### ISSUE TITLE
Question regarding squared terms and multiple interactions

### ISSUE THREAD

**Issue by methodds** [strengejacke/ggeffects#1]
Hi,

first of all thanks for yet another nice package :) 
I don't fully understand whether in ggeffects all interactions and polynomial terms are correctly accounted for when computing average marginal effects.
As an example, this is a nbreg model, effects calculated with your package:

````
fit <- glm.nb(comments_count_fb ~ maxprop + I(day^2) + day * maxprop , data = d)
ame <- ggaverage(fit, terms = c("day", "maxprop"))

ame %>% filter(group %in% c(6,9)) %>% 
ggplot( aes(x, predicted, colour = group)) + 
  geom_line()  + ylim(0,2000) + theme_bw() + 
  scale_x_continuous(breaks = c(6,63,123,184,246,308, 369, 429,489),
                     labels = c("15/01", "15/03", "15/05",
                                "15/07", "15/09", "15/11",
                                "16/01", "16/03", "16/05"))
````

![image](https://user-images.githubusercontent.com/7460499/27763844-c8b4047e-5e8b-11e7-8e0d-26fb99fde737.png)

And this is the same in Stata (the coefficients are equivalent):

````
 nbreg comments_count_fb c.day##c.day##i.maxprop
 margins, at(day=(6  63  123  184  246 308 369  429  489) maxprop=(9 6)) 

 marginsplot, legend(ring(0) position(12) bmargin(large)) title("") ///
  xlabel(6 "15/01" 63 "15/03"  123 "15/05" ///
 184 "15/07" 246  "15/09"  308 "15/11" 369  ///
 "16/01"  429 "16/03" 489 "16/05",  angle(vertical)) ///
 ytitle("Predicted number of Comments") scheme(s1mono)
````
![graph](https://user-images.githubusercontent.com/7460499/27763854-06fbfd68-5e8c-11e7-9f54-b306ee893662.png)

Especially for the red curve this looks a little different to me. Do you have an idea why? And is there a reason why confidence intervals are missing for ``ggaverage()`` estimates? The two columns ``conf.low`` and ``conf.high`` are filled with ``NA`` values for me.

**Comment by methodds** [comment]
While comparing output from ``ggpredict`` and ``ggaverage`` (which look very different to me, see below) I found a bug for the `terms` parameter:

````
mydf <- ggpredict(fit, terms = c("day [6,63,123,184,246,308, 369, 429,489]", "maxprop [6,9]"))
mydf %>% ggplot( aes(x, predicted, colour = group)) +
  geom_line()
````
![image](https://user-images.githubusercontent.com/7460499/27764063-abf9170c-5e90-11e7-95ed-2312fb4bf94d.png)
`mydf` includes group 5 instead of group 6. I am pretty sure that this has to do something with the factor levels of  the variable: 
```
levels(d$maxprop)
 [1] "6"  "1"  "2"  "3"  "4"  "5"  "7"  "8"  "9"  "10"
```
Using `1` inside `terms`  produces this:
````
mydf <- ggpredict(fit, terms = c("day [6,63,123,184,246,308, 369, 429,489]", "maxprop [1,9]"))
mydf %>% ggplot( aes(x, predicted, colour = group)) +
  geom_line()
````
![image](https://user-images.githubusercontent.com/7460499/27764093-26c8b41a-5e91-11e7-9d62-d1e7d2960401.png)

**Comment by strengejacke** [comment]
I think `ggpredict()` is what you typically want. And I'm not sure if I use the term _average marginal effects_ in the same way as, e.g., Thomas Leeper in his vignette from his **margins**-pkg (which may be the same understanding as in Stata). 

Maybe I should become more clear on this distinction, when I get more familiar with it ;-)

According to your main point with category 5 or 6: so, which output is correct? Stata or R? Is it the 6th category (i.e. value = 5)  or value 6 that should be (and is being) plotted?

**Comment by methodds** [comment]
Hey, thanks for investigating. It's definitely the 6th category, that's what I specified in the syntax:
``  "maxprop [6,9]" ``.

**Comment by strengejacke** [comment]
Yes, but I was asking for which _value_ is used? 6, or the value of the 6th category (5)? If the latter, the output from Stata would be misleading.

**Comment by methodds** [comment]
Ah sorry, the value 6 was used. In Stata there is no object class for factors, you just define factors just for the regressions with an `i`, e.g. `i.maxprop`.

**Comment by strengejacke** [comment]
Do you have a (reduced) dataset to reproduce the issue with the wrong category labels in the legend?

**Comment by methodds** [comment]
yep, please find it [here](https://www.dropbox.com/s/9lcj6reqb8yqczh/pegida10_props.xlsx?dl=1).

```
library(readxl)
library(MASS)
library(ggeffects)
library(tidyverse)
d <- read_excel('pegida10_props.xlsx')

d$maxprop <- factor(d$maxprop, 
                       levels = c(6,1,2,3,4,5,7,8,9,10) )
```

**Comment by strengejacke** [comment]
ok, interestingly, `plot()` works fine, regarding the labelling.

```
plot(mydf)
```

![rplot](https://user-images.githubusercontent.com/26301769/27798038-19eb48ae-6010-11e7-83c1-0fca8d7e62ef.png)

**Comment by methodds** [comment]
Hm this is pretty strange, might this be due to another package working in the background for which I do not have the same version?

**Comment by strengejacke** [comment]
```
d$maxprop2 <- factor(d$maxprop, levels = c(6,1,2,3,4,5,7,8,9,10) )
fit <- glm.nb(comments_count_fb ~ maxprop2 + I(day^2) + day * maxprop2, data = d)
mydf <- ggpredict(fit, terms = c("day [6,63,123,184,246,308, 369, 429,489]", "maxprop2 [6,9]"))
```

![rplot01](https://user-images.githubusercontent.com/26301769/27798248-d03e05ce-6010-11e7-9864-2dc47890dae3.png)

```
# A tibble: 18 x 5
       x predicted  conf.low conf.high  group
   <dbl>     <dbl>     <dbl>     <dbl> <fctr>
 1     6 1456.3813 1130.3937 1876.3786      6
 2     6  636.6488  543.9512  745.1434      9
 3    63 1070.2797  871.0094 1315.1392      6
 4    63  497.5987  442.8485  559.1178      9
 5   123  786.2454  665.8191  928.4531      6
 6   123  390.0367  357.4703  425.5700      9
 7   184  584.2787  510.5348  668.6746      6
 8   184  309.6009  288.5187  332.2236      9
 9   246  439.5839  393.5241  491.0348      6
10   246  249.0739  233.7864  265.3610      9
11   308  336.5098  306.5149  369.4400      6
12   308  203.8865  191.6513  216.9027      9
13   369  263.1349  241.5735  286.6206      6
14   369  170.2958  159.3382  182.0069      9
15   429  210.0027  191.4615  230.3395      6
16   429  145.0160  133.6535  157.3444      9
17   489  170.3443  151.4340  191.6160      6
18   489  125.5116  112.3459  140.2201      9
```

Still, seems to work properly... Or am I missing something?

**Comment by methodds** [comment]
No it seems absolutely correct. I remember that my tibbles included "5" and not "6". Please let me check whether I can reproduce this again on another computer.

**Comment by strengejacke** [comment]
If the values in `days` are equally distant, you can simply use:

```
mydf <- ggpredict(fit, terms = c("day", "maxprop2 [6,9]"))
```

This produces a little smoother plot.

**Comment by strengejacke** [comment]
> And is there a reason why confidence intervals are missing for ggaverage() estimates? The two columns conf.low and conf.high are filled with NA values for me.

Yes. `ggaverage()` calls `ggpredict()` with `full.data = TRUE`. This means, the dataset for prediction (argument `newdata` in `predict()`) is _not_ based on a combination of all possible values (generated with `expand.grid()`), but with the raw data that was used to fit the model.

Compare following:

```
library(ggeffects)
data(efc)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
ggpredict(fit, terms = "c12hour")
#> # A tibble: 62 x 5
#>        x predicted conf.low conf.high  group
#>    <dbl>     <dbl>    <dbl>     <dbl> <fctr>
#>  1     4  74.43040 72.33073  76.53006      1
#>  2     5  74.17710 72.09831  76.25588      1
#>  3     6  73.92379 71.86555  75.98204      1
#>  4     7  73.67049 71.63242  75.70857      1
#>  5     8  73.41719 71.39892  75.43546      1
#>  6     9  73.16389 71.16504  75.16275      1
#>  7    10  72.91059 70.93076  74.89042      1
#>  8    11  72.65729 70.69608  74.61850      1
#>  9    12  72.40399 70.46098  74.34700      1
#> 10    14  71.89738 69.98948  73.80529      1
#> # ... with 52 more rows

ggpredict(fit, terms = "c12hour", full.data = T)
#> # A tibble: 815 x 7
#>        x predicted conf.low conf.high observed  residuals  group
#>    <dbl>     <dbl>    <dbl>     <dbl>    <dbl>      <dbl> <fctr>
#>  1     4  78.20477 74.68527  81.72428       80   1.795229      1
#>  2     4  84.77341 80.90060  88.64621       75  -9.773407      1
#>  3     4  78.60006 74.27297  82.92715       75  -3.600060      1
#>  4     4  83.19453 78.69174  87.69731      100  16.805471      1
#>  5     4  74.00559 69.67775  78.33343       95  20.994409      1
#>  6     4  74.32866 71.99907  76.65824       15 -59.328659      1
#>  7     4  69.73419 67.12733  72.34105       50 -19.734190      1
#>  8     4  65.13972 62.02165  68.25779       95  29.860280      1
#>  9     4  71.70836 67.31317  76.10355       95  23.291644      1
#> 10     4  74.32866 71.99907  76.65824       80   5.671341      1
#> # ... with 805 more rows
```

```

Value **4** appears once in the upper, but several times in the lower result. That is because `ggpredict()`, when generating `newdata` (with `expand.grid()` sets all co-variates to mean (and factors to reference etc., see argument `typical`), whil `ggaverage()` simply uses `model.frame(fit)` as `newdata` argument. 

If you would plot the lower result:

```
mydf <- ggpredict(fit, terms = "c12hour", full.data = T)
ggplot(mydf, aes(x = x, y = predicted)) + geom_line()
```

![rplot](https://user-images.githubusercontent.com/26301769/27819804-2caea616-609c-11e7-8f1f-fd059d171b59.png)

You see, there is of course no straight line, because co-variates are not held constant, but are used as they appear in the data (and they vary by obserbvation). Now `ggaverage()` just computes the mean value for `prediction`, for each value-group in `x`:

```
dat <- mydf %>% 
  group_by(x, group) %>% 
  summarise(predicted = mean(predicted)) %>% 
  ungroup()

dat
#> # A tibble: 62 x 3
#>        x  group predicted
#>    <dbl> <fctr>     <dbl>
#>  1     4      1  78.20028
#>  2     5      1  79.49254
#>  3     6      1  79.57242
#>  4     7      1  76.04909
#>  5     8      1  77.01783
#>  6     9      1  74.14616
#>  7    10      1  77.71147
#>  8    11      1  73.26616
#>  9    12      1  76.65181
#> 10    14      1  73.10446
#> # ... with 52 more rows

ggplot(dat, aes(x = x, y = predicted)) + geom_line()
```

![rplot01](https://user-images.githubusercontent.com/26301769/27819950-c5dff6dc-609c-11e7-916e-42cb888fc067.png)

This is still no straight line, so I calculate - based on the model - linear or loess-smoothed regression on these predicted values, to "flatten" or "smooth" this line. Now, since this is a regression model based on completely different data, the standard error only applies to this "small" data set (see `dat`), not to the originally predicted values. Thus, I have no standard errors nor confidence intervals. I tried to do the same I did for the predicted values above for standard errors as well, but the confidence region does not really match my "smoothed" predictions / lines.

But now you probably understand what `ggaverage()` is doing and what I consider as "average marginal effects". :-)

**Comment by methodds** [comment]
I see, thx for the explanation :)

**Comment by strengejacke** [comment]
ok, fixed this issue. will commit tonight.

**Comment by methodds** [comment]
Thanks for the fix! Do you also know how to fix the problem with the factor variable? Installing the latest ggeffects version did not help:
``
mydf <- ggpredict(fit, terms = c("day", "maxprop [6,9]"))
``


![image](https://user-images.githubusercontent.com/7460499/28519366-959e1344-706b-11e7-9c91-5e46a5f7b6bd.png)

**Comment by strengejacke** [comment]
This one is not committed yet, because I plan a direct submit to CRAN, and don't want the GitHub-version with the CRAN version number to be behind of CRAN.

Say, I commit to GitHub, using pkg version 0.2.0, because it should be submitted. You install from GitHub, then I submit version 0.2.0 to CRAN, due to check issues I need some revisions and resubmit to CRAN. If you now update your packages, you won't be notified about the CRAN version, because you already have (an old) version 0.2.0 installed from GitHub...

This is mostly when I already prepare the CRAN submission, forgot the latest GitHub commit and am too lazy to change the version number back for GitHub. ;-)

**Comment by methodds** [comment]
Ah i see. I also noted that it is not necessarily a good idea to mix up sj packages from github and CRAN due to version dependencies. Anyway, thanks for fixing this :)

**Comment by strengejacke** [comment]
Yes, once you started using GitHub-version actively, you need to keep updated with all GitHub versions, due to interdependencies.

**Comment by methodds** [comment]
But if I install them in the correct order it should work right? Because I just received an error for sjPlot (which is last in your suggested order):
```
Error in parse(outFile) : repeated formal argument 'rm.terms' on line 50
ERROR: unable to collate and parse R files for package ‘sjPlot’
* removing ‘/home/cs/R/x86_64-pc-linux-gnu-library/3.4/sjPlot’
* restoring previous ‘/home/cs/R/x86_64-pc-linux-gnu-library/3.4/sjPlot’
Installation failed: Command failed (1)
```

**Comment by strengejacke** [comment]
Building fails more me, too, I just saw. One argument was duplicated, hence the error. Installing sjPlot from GitHub gives currently not much benefits over the CRAN version, if any. It's more a regular backup, because I write the new function from scratch.

My release plan is to complete `plot_models()` (finished yet) and `plot_model()`, and submit to CRAN. Table functions will follow in another update. I perhaps introduce `plot_model()` and `plot_models()` silently and ue the update as "public" testing, but maybe I'll also add a deprecated msg to sjp.lm, sjp.lmer, sjp.int, sjp.glm etc., but I'm not quite sure yet.

**Comment by methodds** [comment]
Ok. Do you think the complete sjverse will be updated on CRAN until October? I'm asking because we will plan our data analysis introductory courses and would like to use sjverse again :)

**Comment by strengejacke** [comment]
ggeffects update just hit CRAN - you may check whether this issue is completely solved for you.

sjmisc-update is already finished, but needs prior update of sjPlot ;-) I hope to get sjPlot ready within the next two weeks, else it will be September.
