### ISSUE TITLE
Error since updating to version 0.2.2

### ISSUE THREAD

**Issue by dnbarron** [strengejacke/ggeffects#10]
I've been using `ggpredict` on a `polr` object without any problem, but since updating to the latest CRAN version, I get the following error:

Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"

The command that generates this error is:
`ggpredict(fit.tri.int.b, terms = c('chain_type', 'sector'))`

The `sector` variable in the data is of class character rather than factor, which seems to be the source of the error. I converted sector to a factor and the error disappears, and that is a simple workaround, but I'd prefer not to have to use factors if I can avoid it.  Is this something that could be fixed?

Thanks,
David

**Comment by strengejacke** [comment]
Thanks, this is an issue with `sjmisc::to_label()`. I fixed this issue, will commit to GitHub tonight. Please either update sjmisc from GitHub, or wait for the next CRAN update (which, however, may take some time to submit).

**Comment by dnbarron** [comment]
Thanks! Much appreciated.
