### ISSUE TITLE
Simulate Predictions from models with binary outcome variable

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#102]
I was really excited to re-find ggpredict() to create predictions for a model where my response variable is binary. When I went to use type="sim," though I was given this error: 
```
Error: Can't simulate predictions from models with binary, categorical or ordinal outcome. Please use another option for argument `type`.
```
I wanted to post to ask to see if there is any plan to incorporate that in the near future?

**Comment by strengejacke** [comment]
`simulate()` returns values on the response scale, i.e. a vector of 0 and 1 in your case. In such cases, you can't calculate proper SDs or CIs, or even an average value for the response. That's why ggpredict throws an error in such cases. The related code is here:
https://github.com/strengejacke/ggeffects/blob/master/R/simulate_predictions.R

**Comment by rpmady** [comment]
Okay, I think I was missing the mark. I thought with simulate it would produce 0's and 1's and then from there use the model to create predictions with SDs or CIs.

**Comment by strengejacke** [comment]
> Okay, I think I was missing the mark. I thought with simulate it would produce 0's and 1's and then from there use the model to create predictions with SDs or CIs.

If I understand aright, that would mean that you refit the model with a new response? But that would lead to completely different coefficients (and hence, predictions...).

**Comment by rpmady** [comment]
I'm not sure I'm following. What I meant to say was that I thought using simulate() would use the model to create predictions that would give me a probability of success. To do that, it would simulate  0's and 1's (the current response variable) and then refit the model based on the simulations to create predictions.

**Comment by strengejacke** [comment]
yes, that was what I meant ;-) so you would expect this be the purpose of `type = "sim"`?

**Comment by rpmady** [comment]
Woops, okay, well we are definitely on the same page now :) 
That was my expectation.

**Comment by strengejacke** [comment]
Let me take an example from the Appendix from [this paper](https://journal.r-project.org/archive/2017/RJ-2017-066/index.html):

``` r
library(glmmTMB)
library(dplyr)
library(ggplot2)
library(ggeffects)

nbm2 <- glmmTMB(count ~ spp * mined + (1 | site), Salamanders, family = nbinom2)
sims <- simulate(nbm2, seed = 1, nsim = 1000)

simdatlist <- lapply(sims, function(count) {
  cbind(count, Salamanders[, c('site', 'mined', 'spp')])
})

simdatsums <- lapply(simdatlist, function(x) {
  x %>% 
    group_by(spp, mined) %>% 
    summarize(
      absence = mean(count == 0),
      mu = mean(count)
    )
})

ssd <- do.call(rbind, simdatsums)

real <- Salamanders %>% 
  group_by(spp, mined) %>% 
  summarize(
    absence = mean(count == 0),
    mu = mean(count)
  )

ggplot(ssd, aes(x = absence, color = mined))+
  geom_density(adjust = 4) +
  facet_wrap( ~ spp) +
  geom_point(data = real,
             aes(x = absence, y = 1, color = mined),
             size = 2) +
  xlab("Probability that salamanders are not observed") + ylab(NULL)
```

![](https://i.imgur.com/bsqbRnc.png)

``` r
ggplot(ssd, aes(x = mu, color = mined))+
  geom_density(adjust = 4) +
  facet_wrap( ~ spp) +
  geom_point(data = real,
             aes(x = mu, y = 1, color = mined),
             size = 2) +
  xlab("Mean count of observed salamanders") + ylab(NULL)
```

![](https://i.imgur.com/Hl8jnZ3.png)

``` r
ggpredict(nbm2, c("spp", "mined")) %>% plot()
```

![](https://i.imgur.com/4VNFf9V.png)

```r
ggpredict(nbm2, c("spp", "mined"), type = "sim") %>% plot(ci = FALSE)
```

![image](https://user-images.githubusercontent.com/26301769/67636151-cc3c5180-f8cd-11e9-8a67-f17597f18f43.png)


<sup>Created on 2019-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here, the authors used `simulate()` to simulate a response distribution. In the first plot, they plotted the density for observing "absence" (i.e. simulated response = 0), and compared it to the true numbers of absence in the data.

In the second plot, I plotted the mu values, and the values at the x-axis represent the predicted (or simulated) mean value of observing salamanders. You get (almost) the same numbers when using `ggpredict()` (see third plot). So the dots resp. the "peaks" at the x-axis in plot 2 are comparable to the dots along the y-axis in plot 3. Plot 4 uses `simulate()` instead `predict()`, but comparable to plot 2, takes the mean values of the simulated response values.

So, I understand `simulate()` to predict a kind of "posterior distribution", for which we can take values like mean or median to get a "point estimate" of predictions, and the SD or MAD to get the related CI for those predicted values. I would not use the simulated response values to create new data, from which we refit models to generate new predictions...

**Comment by rpmady** [comment]
Okay, so simulate(), as used in the paper and used within the ggpredict() creates a response distribution then based on the model? Like you said, a series of 0's and 1's?

**Comment by strengejacke** [comment]
Yes, for each observation, `simulate()` returns a series of 0/1, based on the numbers of simulations:

``` r
library(lme4)
#> Loading required package: Matrix
data("mtcars")
m <- glmer(am ~ mpg + hp + ( 1 | carb), data = mtcars, family = binomial())
#> Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: large eigenvalue ratio
#>  - Rescale variables?
head(simulate(m, nsim = 10))
#>                   sim_1 sim_2 sim_3 sim_4 sim_5 sim_6 sim_7 sim_8 sim_9
#> Mazda RX4             0     1     0     1     0     0     0     0     0
#> Mazda RX4 Wag         0     0     1     0     0     1     0     0     1
#> Datsun 710            1     0     1     1     1     1     1     1     1
#> Hornet 4 Drive        1     0     0     0     0     1     1     1     0
#> Hornet Sportabout     1     0     1     1     1     0     0     0     0
#> Valiant               0     0     0     0     0     0     0     0     0
#>                   sim_10
#> Mazda RX4              1
#> Mazda RX4 Wag          0
#> Datsun 710             1
#> Hornet 4 Drive         1
#> Hornet Sportabout      1
#> Valiant                0
```

And running just one simulation to simulate a "new" response for refitting the model and making new predictions is not very exact, because the distribution of response values being 0 or 1 can differ quite substantially:

``` r
library(lme4)
#> Loading required package: Matrix
data("mtcars")
m <- glmer(am ~ mpg + hp + ( 1 | carb), data = mtcars, family = binomial())
#> Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: large eigenvalue ratio
#>  - Rescale variables?

head(simulate(m))
#>                   sim_1
#> Mazda RX4             0
#> Mazda RX4 Wag         1
#> Datsun 710            0
#> Hornet 4 Drive        0
#> Hornet Sportabout     0
#> Valiant               0

head(simulate(m))
#>                   sim_1
#> Mazda RX4             0
#> Mazda RX4 Wag         0
#> Datsun 710            0
#> Hornet 4 Drive        0
#> Hornet Sportabout     1
#> Valiant               0

head(simulate(m))
#>                   sim_1
#> Mazda RX4             0
#> Mazda RX4 Wag         1
#> Datsun 710            0
#> Hornet 4 Drive        1
#> Hornet Sportabout     1
#> Valiant               0

head(simulate(m))
#>                   sim_1
#> Mazda RX4             1
#> Mazda RX4 Wag         1
#> Datsun 710            0
#> Hornet 4 Drive        0
#> Hornet Sportabout     0
#> Valiant               0
```
