### ISSUE TITLE
How to predict dependent variable in another range of independent variable

### ISSUE THREAD

**Issue by UNCcrawler** [strengejacke/ggeffects#104]
Hi, could you please provide an example on how to predict data in another range? I used to use predict(lm model, interval = 'confidence', newdata = PRED) to do this in linear model. Now I switch to your package for linear mixed effect model. How can I submit the newdata to ggpredict()? ggpredict(model, type = 'fe', newdata = PRED) didn't work. I got an error saying 'Error in predict.merMod(model, newdata = fitfram, type = "response", re.form = ref,  : 
  formal argument "newdata" matched by multiple actual arguments'. Thanks!

**Comment by strengejacke** [comment]
Please see these vignettes / docs:

https://strengejacke.github.io/ggeffects/
https://strengejacke.github.io/ggeffects/articles/ggeffects.html

**Comment by UNCcrawler** [comment]
Thanks for the quick response. I am still confused. The given examples predicted observations in the range consistent with the data used for the model. I want to do extrapolation. For instance, my model was fitted using independent variable range from 5 to 20. I want to predict the observation in the independent variable range from 20 to 40.

**Comment by strengejacke** [comment]
Ok, predictions at certain values are described here
https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html
