### ISSUE TITLE
add dodge to raw data points when plotting means and add.data = TRUE

### ISSUE THREAD

**Issue by dr-JT** [strengejacke/ggeffects#106]
**Describe the bug**
When plotting means and add.data = TRUE, the raw data points do not have any dodge to them. The data points for one group overlaps with the other group, while the means do have some horizontal space between them. Shouldn't the raw data points fall along the same vertical axis as the mean/error bar? 

**Screenshots**

**Comment by dr-JT** [comment]
Based on the example provided in the article "Introduction: Plotting Marginal Effects"

Run this code to see what I am referring to:

library(ggeffects)
library(sjmisc)
data(efc)
efc$c172code <- to_label(efc$c172code)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)

# categorical variables have errorbars
dat <- ggpredict(fit, terms = c("c172code", "c161sex"))
plot(dat, add.data = TRUE, jitter = .2, dodge = 1)

**Comment by dr-JT** [comment]
Based on the example provided in the article "Introduction: Plotting Marginal Effects"

Run this code to see what I am referring to:

library(ggeffects)
library(sjmisc)
data(efc)
efc$c172code <- to_label(efc$c172code)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)

dat <- ggpredict(fit, terms = c("c172code", "c161sex"))
plot(dat, add.data = TRUE, jitter = .2, dodge = 1)

**Comment by strengejacke** [comment]
The problem is that I add a jitter to the data points, and you can't mix jitter with dodge:

> Error: You must specify either `position` or `width`/`height`

**Comment by dr-JT** [comment]
In ggplot2 you can mix jitter with dodge using position_jitterdodge()

https://ggplot2.tidyverse.org/reference/position_jitterdodge.html

But maybe it is more complicated with how this package is written? Idk

**Comment by strengejacke** [comment]
Ah, good to know! Obviously I didn't follow the past development of ggplot in detail. Then it should be rather easy to do.
