### ISSUE TITLE
Add rawdata attribute to ggemmeans output

### ISSUE THREAD

**Issue by crsh** [strengejacke/ggeffects#108]
**Describe the solution you'd like**
In contrast to `ggpredict()` the output of `ggemmeans()` does not have a `rawdata` attribute. This means that raw data can not be plotted.

~~~r
plot(ggpredict(lm(dist ~ speed, cars), term = "speed"), rawdata = TRUE)
plot(ggemmeans(lm(dist ~ speed, cars), term = "speed"), rawdata = TRUE)
~~~
~~~
Raw data not available.
~~~

**How could we do it?**
From a quick first browse of the source code, I suspect it may be as simple as adding `attr(mydf, "rawdata") <- .get_raw_data(model, ori.mf, terms)` to the function.

If that's indeed all it takes, I'd be happy to open a PR.

(Sorry for posting prematurely, inadvertently hit some hotkeys.)

**Comment by strengejacke** [comment]
Yes, it indeed looks like that should be enough. Gel free to open a PR, and add yourself as contributor.
