### ISSUE TITLE
Raw data points omitted when plotting interaction between continuous variables

### ISSUE THREAD

**Issue by crsh** [strengejacke/ggeffects#110]
**Describe the bug**
When plotting predictions when the grouping variable is continuous, the added raw data is omitted if it doesn't numerically match the grouping levels (e.g., mean plus/mins one standard deviation). It would be great if the data could be plotted regardless of the scale of the grouping variable.

**To Reproduce**
This example illustrates the problem:

~~~r
m <- lm(Sepal.Length ~ Petal.Length * Petal.Width, iris)
m_pred <- ggpredict(m2, terms = c("Petal.Length", "Petal.Width"))

plot(m_pred, rawdata = TRUE)

# The 5 plotted raw data points
subset(iris, Petal.Width %in% levels(m_pred$group))
~~~
~~~
   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
74          6.1         2.8          4.7         1.2 versicolor
83          5.8         2.7          3.9         1.2 versicolor
91          5.5         2.6          4.4         1.2 versicolor
93          5.8         2.6          4.0         1.2 versicolor
96          5.7         3.0          4.2         1.2 versicolor
~~~

**Screenshots**

![Screenshot from 2019-11-19 12-15-50](https://user-images.githubusercontent.com/2195485/69142093-5db27400-0ac6-11ea-876c-7c848d8ac9ec.png)

**Possible fix/implementation**

The problem here is the mismatch between the discrete color/fill scale and the continuous grouping variable. By preserving the contiuousness of the grouping variable the problem could be addressed fixed. From looking at the code it wasn't obvious to me where to me where best to do this (probably somewhere in the plot method), so I've tried to illustrate the solution by building the plot from scratch:

~~~r
moderator_values <- sort(as.numeric(as.character(unique(m_pred$group))))

ggplot(as.data.frame(m_pred), aes(x = x, y = predicted, group = group, color = as.numeric(as.character(group)), fill = as.numeric(as.character(group)))) +
  geom_point(data = attr(m_pred, "rawdata"), aes(x = jitter(x), y = jitter(response)), alpha = 0.6) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), color = FALSE, alpha = 0.2) +
  geom_line() +
  scale_color_continuous(guide = "legend", aesthetics = c("colour", "fill"), breaks = moderator_values, limits = range(c(moderator_values, range(attr(m_pred, "rawdata")$group))), labels = paste(format(moderator_values, digits = 2), c("(M + 1SD)", "(M)", "(M - 1SD)"))) +
  labs(color = "Petal.Width", fill = "Petal.Width")
~~~

![Screenshot from 2019-11-19 14-08-12](https://user-images.githubusercontent.com/2195485/69149103-0e743f80-0ad6-11ea-8ef7-40d7fcb7be33.png)

Alternatively, it would be possible to replace the legend by a full colorbar and add the values at which predictions are plotted:

~~~r
moderator_values <- sort(c(as.numeric(as.character(unique(m_pred$group))), range(c(attr(m_pred, "rawdata")$group, as.numeric(as.character(unique(m_pred$group)))))))

ggplot(as.data.frame(m_pred), aes(x = x, y = predicted, group = group, color = as.numeric(as.character(group)), fill = as.numeric(as.character(group)))) +
  geom_point(data = attr(m_pred, "rawdata"), aes(x = jitter(x), y = jitter(response)), alpha = 0.6) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), color = FALSE, alpha = 0.2) +
  geom_line() +
  scale_color_continuous(guide = "colorbar", aesthetics = c("colour", "fill"), breaks = moderator_values, limits = range(moderator_values), labels = paste(format(moderator_values, digits = 2), c("", "(M + 1SD)", "(M)", "(M - 1SD)"))) +
  labs(color = "Petal.Width", fill = "Petal.Width")
~~~

![Screenshot from 2019-11-19 12-20-26](https://user-images.githubusercontent.com/2195485/69142437-12e52c00-0ac7-11ea-9030-fed99d4f7040.png)

**Comment by strengejacke** [comment]
You describes the problem very well - indeed, we have "discrete groups" even for mean +/- 1 SD, so only those data exactly matching these value are preserved. The related code-line is here:
https://github.com/strengejacke/ggeffects/blob/ec193a64800ce06cf6b0001051fbbf4e5561d430/R/plot.R#L546

I suggest using your first proposal, with _no_ continuous _legend_ for the continuous color scale. Maybe the information, if the "grouping variable" is actually continuous, needs to be saved somewhere (probably in the function `.get_data_grid()` or so...
