### ISSUE TITLE
ggeffect command does not work if random effects come first in formula

### ISSUE THREAD

**Issue by PCK1992** [strengejacke/ggeffects#113]
**Describe the bug**
I tried to calculate the predicted effects of a random-effects model through the `ggeffect` command. I noticed that the command does not work if random effects are the first term in a regression model.

**To Reproduce**

```
library(lme4) 
library(ggeffects)
lmm.data <- read.table("http://bayes.acs.unt.edu:8083/BayesContent/class/Jon/R_SC/Module9/lmm.data.txt",
                       +                        header=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)


mod1a <- lmer(social ~ open + extro + agree + school + (1|school), data = lmm.data)
mod1b <- lmer(social ~ (1|school) + open + extro + agree + school, data = lmm.data)
#summary(mod1a)
#summary(mod1b)
#Results are the same!

ggeffect(mod1a) # does work
ggeffect(mod1b)# does not work
```

I could reproduce this error on a Linux and a Windows PC.

Current version of ggeffects package is 0.13.0. Perhaps you could somehow account for the ordering of the formula? I think it's not a big deal but it took me a few minutes to figure out why it didn't work.

**Comment by strengejacke** [comment]
Should be fixed now, after you update [*insight*](https://github.com/easystats/insight) from **GitHub**.
