### ISSUE TITLE
p-values for marginal effects?

### ISSUE THREAD

**Issue by katherinesiegel** [strengejacke/ggeffects#115]
Thanks for making this package-- it's really great! Apologies if this is an ignorant question, but is it possible to get p-values for the marginal effects using the ggpredicts() command, like you can using the margins package? (There's an example of the summary table from margins here: https://www.brodrigues.co/blog/2017-10-26-margins_r/).

Thanks for any help you're able to provide!

**Comment by strengejacke** [comment]
`margins()` does not alter any p-values. If you compare the output from the model summary and from `margins()`, you'll see that the p-values are the same.

I was thinking about p-values for pairwise comparisons, however, that would be a completely different function / output, so it does not relate to what `ggpredict()` et al. do now.

According to your initial question: I'm not sure where the p-values should relate to? To a "reference" category (then they would be the same as in the model-summary), or predicted value compared to the "zero"? I'm not sure which hypothesis-testing might make sense in this case (to calculate a "p"), or if se/ci for the estimated marginal means are sufficient?

I guess most sense would make comparing to different predicted values against each other (i.e. pairwise comparison), but this would not fit into the output of the current result of ggpredict.

See examples:

``` r
library(emmeans)
#> Welcome to emmeans.
#> NOTE -- Important change from versions <= 1.41:
#>     Indicator predictors are now treated as 2-level factors by default.
#>     To revert to old behavior, use emm_options(cov.keep = character(0))
library(ggeffects)
library(sjmisc)

data(efc)
efc$c161sex <- to_label(efc$c161sex)
efc$c172code <- to_label(efc$c172code)
levels(efc$c172code) <- c("low", "medium", "high")

m <- lm(neg_c_7 ~ c161sex * c172code, data = efc)

ggemmeans(m, c("c161sex", "c172code"))
#> 
#> # Predicted values of Negative impact with 7 items
#> # x = carer's gender
#> 
#> # c172code = low
#>       x predicted std.error conf.low conf.high
#>    Male    11.024     0.607    9.833    12.215
#>  Female    12.088     0.332   11.436    12.739
#> 
#> # c172code = medium
#>       x predicted std.error conf.low conf.high
#>    Male    11.277     0.367   10.556    11.997
#>  Female    11.849     0.196   11.463    12.235
#> 
#> # c172code = high
#>       x predicted std.error conf.low conf.high
#>    Male    11.674     0.573   10.550    12.798
#>  Female    12.632     0.377   11.891    13.373

emmeans(m, c("c161sex", "c172code")) %>%
  contrast(method = "pairwise") %>%
  as.data.frame()
#>                       contrast   estimate        SE  df    t.ratio   p.value
#> 1        Male,low - Female,low -1.0632010 0.6916208 827 -1.5372601 0.6401845
#> 2       Male,low - Male,medium -0.2523955 0.7091776 827 -0.3558988 0.9992515
#> 3     Male,low - Female,medium -0.8247146 0.6377813 827 -1.2930994 0.7889024
#> 4         Male,low - Male,high -0.6495228 0.8344475 827 -0.7783867 0.9711432
#> 5       Male,low - Female,high -1.6076852 0.7145359 827 -2.2499714 0.2162217
#> 6     Female,low - Male,medium  0.8108055 0.4949264 827  1.6382346 0.5733188
#> 7   Female,low - Female,medium  0.2384864 0.3857257 827  0.6182798 0.9897064
#> 8       Female,low - Male,high  0.4136782 0.6620588 827  0.6248360 0.9891969
#> 9     Female,low - Female,high -0.5444842 0.5025742 827 -1.0833908 0.8880404
#> 10 Male,medium - Female,medium -0.5723191 0.4163867 827 -1.3744896 0.7424053
#> 11     Male,medium - Male,high -0.3971273 0.6803789 827 -0.5836855 0.9921047
#> 12   Male,medium - Female,high -1.3552898 0.5264735 827 -2.5742791 0.1047801
#> 13   Female,medium - Male,high  0.1751918 0.6055969 827  0.2892878 0.9997280
#> 14 Female,medium - Female,high -0.7829706 0.4254486 827 -1.8403412 0.4402904
#> 15     Male,high - Female,high -0.9581624 0.6859622 827 -1.3968152 0.7290221
```

<sup>Created on 2019-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by katherinesiegel** [comment]
Thanks for the response! I'm looking for a way to get both predicted probability values and marginal effects values (with p-values) for a logit model with a categorical variable over time-- I want to calculate the change over time in the effect of being in one category vs the other on the probability of an event occurring. 

Here's some sample data:
`df <- data.frame(year = rep(2001:2010, each = 100), 
state = rep(c("montana", "idaho", "colorado", "wyoming", "utah"), times = 10, each = 20), 
site_id = rep(1:100, times = 10),
cat_variable = rep(0:1, times = 5, each = 10),
ind_cont_variable = rnorm(100, mean = 20, sd = 5),
event_occurred = as.factor(sample(c(0, 1), replace = TRUE, size = 1000)))`

and a model: 
`fit_df <- glmer(event_occurred ~ cat_variable + ind_cont_variable + year + cat_variable*year + (1|site_id), data = df, family = binomial(link = "logit"), nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))`

So I've been using ggpredict to get the predicted probability of the event occurring for samples from each of the two categories (cat_variable) in each year:
`fit_pp <- ggpredict(fit_df, terms = c("year [all]", "cat_variable"))`

Is that the correct use of ggpredict? And how would I then derive the marginal effect of being in each category in each year?

Thanks again for your help!

**Comment by strengejacke** [comment]
> I want to calculate the change over time in the effect of being in one category vs the other on the probability of an event occurring.

I'm still not sure what you exactly want to know. In the following example, you see that the time trend (`year`) is not significant. However, the (differing) trend for `cat_variable` is significant, i.e. the effect of `year` is significantly different for the `cat_variable` levels.

``` r
library(ggeffects)
library(lme4)
set.seed(1)
df <- data.frame(year = rep(2001:2010, each = 100), state = rep(c("montana", "idaho", "colorado", "wyoming", "utah"), times = 10, each = 20), site_id = as.factor(rep(1:100, times = 10)), cat_variable = as.factor(rep(0:1, times = 5, each = 10)), ind_cont_variable = rnorm(100, mean = 20, sd = 5), event_occurred = as.factor(sample(c(0, 1), replace = TRUE, size = 1000)))
m <- glmer(event_occurred ~ cat_variable + ind_cont_variable + year + cat_variable*year + (1|site_id), data = df, family = binomial(link = "logit"), nAGQ = 0, control = glmerControl(optimizer = "nloptwrap"))

summary(m)
#> Generalized linear mixed model fit by maximum likelihood (Adaptive
#>   Gauss-Hermite Quadrature, nAGQ = 0) [glmerMod]
#>  Family: binomial  ( logit )
#> Formula: 
#> event_occurred ~ cat_variable + ind_cont_variable + year + cat_variable *  
#>     year + (1 | site_id)
#>    Data: df
#> Control: glmerControl(optimizer = "nloptwrap")
#> 
#>      AIC      BIC   logLik deviance df.resid 
#>   1387.6   1417.1   -687.8   1375.6      994 
#> 
#> Scaled residuals: 
#>     Min      1Q  Median      3Q     Max 
#> -1.3298 -0.9716  0.7520  0.9407  1.3579 
#> 
#> Random effects:
#>  Groups  Name        Variance Std.Dev.
#>  site_id (Intercept) 0.1567   0.3958  
#> Number of obs: 1000, groups:  site_id, 100
#> 
#> Fixed effects:
#>                      Estimate Std. Error z value Pr(>|z|)  
#> (Intercept)          54.04399   62.87014   0.860   0.3900  
#> cat_variable1      -184.56787   89.19778  -2.069   0.0385 *
#> ind_cont_variable     0.00487    0.01680   0.290   0.7719  
#> year                 -0.02698    0.03135  -0.861   0.3895  
#> cat_variable1:year    0.09202    0.04448   2.069   0.0386 *
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Correlation of Fixed Effects:
#>             (Intr) ct_vr1 ind_c_ year  
#> cat_varibl1 -0.705                     
#> ind_cnt_vrb -0.004  0.000              
#> year        -1.000  0.705 -0.001       
#> ct_vrbl1:yr  0.705 -1.000  0.000 -0.705

pr <- ggpredict(m, terms = c("year [all]", "cat_variable"))
pr
#> 
#> # Predicted probabilities of event_occurred
#> # x = year
#> 
#> # cat_variable = 0
#>     x predicted std.error conf.low conf.high
#>  2001     0.540     0.177    0.454     0.624
#>  2002     0.533     0.153    0.459     0.607
#>  2004     0.520     0.116    0.463     0.576
#>  2006     0.507     0.107    0.454     0.559
#>  2007     0.500     0.116    0.443     0.556
#>  2010     0.480     0.176    0.395     0.566
#> 
#> # cat_variable = 1
#>     x predicted std.error conf.low conf.high
#>  2001     0.431     0.177    0.349     0.518
#>  2002     0.447     0.153    0.375     0.522
#>  2004     0.480     0.116    0.423     0.537
#>  2006     0.512     0.107    0.460     0.565
#>  2007     0.529     0.116    0.472     0.585
#>  2010     0.577     0.177    0.490     0.659
#> 
#> Adjusted for:
#> * ind_cont_variable = 20.54
#> *           site_id = 0 (population-level)
#> Standard errors are on link-scale (untransformed).

plot(pr)
```

![](https://i.imgur.com/MB40ZTm.png)

When you use `ggpredict()`, you can "see" these different trends, because `ggpredict()` shows you the association of `terms` and your outcome at different values for `terms` (in your case: `terms` = `year` and `cat_variable`). `ggpredict()` does not produce other results than your model - it just "visualizes" the association of one or more parameters and your outcome, so it helps interpreting the result. As you can see, the overall time trend ( `year`) is not significant. However, the different time trends for the levels of `cat_variable` are such divergent, that these trends differ significantly. You have the p-values in the summary, and the figure from `ggpredict()`.

**Comment by katherinesiegel** [comment]
OK, I understand now. Thank you for taking the time to explain it to me!
