### ISSUE TITLE
ggpredict and ggemmeans yield different results even conditionned

### ISSUE THREAD

**Issue by Helene035** [strengejacke/ggeffects#116]
**I have built a model with bmrs for which all looks fine (convergence, etc). With this model I investigate parasitism in four butterfly species, between 3 regions and 2 years. I also included a non linear term ("smooth") in the model, which is the week as several sampling were done every year to investigate the phenology of parasitism. Note that the variables "region" and "butterfly_species" were combined into one variable "region_butterfly" because I have a missing contrast for the interaction between one region and one butterfly.

My model is as follow:  

`parasitism=brm(number_parasitized|trials(number_larvae_collected)~0+ region_butterfly+year+s(week,k=4,by=butterfly_species),
          core=4,data=dat.2,iter=10000,warmup=4000,thin=2,family=binomial,
        control=list(adapt_delta=0.99,max_treedepth=15))`

I wish now to illustrate my model with a plot and here come my problem. I do not get equivalent results using ggpredict and ggemmeans even though I conditionned my categorical variables the same way: Let's say I want to plot parasitism rate in 2018 across regions.  

- Using ggemmeans:

`ggemmeans(parasitism,"region_butterfly",condition = list(year="2018"),x.as.factor = TRUE)`

Predicted successes of nb_ind_parasite
x = reg_butt
           x predicted    conf.low        conf.high
   sk_au         0.407         0.357               0.458
   Kr_au         0.277         0.218               0.343
  sk_aio         0.360         0.310               0.411
  Kr_aio         0.269         0.219               0.328
 nor_aio        0.186         0.151               0.228
   sk_va          0.195        0.111               0.308
   Kr_va          0.040        0.018               0.080
 Kr_alev         0.025        0.013               0.045

Adjusted for:
week = 4.74
nb_larvae_in_lab = 4.00

- Using ggpredicts:

`ggpredict(parasitism,terms = c("region_butterfly","year[2018]"),x.as.factor = TRUE)`

Predicted successes of nb_ind_parasite
x = reg_butt
       x predicted conf.low conf.high
   sk_au     1.357    1.127     1.602
   Kr_au     0.891    0.654     1.174
  sk_aio     1.183    0.977     1.397
  Kr_aio     0.863    0.668     1.082
 nor_aio     0.585    0.453     0.740
   sk_va     0.614    0.322     0.979
   Kr_va     0.120    0.052     0.239
 Kr_alev     0.074    0.037     0.134

Adjusted for:
week = 4.74
butterfly_species =   au
number_larvae_collected= 4.00

1. Using ggpredict, I (maybe naively) thought that if I devided x predicted by 4 (as the output says it adjusted for number_larvae_collected= 4.00), I should get the same values as "x predicted" with ggemmeans, as the week adjusted for is also the same (4.74). However, this is not what I get. How to explain this discrepancy? and if this difference is to be expected, what is the differences in the estimation made by these two functions?

2. A bit out of my main issue but as I use a binomial distribution, I was trying to play around the argument "back.tranform= TRUE/FALSE. I noted that the output are always identical, whether the argument is TRUE or FALSE. is that normal?

Thanks a lot !
**

**Comment by strengejacke** [comment]
At 1) The "adjustement" (adjusted values) only refer to at which values are held constant. This is the same for `ggpredict()` and `ggemmeans()` for numerical predictors. See following example:

``` r
library(ggeffects)
data(iris)
m <- lm(Sepal.Width ~ Species + Sepal.Length, data = iris)

ggpredict(m, "Species")
#> 
#> # Predicted values of Sepal.Width
#> # x = Species
#> 
#>           x predicted std.error conf.low conf.high
#>      setosa     3.721     0.056    3.611     3.831
#>  versicolor     2.738     0.041    2.657     2.818
#>   virginica     2.713     0.053    2.609     2.818
#> 
#> Adjusted for:
#> * Sepal.Length = 5.84


# at this value "Sepal.Length" is held constant
mean(iris$Sepal.Length)
#> [1] 5.843333

# see ggpredict-output, 1st line
coef(m)["(Intercept)"] + mean(iris$Sepal.Length) * coef(m)["Sepal.Length"]
#> (Intercept) 
#>    3.720966

# see ggpredict-output, 2nd line
coef(m)["(Intercept)"] + mean(iris$Sepal.Length) * coef(m)["Sepal.Length"] + coef(m)["Speciesversicolor"]
#> (Intercept) 
#>    2.737578

# see ggpredict-output, 3rd line
coef(m)["(Intercept)"] + mean(iris$Sepal.Length) * coef(m)["Sepal.Length"] + coef(m)["Speciesvirginica"]
#> (Intercept) 
#>    2.713456
```

<sup>Created on 2019-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The difference you see is due to the fact how emmeans (and thus, `ggemmeans()`, handles factors (see [this vignette](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html) for details).

At 2) `backtransform` *only* transforms logged-transform response values back to their non-logged values (i.e. if you have `log(y)` in your model as response, predicted values will be on the scale of the _log_-responses). Else, you can't use `backtransform`, and you will _always_ get predicted values (or marginal effects, or estimated marginal means) on the scale of the *response* variable - for a model with binomial family, you model the probability of an event / success / ..., so you get predicted probabilities.

**Comment by Helene035** [comment]
thanks for the input! About the second point, that makes sense, I did not understood it that way, my apologies. About the first question, I came across the vignette you are mentioning before and indeed if I simplify my model as below (i.e. I remove s(week,k=4,by=butterfly_species)), ggemmeans and ggpredicts give the same predictions.

`parasitism=brm(number_parasitized|trials(number_larvae_collected)~0+ region_butterfly+year, core=4,data=dat.2,iter=10000,warmup=4000,thin=2,family=binomial, control=list(adapt_delta=0.99,max_treedepth=15))`

If this way to formulate my question makes more sense:  how is the average over the non linear effect of week handled?

with the "full model" (including the smooth term), i thought I would get what I obtain with ggemmeans if I would specify exactly the same conditions. I therefore checked for one set of conditions (Sk_au, 2017, and week = 4.74 as ggemmeans adust for that week). 

`ggemmeans(nov_species, terms = "reg_butt[sk_au]", condition = c(year = "2017"),x.as.factor = TRUE)
`

`ggpredict(parasitism, terms=c("week[4.74]","region_butterfly[sk_au]","year[2017]"),robust=FALSE,x.as.factor = TRUE)`

but the predictions do not align between ggemmeans and ggpredict.... maybe I completely misunderstood how this is calculated but I thought that this should be similar.  I also tried to get the predictions for each week and region_butterfly (ggpredict(nov_species, terms=c("week","reg_butt"),robust=FALSE,x.as.factor = TRUE)) and to average the predicted values (again divided by 4) over the week variable but this is not how it is calculated either.

hoping you can clear up my mind!

**Comment by Helene035** [comment]
I have been rethinking about it and refined the interval I used with ggpredict. I asked ggpredict to return a value for each increment of week of 0.1 as follow:

`ggpredict(nov_species, terms=c("week[1, 1.1, 1.2, 1.3, 1.4, ....8.7, 8.8, 8.9, 9","reg_butt"), robust=FALSE, x.as.factor = TRUE)`

then I averaged the value :
`pred %>%
  mutate(perc=predicted/4)%>%
  group_by(group)%>%
  summarise(perc_mean=mean(perc))`

I get closer values that way but still different. I guess it is because ggemmeans predicted values are calculated from the integral over week (I am not sure this is how a mathematician would express that, though), while ggpredict return a value for each point and using multiple points, as I just did, I am in a way building an histogram which gets closer and closer to the function. That is so far my understand of this difference.

**Comment by strengejacke** [comment]
I'm afraid I can't help further without a reproducible example. Maybe it's because the number of trials are held constant at different values?

**Comment by Helene035** [comment]
I shared the model output with you as a reproductible example and below is the script I used to extract data.

just to recall the final goal is to extract mean parasitism, averaged over years and weeks, per butterfly species (there are 4 species : "au", "aio", "va", and "alev") and regions (3 regions "sk", "Kr", "nor")(these two variables are combined in variable called "reg_butt" to avoid issue with missing contrast)

```
rm(list=ls())
library(brms)
library(tidybayes)
library(ggplot2)
```


load brms model:
```
nov_species=readRDS("nov_species_intercept0.rds") 
summary(nov_species)
```
the model is: 
nb_ind_parasite | trials(nb_larvae_in_lab) ~ 0 + reg_butt + year + s(week, k = 4, by = butterfly_species) 

Below I compare what are the values I get with ggemmeans and ggpredict for the year=2017, region "sk", butterfly "au":
`ggemmeans(nov_species, terms = c("reg_butt[sk_au]"), condition = c(year = "2017"), x.as.factor = TRUE)  `

I obtain:

Predicted successes of nb_ind_parasite
 x = reg_butt
 x predicted conf.low conf.high
sk_au      0.33    0.288     0.377

Adjusted for:
week = 4.74
 nb_larvae_in_lab = 4.00

Now using ggpredict, I specify the same conditions, making use of the "adjusted for" output above.
`ggpredict(nov_species, terms=c("reg_butt[sk_au]","week[4.74]","year[2017]","butterfly_species[au]"), robust=FALSE,x.as.factor = TRUE) #give the same as marginal_effect`

I obtain:

Predicted successes of nb_ind_parasite
x = week
x predicted conf.low conf.high facet
4.74      1.08     0.89     1.284  2017

Adjusted for:
 butterfly_species =   au
 nb_larvae_in_lab = 4.00

`1.08/4 #is different from 0.33 obtained with ggemmeans`

As it did not give the same, alternatively I assume that ggemmeans calculated the average rate of parasitism overall the week sampled, as "ggemmeans() compute predicted values for all possible levels or values from a model’s predictor". Therefore, I average the predictions from ggpredict over the range of weeks sampled:
```
predau=ggpredict(nov_species, terms=c("year[2017]","week[1,2,3,4,5,6,7,8,9]","reg_butt[sk_au]","butterfly_species[au]"),robust=FALSE,x.as.factor = TRUE)

predau%>%
  group_by(facet) %>%
  summarize(larvae_parasitized=mean(predicted)/4)
```

I obtain:

A tibble: 3 x 2
facet  larvae_parasitized
<fct>               <dbl>
sk_au               0.373

that is again different from 0.33...

I am obviously not extracting the same things here but I cannot figure out how the smooth term is used and what I am extracting with both function to explain the difference in the values obtained.

**Comment by strengejacke** [comment]
Ok, thanks, I'll look into it! Might take this or next week, as I'm currently busy with lectures.

**Comment by strengejacke** [comment]
The large differences comes from the fact that you have `trials()` as response, and `emmeans()` (and hence, `ggemmeans()`) uses a different value to hold the trials-variable constant (probably 1?), while `ggpredict()` uses the median value.

You can now use the trials-variable in the `condition`-argument to choose a different value instead of median:

```r
ggpredict(nov_species,c("reg_butt", "year"), condition = c(nb_larvae_in_lab = 1))
```

There are still slight differences between ggemmeans and ggpredict, probably due to different underlying computations. `ggpredict()`, however, yields the same results as `brms::marginal_effects()`.

**Comment by Helene035** [comment]
Thanks for the input and your time! I have indeed also noticed the similarity between ggpredict and marginal_effects from brms.

If I may ask a last thing, the reason why I was exploring ggemmeans instead of ggpredict or marginal_effects is that I could compute Average Marginal Effects (rather that Marginal effects at Representative values). However, I was a bit uncertain about how the values are computed with ggemmeans as they are quite different from what I get with ggpredict and marginal_effect in my case. For example, the following code return mean value and confidence intervals for each reg_butt levels, both years taken together:

`ggemmeans(nov_species, terms = c("reg_butt"), x.as.factor = TRUE)`

 How would be the code with ggpredict? I tried different things but it always decompose estimates by year and week. Ideally I would like a summary of the distribution of reg_butt **averaged over week and year**.

**Comment by strengejacke** [comment]
This code:
```r
ggemmeans(nov_species, terms = "reg_butt")
```

is equivalent to this code:
```r
ggpredict(nov_species, terms = "reg_butt")
```

You only get different results when you have factors as predictors, that do not appear in the `terms`-argument, due to different values at which factors are held constant for `emmeans()` and `predict()` (see https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html).

I think there are differences in how _emmeans_ handles brms-models, but that should not be related to the _ggeffects_ package, but rather to _emmeans_.

Try following and see if results are the same:

```r
ggemmeans(nov_species, terms = "reg_butt")
emmeans(nov_species, "reg_butt")
```

I'm also not sure if _emmeans_ really calculates _average marginal effects_ (AME) - I think, AME have a different definition (see, e.g. _margins_ package or here: https://stats.stackexchange.com/tags/marginal-effect/info).
