### ISSUE TITLE
Error with zero-inflated glmmTMB model (ggpredict)

### ISSUE THREAD

**Issue by paternogbc** [strengejacke/ggeffects#117]
Hellow,
**Describe the bug**
I have fitted a mixed zero-inflated model with binomial error structure using the package glmmTMB.
The call from the model is found below:
``` r
zib <- glmmTMB(formula = Ps ~ log10(aridity) + weed_control + seededrateL + 
    log10(tsr) * lifeform2 + (1 | projectid/siteid/treatmentid) + 
    (1 | speciesid), data = dc, family = binomial(link = "logit"), 
    ziformula = ~seededrateL, weights = n, dispformula = ~1)

# model summary
summary(zib)
 Family: binomial  ( logit )
Formula:          Ps ~ log10(aridity) + weed_control + seededrateL + log10(tsr) *  
    lifeform2 + (1 | projectid/siteid/treatmentid) + (1 | speciesid)
Zero inflation:      ~seededrateL
Data: dc
Weights: n

     AIC      BIC   logLik deviance df.resid 
 90020.4  90163.9 -44993.2  89986.4    34168 

Random effects:

Conditional model:
 Groups                         Name        Variance Std.Dev.
 treatmentid:(siteid:projectid) (Intercept) 0.6294   0.7933  
 siteid:projectid               (Intercept) 0.6413   0.8008  
 projectid                      (Intercept) 3.1518   1.7753  
 speciesid                      (Intercept) 4.2196   2.0542  
Number of obs: 34185, groups:  
treatmentid:(siteid:projectid), 1259; siteid:projectid, 151; projectid, 81; speciesid, 555

Conditional model:
                               Estimate Std. Error z value Pr(>|z|)    
(Intercept)                     1.37283    0.64545    2.13 0.033426 *  
log10(aridity)                  1.81698    0.82813    2.19 0.028229 *  
weed_controlyes                 0.41462    0.16133    2.57 0.010172 *  
seededrateL                     0.71811    0.01496   48.01  < 2e-16 ***
log10(tsr)                     -2.67908    0.09636  -27.80  < 2e-16 ***
lifeform2per. forb             -3.70573    0.37697   -9.83  < 2e-16 ***
lifeform2per. grass            -2.55808    0.41014   -6.24 4.46e-10 ***
lifeform2woody                 -1.62246    0.43384   -3.74 0.000184 ***
log10(tsr):lifeform2per. forb   2.03250    0.10458   19.43  < 2e-16 ***
log10(tsr):lifeform2per. grass  1.58765    0.10940   14.51  < 2e-16 ***
log10(tsr):lifeform2woody       1.07520    0.10621   10.12  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Zero-inflation model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept) -1.03023    0.07819 -13.177   <2e-16 ***
seededrateL -0.02604    0.01460  -1.784   0.0745 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

The model seems ok with no convergence problems. But when trying to generate predictions using ggpredict, I got the Error message below:

``` r
pred  <- ggeffects::ggpredict(model = zib, 
                              terms = c("tsr", 
                                        "lifeform2"))

Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  Some variables in newdata needed for predictions contain NAs or NaNs.
           This is currently incompatible with se.fit=TRUE.
In addition: Warning messages:
1: In eval(predvars, data, env) : NaNs produced
2: In eval(predvars, data, env) : NaNs produced
```

Any idea why this is happening? 

**To Reproduce**
Sorrry but the dataset is huge and not public yet (I could send data and code by email it helps).

Many thanks!
**Screenshots**

**Comment by strengejacke** [comment]
> I could send data and code by email it helps

Yes, that would be helpful. It probably related to the random effects structure, but I'm not sure, so something to reproduce the error would be good! You can also send some fake data, or just a smaller portion of the data, ...

**Comment by paternogbc** [comment]
Hey @strengejacke thanks for your reply! The problem was gone once I **scaled** and cenetered my continuous predictors! If you want to explore the issue I can still send you the data, just let me know.  
And thanks for such amazing package! It makes life much easier, especially for complex mixed models!

**Comment by strengejacke** [comment]
Yes, if you don't mind, of be happy if you could share some data to investigate this issue further.

**Comment by strengejacke** [comment]
Can you please install the latest ggeffects-master from GitHub and check if this issue still occurs? You might need to update _insight_ from CRAN first.

**Comment by strengejacke** [comment]
_bump_

**Comment by paternogbc** [comment]
Hey @strengejacke sorry for the delay! I will install the dev version and try again. I give you a feedback here. Many thanks!

**Comment by paternogbc** [comment]
I have repeated the analysis after updating both packages and the error persists.

Fitted model:

```r 
m5.1 <- glmmTMB(Ps ~ log(aridity) + weed_control + log(seededrate_1) + log(tsr) * lifeform2 +
                (1 | projectid / siteid / treatmentid) + (1 | speciesid),
              family = binomial(link = "logit"),
              ziformula = ~ log(seededrate_1),
              weights = n,
              data = dc)

pred  <- ggeffects::ggpredict(model = m5.1, 
                              terms = c("tsr[exp]", 
                                          "lifeform2"))
```

Error message:

```r 
Model has log-transformed predictors. Consider using `terms="aridity [exp]"` to back-transform scale.
Warning messages:
1: In log(aridity) : NaNs produced
2: In log(aridity) : NaNs produced
```
When I check the object `pred`

this is the output:

``` r 
pred
# Predicted probabilities of Ps
# x = tsr
Error in tapply(x$predicted, list(x$group), NULL) : 
  arguments must have same length
```

When I run the same code with `ggeffects` it works:

``` r
pred <- ggeffects::ggeffect(model = m5.1, 
                     terms = c("tsr[exp]", 
                               "lifeform2"))
```

I have solved the problem by scaling the variables but I am posting here so you can investigate and also for me to understand. 

All the best

**Comment by annaskye** [comment]
Hello, I am also having this exact issue. I can send you my code + data if it is helpful.

**Comment by strengejacke** [comment]
Do you have a small, reproducible example, maybe with a smaller subset of your data?

**Comment by benjaminwnelson** [comment]
@strengejacke and @paternogbc, is it common for the predicted values in a zero-inflation model with the ggeffects package to go exponential extremely quickly? If so, would it make sense to limit the y axis in the figure to plausible values?

**Comment by strengejacke** [comment]
It depends on the model. See this example, which looks good to me:

``` r
library(glmmTMB)
library(ggeffects)
m2 <- glmmTMB(count ~ Wtemp * mined + spp + (1|site),
              zi=~spp + mined,
              family=nbinom2, data=Salamanders)

plot(ggpredict(m2, c("Wtemp", "mined")))
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/LOTLCIr.png)

``` r

plot(ggpredict(m2, c("Wtemp", "mined"), type = "random"))
```

![](https://i.imgur.com/Ei5Mkwi.png)

``` r

plot(ggpredict(m2, c("Wtemp", "mined"), type = "zero_inflated"))
```

![](https://i.imgur.com/btmHfPe.png)

``` r

plot(ggpredict(m2, c("Wtemp", "mined"), type = "zi_random"))
```

![](https://i.imgur.com/0dsdhF4.png)

``` r

plot(ggpredict(m2, c("Wtemp", "mined"), type = "zi_prob"))
```

![](https://i.imgur.com/HZc6IAS.png)

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by popovs** [comment]
Because this is the main link that pops up on google when searching this error, I thought I'd share my solution. In my case it was because I was piping the dataframe into the model and using a custom function to mutate a variable before fitting the model. The next session I loaded up my fitted model, and suddenly `ggpredict` failed, throwing the `Some variables in newdata needed for predictions contain NAs or NaNs` error! I realized after much troubleshooting that I had to re-load the custom function back into the environment. After that `ggpredict` (and all associated functions) worked again.

Here is a similar minimal example:

```
library(glmmTMB)
library(ggeffects)

# Define simple scaling fxn
scale.simple <- function(x) {
  out <- (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
  return(out)
}

# Fit our model
data("Salamanders")

mod <- Salamanders |>
  dplyr::mutate(cover = scale.simple(cover)) |>
  glmmTMB(count ~ cover + mined,
          data = _)

summary(mod)
ggeffect(mod, terms = "cover") # Works fine
ggpredict(mod, terms = "cover") # Works fine

# Now remove our scale.simple fxn and try again
rm(scale.simple)
ggeffect(mod, terms = "cover") # Can't compute adjusted predictions, `effects::Effect()` returned an error. Reason: In argument: `cover = scale.simple(cover)`.
ggpredict(mod, terms = "cover") # Still works in this specific example, but with my larger working dataset, I got the following error:

Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  Some variables in newdata needed for predictions contain NAs or NaNs.
           This is currently incompatible with se.fit=TRUE or cov.fit=TRUE.
```
