### ISSUE TITLE
Support of object.class mira from package mice

### ISSUE THREAD

**Issue by elronca** [strengejacke/ggeffects#119]
I tried to use ggemmeans on a [mira object](https://stefvanbuuren.name/fimd/workflow.html) from the [mice package](https://cran.r-project.org/web/packages/mice/index.html).

According to [this documentation](https://strengejacke.github.io/ggeffects/reference/ggpredict.html) of the ggeffects package "all models supported by emmeans should work". However, in my particular case it did not.

`library(ggeffects)`
`library(emmeans)`
`library(mice)`
`library(carData)`
`library(tidyverse)`

Here I am fitting a logistic regression model and use the emmenas package to calculate predicted marginal means.

`fit <- glm(volunteer ~ sex + extraversion, data = Cowles, family = binomial)`
`pmm_cow <- emmeans(fit, "sex")`

Output

`# Predicted values of volunteer`
`# x = sex`

`x      | Predicted |   SE |       95% CI`
`----------------------------------------`
`female |      0.46 | 0.07 | [0.42, 0.49]`
`male   |      0.40 | 0.08 | [0.36, 0.43]`

`Adjusted for:`
`* extraversion = 13.00`

Now I introduce missing values in the Cowles data...

`Cowles_NA <- Cowles`
`set.seed(42)`

`Cowles_NA[,-4] <- do.call(cbind.data.frame,`
                         ` lapply(Cowles_NA[,-4], function(x) {`
                            `n <- nrow(Cowles_NA)`
                            `x[sample(c(1:n),floor(n/10))]<-NA`
                            `x`
                        `  })`
`)`

... impute the missing values and fit the same regression model with the multiply imputed datasets.

`fit_mi <- Cowles_NA %>%`
  `mice(seed = 123, m = 2, print = FALSE) %>%`
  `with(glm(volunteer ~ sex + extraversion, family = binomial))`

Here emmeans still works...

`emmeans(fit_mi, "sex")`

Output

`sex    emmean     SE  df asymp.LCL asymp.UCL`
` female -0.216 0.0744 Inf    -0.362   -0.0706`
`male   -0.467 0.0824 Inf    -0.629   -0.3058`

`Results are given on the logit (not the response) scale. `
`Confidence level used: 0.95 `

...but ggemmeans does not.

`ggemmeans(fit_mi, "sex")`

Output

`Error in f$conditional[[2L]] : subscript out of bounds`
`In addition: Warning messages:`
`1: Could not access model information. `
`2: In faminfo$is_brms_trial <- is_brms_trial(model) :`
`  Coercing LHS to a list`
`3: Could not get model data.` 
`4: Could not access model information. `
`5: In faminfo$is_brms_trial <- is_brms_trial(model) :`
 ` Coercing LHS to a list`

Am I doing something wrong or is it possible that it does not work because the support of the object.class mira was implemented only recently in [CRAN version (1.3.3) of emmeans](https://github.com/rvlenth/emmeans/issues/80).

This is my my first time opening an issue on github, I hope I did it the correct way.
Thanks for the great package!

**Comment by strengejacke** [comment]
Thanks for your bug report. I think the problem is that `mira`-objects are no classical model-objects, and there's some internal preparation before passing the arguments to `emmeans()`, so this is most likely the issue here. I must take a look at it and see if I can handle this somehow.

**Comment by strengejacke** [comment]
I have implemented a `pool_predictions()` function, which can be used as workaround for your issue. The advantage is that you can even pool predictions for models that are not supported by `with.mids()`, which however work with `ggemmeans()` or `ggpredict()`:

``` r
library(ggeffects)
library(emmeans)
library(mice)
#> 
#> Attaching package: 'mice'
#> The following objects are masked from 'package:base':
#> 
#>     cbind, rbind
library(carData)
library(tidyverse)

Cowles_NA <- Cowles
set.seed(42)

Cowles_NA[, -4] <- do.call(cbind.data.frame,
                           lapply(Cowles_NA[, -4], function(x) {
                             n <- nrow(Cowles_NA)
                             x[sample(c(1:n), floor(n / 10))] <- NA
                             x
                           }))


imp <- mice(Cowles_NA, seed = 123, m = 5, print = FALSE)
m <- with(imp, glm(volunteer ~ sex + extraversion, family = binomial))

predictions <- lapply(1:imp$m, function(i) {
  mod <- glm(volunteer ~ sex + extraversion, family = binomial, data = complete(imp, action = i))
  ggemmeans(mod, "sex")
})

pool_predictions(predictions)
#> 
#> # Predicted probabilities of volunteer
#> # x = sex
#> 
#> x      | Predicted |   SE |       95% CI
#> ----------------------------------------
#> female |      0.46 | 0.07 | [0.42, 0.49]
#> male   |      0.39 | 0.08 | [0.35, 0.43]
#> 
#> Adjusted for:
#> * extraversion = 13.00
#> Standard errors are on the link-scale (untransformed).
emmeans(m, "sex", type = "response")
#>  sex     prob     SE  df asymp.LCL asymp.UCL
#>  female 0.448 0.0181 Inf     0.412     0.483
#>  male   0.384 0.0197 Inf     0.346     0.423
#> 
#> Confidence level used: 0.95 
#> Intervals are back-transformed from the logit scale
```

<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
