### ISSUE TITLE
Confidence intervals not included for polr

### ISSUE THREAD

**Issue by stefan-mueller** [strengejacke/ggeffects#12]
First of all, a great package – thanks a lot for your work. I ran an ordinal logistic regression using the `polr` function from the **MASS** package. While the predicted probabilities are returned, the data frame does not include confidence intervals. How can I retrieve them? Thanks for a reply and your help!

```r
library(MASS)
options(contrasts = c("contr.treatment", "contr.poly"))
house_plr <- polr(Sat ~ Infl + Type + Cont, weights = Freq, data = housing)

predict_house <- ggpredict(house_plr, terms = "Type")

head(predict_house)
# # A tibble: 6 x 4
# x predicted response.level  group
# <dbl>     <dbl>          <chr> <fctr>
#   1     1 0.3784493            Low      1
# 2     1 0.2876752         Medium      1
# 3     1 0.3338755           High      1
# 4     2 0.5190445            Low      1
# 5     2 0.2605077         Medium      1
# 6     2 0.2204478           High      1
```

**Comment by strengejacke** [comment]
The `predict()`-function in MASS does not calculate CI. For some objects, like *merMod*, I use [this code](https://github.com/strengejacke/ggeffects/blob/67ab6ab9bbd244d981672769511ad2c892d78ee9/R/predictions.R#L772) - however, this does not seem to work for *polr*-models, at least not always reliable.

If you have any ideas, I'm happy to implement CI for polr as well, but currently I don't know how to do this.

**Comment by stefan-mueller** [comment]
Thanks for the quick response!

I had a look at your [overview](http://dwoll.de/rexrepos/posts/regressionOrdinal.html#using-vglm-from-package-vgam) of ordinal regressions in R. Does `clm()` (**ordinal**), `lrm()` (**rms**) or `vglm()` (**VGAM** package) include an option to calculate CI? As far as I see these models are not implemented in **ggeffects**, so I do not want to cause too much work. If I can help, please let me know. Thanks again for your great work on the package(s)!

**Comment by strengejacke** [comment]
Support for `clm` is implemented - I hope this is sufficient? Will commit tonight, but note that you need to install **sjstats** from GitHub as well in order to use `ggpredict()` with clm-objects.

`lrm`-objects are also implemented, but only for binary outcomes.
