### ISSUE TITLE
Error in exp(mydf$predicted) :    non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by LindaWvanR** [strengejacke/ggeffects#122]
**Describe the bug**
As I told you before, I really like your packages and use them a lot. Since this morning, I get the following error: Error in exp(mydf$predicted) : 
  non-numeric argument to mathematical function

I can no longer use plot_model in sjPlot either, this will provide the same error, so my thought is something is going wrong in ggeffects.

**To Reproduce**
I used the exact same script I used before, no changes. Examples resulting in the error:
mydf <- ggemmeans(Fit1, terms = "term1 [0,10,20,30,60]")
mydf2 <-ggemmeans(Fit1, terms=c("term1 [0,10,20,30,40,50,60]", "term4","term3"))

This one works:
mydf3 <- ggemmeans(Fit1, terms = c("term1 [0,10,20,30,40,50,60]", "term2[exp][0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30]","term3"))

term 2 is a log-transformed continuous variable
term 3 is a categorical variable
term 4 is an ordinal variable with 3 values.

Thanks for your help!

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by LindaWvanR** [comment]
Thank you for your quick response. Sorry, I don't have a reproducible example (apart from the test set and script you already have). The strange thing is that it worked last night and this morning, and now it does not. I already re-installed the packages and dependents but that does not fix the problem. Sorry I cannot be more clear.

**Comment by strengejacke** [comment]
Have you sent the data via email? Can you please send again, or attach the script and test set here to the GitHub discussion?

**Comment by LindaWvanR** [comment]
Hi Daniel,

 

Thanks again for your help. 

Please find attached a very small sample of my data and the script.

 

Errors I see:

 

ggpredict: Error: Confidence intervals could not be computed.

ggemmeans: Error in exp(mydf$predicted) : non-numeric argument to mathematical function 

ggeffect:Can't compute marginal effects, 'effects::Effect()' returned an error.

 

I truly hope I did something stupid 😊 

 

Thanks again!

 

Linda 

 

Van: Daniel <notifications@github.com> 
Verzonden: dinsdag 10 maart 2020 19:17
Aan: strengejacke/ggeffects <ggeffects@noreply.github.com>
CC: LindaWvanR <lindavanrijn@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [strengejacke/ggeffects] Error in exp(mydf$predicted) : non-numeric argument to mathematical function (#122)

 

Do you have a reproducible example?

**Comment by LindaWvanR** [comment]
I sent you a new e-mail. Thanks!

**Comment by strengejacke** [comment]
thanks, should be fixed now.

**Comment by LindaWvanR** [comment]
Thanks, it works, better than ever! Highly appreciated, thank you!
