### ISSUE TITLE
I have some error code with the ggeffects package. Is there some problem with the package? 

### ISSUE THREAD

**Issue by karthy257** [strengejacke/ggeffects#124]
**Describe the bug**
A description of what the bug is. Can You check with the error with the package is? 
[](url)
**To Reproduce**
Steps to reproduce the behaviour. If possible please provide simulated data or a small fraction of your data, in order to have a minimal reproducible example!
<img width="1047" alt="Screen Shot 2020-03-17 at 4 43 48 PM" src="https://user-images.githubusercontent.com/18094581/76899783-9a248f80-686e-11ea-9018-1149d1325c18.png">
`library(sjlabelled)
> data(efc)
> efc$c172code <- as_factor(efc$c172code)
> fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
> fit

Call:
lm(formula = barthtot ~ c12hour + neg_c_7 + c161sex + c172code, 
    data = efc)

Coefficients:
(Intercept)      c12hour      neg_c_7      c161sex    c172code2    c172code3  
    98.9447      -0.2532      -2.2814       0.8750       2.8847       1.2166  

> ggpredict(fit, terms = "c12hour")
Error in .subset2(x, i, exact = exact) : no such index at level 1
Called from: (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, 
    i, exact = exact))(x, ..., exact = exact)
Browse[1]> `
**Screenshots**

**Comment by strengejacke** [comment]
Works as expected:

``` r
library(sjlabelled)
library(ggeffects)
data(efc)
efc$c172code <- as_factor(efc$c172code)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
ggpredict(fit, terms = "c12hour")
#> 
#> # Predicted values of Total score BARTHEL INDEX
#> # x = average number of hours of care per week
#> 
#>   x | Predicted |   SE |         95% CI
#> ---------------------------------------
#>   0 |     73.48 | 2.02 | [69.52, 77.44]
#>  20 |     68.41 | 1.89 | [64.70, 72.13]
#>  45 |     62.08 | 1.82 | [58.51, 65.66]
#>  65 |     57.02 | 1.84 | [53.42, 60.62]
#>  85 |     51.95 | 1.92 | [48.20, 55.71]
#> 105 |     46.89 | 2.05 | [42.87, 50.91]
#> 125 |     41.83 | 2.23 | [37.45, 46.20]
#> 170 |     30.43 | 2.76 | [25.02, 35.84]
#> 
#> Adjusted for:
#> *  neg_c_7 = 11.84
#> *  c161sex =  1.76
#> * c172code =     1
```

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Please check your RStudio-environment: from the screenshot I see that there's a global function names `ggpredict()` defined, possibly conflicting with the package's function. Try to clean your environment and rerun the example, than it should work.

**Comment by karthy257** [comment]
Hi, 
          Thank you so much. I think the problem is with the global environment. Now, the code is working. Thanks again for replying me back. 

Regards, 
Karthy
