### ISSUE TITLE
Request: implement method for gbm objects

### ISSUE THREAD

**Issue by pierozannini** [strengejacke/ggeffects#125]
Hello,

Thanks for this great package!

We're trying to visualize marginal effects of some large scale ecological models and we found out that no methods are implemented for gbm objects. We've read the section "contributing guidelines" of this git but we weren't able to implement a method for gbm ourselves.
Although gbm have a method for predict(), it seems there aren't methods for family() and model.frame().

Below two reprex to check the errors that occur when trying to apply ggpredict() to gbm objects:

library(gbm)
library(dismo)
library(ggeffects)

-Modeling with gbm

N <- 1000
X1 <- runif(N)
X2 <- 2 * runif(N)
X3 <- ordered(sample(letters[1:4], N, replace = TRUE), levels = letters[4:1])
X4 <- factor(sample(letters[1:6], N, replace = TRUE))
X5 <- factor(sample(letters[1:3], N, replace = TRUE))
X6 <- 3 * runif(N)
mu <- c(-1, 0, 1, 2)[as.numeric(X3)]
SNR <- 10
Y <- X1 ^ 1.5 + 2 * (X2 ^ 0.5) + mu
sigma <- sqrt(var(Y) / SNR)
Y <- Y + rnorm(N, 0, sigma)
data <- data.frame(Y, X1, X2, X3, X4, X5, X6)
gbm1 <- gbm(Y ~ ., data = data, distribution = "gaussian", n.trees = 100, shrinkage = 0.1,            
            interaction.depth = 3, bag.fraction = 0.5, train.fraction = 0.5,
            n.minobsinnode = 10, cv.folds = 5, keep.data = TRUE,
            verbose = FALSE, n.cores = 1)
ggeffects::ggpredict(gbm1, terms = "X1", n.trees = 100)

X1` was not found in model terms. Maybe misspelled?
Error in if (!is.na(suppressWarnings(as.numeric(modus)))) as.numeric(modus) else modus :
argument is of length zero

-Modelling with dismo

data(Anguilla_train)
Anguilla_train = Anguilla_train[1:200,]
gbm2 <- gbm.step(data=Anguilla_train, gbm.x = 3:14, gbm.y = 2, family = "bernoulli",
                 tree.complexity = 5, learning.rate = 0.01, bag.fraction = 0.5)
ggeffects::ggpredict(gbm2, terms = "SegTSeas", n.trees=10) 
 

SegTSeas` was not found in model terms. Maybe misspelled?
Error in formula.default(object, env = baseenv()) : invalid formula

Thank you very much for your attention, best

Piero

**Comment by strengejacke** [comment]
Closing as "won't fix". First model works, if you specify the variable names in the model formula:

`gbm1 <- gbm(Y ~X1 + X2 + X3 + X4 + X5 + X6, data = data)`

2nd model has no classic model structure, thus it's not supported.
