### ISSUE TITLE
How to backtransform an standard error

### ISSUE THREAD

**Issue by mountaingoat19** [strengejacke/ggeffects#127]
Hi, 

I really like your packages, but I'm using  a model with log transform response and I'm trying to also transform my standard error. Could you tell me  how to do it ?

![image](https://user-images.githubusercontent.com/62620375/77469211-1d049780-6de5-11ea-9511-93f08a324ba9.png)

Thanks

**Comment by strengejacke** [comment]
At least the confidence intervals are on the same scale as the response. For the standard error, I think there exist methods like delta-approximations, but I'm not sure if and how these differ for the different link-functions.

See, for instance, here:
https://blog.methodsconsultants.com/posts/delta-method-standard-errors/

**Comment by mountaingoat19** [comment]
Hi again,

So you tell me that the confidence intervals on this graph are good ?

![image](https://user-images.githubusercontent.com/62620375/77470081-7d480900-6de6-11ea-8823-8fa9a10a5ae1.png)

Thank you for your support

**Comment by strengejacke** [comment]
Yes. It's similar to models with other link-functions, where the SE are not on the response scale, but the CIs are. See, e.g., this vignette: https://strengejacke.github.io/ggeffects/articles/technical_stata.html
