### ISSUE TITLE
ggpredict with clustered se 

### ISSUE THREAD

**Issue by haoliuhoward** [strengejacke/ggeffects#129]
Hi, 
I find the ggeffects package super useful so thank you!

But I find myself having a difficult time plotting predicted values with conf interval adjusted by "clustered standard errors". It seems like I need to work with vcov.fun, vcov.type, vcov.args, but i can't really work it out, especially on specifying my clustering variable. Could you provide an example of how to do this? I think it'd be super useful for many of us.

Thanks in advance!

**Comment by strengejacke** [comment]
There's a vignette with some examples:
https://strengejacke.github.io/ggeffects/articles/practical_robustestimation.html

Does this help?

**Comment by haoliuhoward** [comment]
Oh. I missed that. Very helpful. Thanks!
