### ISSUE TITLE
clustered standard errors with glm logit

### ISSUE THREAD

**Issue by eborbath** [strengejacke/ggeffects#13]
Hi,

I am wondering if it is possible to use clustered standard errors with ggeffects to plot confidence intervals accordingly. I found [this thread](https://stackoverflow.com/questions/34298373/effects-package-with-multiway-clustered-variance-covariance-matrix) on how to do it with the effects package, but it's somewhat counterintuitive, and I was not sure I really get the syntax right. Therefore I wanted something more straightforward, preferably in a format I can then plot with ggplot (hence this package). I need this from a glm logit.

Thanks!

**Comment by strengejacke** [comment]
I mostly rely on the `predict()` methods and / or methods from the _prediction_ package. I'm not sure in which way I can incoporate user-defined functions for vcov-matrix-computation... Since `ggeffect()` simply wraps `effects::Effect()`, you can use the same approach as described in the thread you're linking to. But I will also try to figure out if I can implement this using `ggpredict()`.

**Comment by strengejacke** [comment]
I just read about an update of the _sandwhich_ package, with more support for clustered covariances. Maybe it's now easier to implement that feature in the package.

`ggeffect()` should already work, as the vcov-function is just passed down to `effects::Effect()`.

**Comment by strengejacke** [comment]
from the latest update to _sandwich_, I may add arguments like `.vcov` and `.vcov.args`, which - if not `NULL` - may use an own estimation of vcov, allowing several types from sandwich.

reminder for implementation
```r
.vcov <- "vcovCL"
.vcov.args <- list(cluster = ~ firm, type = "HC2")
vcov.fun <- get(.vcov, asNamespace("sandwich"))
do.call(vcov.fun, c(list(x = model), .vcov.args))
```

**Comment by strengejacke** [comment]
I'm not 100% sure iof this is what you had in mind, but `ggpredict()` now supports robust se, including clustered se, for various models.
