### ISSUE TITLE
How to add data when the outcome variable has a log transformation in a linear model

### ISSUE THREAD

**Issue by gjabel** [strengejacke/ggeffects#134]
I am trying to find an adequate way to plot the results of ggpredict() when outcome variable has a log transformation in a linear model. The default behaviour with `add.data = TRUE` does not work:

```
library(tidyverse)
library(ggeffects)

m <- lm(log(mpg) ~ vs + wt, data = mtcars)
ggpredict(model = m, terms = c("wt", "vs")) %>%
  plot(add.data = TRUE)
```
![Rplot](https://user-images.githubusercontent.com/2735201/80453209-643cf580-895a-11ea-9243-58b59acff800.png)

I can add the data points manually, to get the plot I want, but I fear it is will become cumbersome with more complicated plots (facets for example).
```
ggpredict(model = m, terms = c("wt", "vs")) %>%
  plot() +
  geom_point(data = mutate(mtcars, group_col = as.factor(vs)), 
             mapping = aes(x = wt, y = mpg, group = group_col))
```
![Rplot01](https://user-images.githubusercontent.com/2735201/80453260-79198900-895a-11ea-9514-38851cd2d3e6.png)

What is the suggested method to handle this situation?

**Comment by strengejacke** [comment]
Thanks, should work now:

``` r
library(ggeffects)
library(tidyverse)

m <- lm(log(mpg) ~ vs + wt, data = mtcars)
ggpredict(model = m, terms = c("wt", "vs"), back.transform = FALSE) %>%
  plot(add.data = TRUE)
#> Model has log-transformed response. Predictions are on log-scale.
```

![](https://i.imgur.com/IxM0bHm.png)

``` r

m <- lm(log(mpg) ~ vs + wt, data = mtcars)
ggpredict(model = m, terms = c("wt", "vs"), back.transform = TRUE) %>%
  plot(add.data = TRUE)
#> Model has log-transformed response. Back-transforming predictions to original response scale. Standard errors are still on the log-scale.
```

![](https://i.imgur.com/uHS16tA.png)

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
