### ISSUE TITLE
Data values grouped in my plot_model

### ISSUE THREAD

**Issue by Phidrod26** [strengejacke/ggeffects#135]
Hi, I'm beginner at R and I was trying to plot a lineal regression and the data values aswell in the same graph. To get you in context, my data base is about bird individuals captured and recaptured where in every capture, we measure biometrics. I want to plot their fittedmass (predicted values of body mass of individuals) depending on the julian day of the year it is (because mass of individuals vary throughout the breeding season that is the time when we captured them)

Here is my R script:
modpatternreduced = glmmTMB(fittedmass ~ JULIAN + I(JULIAN^2) + SX + (1|YEAR) + (1|ANILLA), data = juvecond)
plot_model(modpatternreduced, transform = NULL, terms = "JULIAN[all]", type = ("pred"),    
           title="", ci.lvl = 0.95,
           dot.size =2, line.size = 0.9, 
           axis.title= c( "Day of year","Body mass (g)"),
           show.data=TRUE)+
  theme_bw()+
  theme(
    axis.text.x=element_text(colour="black", size = 16),
    axis.text.y=element_text(colour="black", size = 16),
    axis.title.x=element_text(colour="black", size = 18),
    axis.title.y=element_text(colour="black", size = 18),
    panel.grid.minor = element_blank(),    
    panel.grid.major = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=0.8))

But I get these:
![image](https://user-images.githubusercontent.com/64856903/81091390-77723700-8eff-11ea-9faf-5e0624171970.png)

I don't know why my values are grouped in different lines... I want the data to take its exact place in the graph.

However I have tried to include ''fitted mass'' in the terms of plot model:

plot_model(modpatternreduced, transform = NULL, terms = c("JULIAN[all]", 'fittedmass'), type = ("pred"),    
           title="", ci.lvl = 0.95,
           dot.size =2, line.size = 0.9, 
           axis.title= c( "Day of year","Body mass (g)"),
           show.data=TRUE)+
  theme_bw()+
  theme(
    axis.text.x=element_text(colour="black", size = 16),
    axis.text.y=element_text(colour="black", size = 16),
    axis.title.x=element_text(colour="black", size = 18),
    axis.title.y=element_text(colour="black", size = 18),
    panel.grid.minor = element_blank(),    
    panel.grid.major = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=0.8))

I get this:
![image](https://user-images.githubusercontent.com/64856903/81091813-054e2200-8f00-11ea-895a-d3e70485ecf9.png)

It looks like fitted mass is grouped in five different groups or ''means'' of predicted values of fitted mass. 
(To calculate fitted mass I do this:
modregression=lm(MASS ~ STOMACH, data = juve)
fittedmass= predict.lm(modregression))

**Comment by strengejacke** [comment]
Do you have a reproducible example or some data? Else, it is difficult to track down the bug.

**Comment by Phidrod26** [comment]
Thnak you for your interest. I finally could fix it. It was because of the data: fittedmass was calculated from:
modregression=lm(MASS ~ STOMACH, data = juve)
fittedmass= predict.lm(modregression)

and stomach has categoric values: 0, 1, 2, 3 and 4. So these fitted masses were plotted like this. 

Thank yoy for trying to help!
