### ISSUE TITLE
Conditional effects / plots for probability component in hurdle / zero-inflated models

### ISSUE THREAD

**Issue by pboesu** [strengejacke/ggeffects#136]
**Is it possible to get/plot conditional effects for predictors in the hurdle / zero-inflation part of a two-part model?**

I feel like I am missing something obvious here, but after a fair amount of searching I can't find a solution. Is there a way to get partial effects for predictors in each of the components (i.e. both the count and the probability model)?

```
#e.g. 
library(glmmTMB)
library(ggeffects)

zip <- glmmTMB(count ~ mined, zi = ~ spp,
                 data = Salamanders, family = poisson)

summary(zip) #gives parameter estimates for both count and zero-inflation probability model
plot(ggeffect(zip)) #only returns effects / plots for 'mined' predictor.
```

**Comment by strengejacke** [comment]
No, you haven't missed anything. You can calculate predicted values for the count model only, or for the "complete" model (i.e. counts, conditioned on zero-inflation component). However, I have added a new option `type = "zi.prob"` to predict the zero-inflation probability. This currently only works for `ggpredict()` (and maybe `ggemmeans()`), but I'll see if I get this implemented for ggeffect() and (properly) for ggemmeans() as well.

**Comment by strengejacke** [comment]
Implemented for `ggpredict()` right now, works with GLMMadaptive, glmmTMB and pscl. ggemmeans seems to be a bit trickier, will maybe implement later.

**Comment by strengejacke** [comment]
btw, if you're looking for coefficients (like the results in summary), you may look at [`parameters::model_parameters()`](https://easystats.github.io/parameters/reference/model_parameters.merMod.html) and the related [plotting-functions](https://easystats.github.io/see/articles/parameters.html).

**Comment by pboesu** [comment]
Brilliant! Thanks so much for the speedy response.

I did notice that `sjPlot` provides coefficients for the zi part, but I hadn't yet played with `parameters`. That's an amazing set of packages you put together!
