### ISSUE TITLE
ggpredict with clustered standard errors

### ISSUE THREAD

**Issue by abaimel** [strengejacke/ggeffects#138]
Heya, 

I've been using ggpredict to adjust predictions based on 2-way clustering with the following type of code in version (ggeffects 0.11.0). 

ggpredict(model, c("X", "Z"), 
          vcov.fun="vcovCL", 
          vcov.args=list(cluster = ~ CL1 + CL2))

But just wanted to give a heads up that this no longer seems to work on the most recent update (i.e., confidence intervals cannot be computed, and it doesn't seem to be properly communicating with underlying sandwich/clubSandwich functions). 

Might very well be me, but just wanted to drop a line to see! 

All best and thanks for keeping up such an awesome set of packages.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by abaimel** [comment]
Yup, sure thing. 

If I update ggeffects from CRAN to (0.14.3) I get the following error: 

Error: Confidence intervals could not be computed.
* Reason: "argument is of length zero"
* Source: if (vcov.type %in% c("CR0", "CR1", "CR1p", "CR1S", "CR2", "CR3")) { if (!requireNamespace("clubSandwich", quietly = TRUE)) { stop("Package `clubSandwich` needed for this function. Please install and try again.") } robust_package <- "clubSandwich" } else { if (!requireNamespace("sandwich", quietly = TRUE)) { stop("Package `sandwich` needed for this function. Please install and try again.") } robust_package <- "sandwich" }.
_____________
If I uninstall, then reinstall from version "0.11.0" (and don't accept any updates during the install).; everything works.

R CODE:
install.packages("ggeffects") #for latest version

devtools::install_version("ggeffects", version = "0.11.0", repos = "http://cran.us.r-project.org")

library(ggeffects)

d <- read.csv("repex_effects.csv")

even.m4.plot <- glm(DECISION_EVEN ~ 1 + CONDITION*ROUND.Z + AGE.C + MALE.C, data=d, family="binomial")

ggpredict(even.m4.plot, c("ROUND.Z", "CONDITION"), 
              vcov.fun="vcovCL", 
              vcov.args=list(cluster = ~ ID + SITE))

Data attached too. 
[repex_effects.csv.zip](https://github.com/strengejacke/ggeffects/files/4732841/repex_effects.csv.zip)
