### ISSUE TITLE
ggpredict for brms model

### ISSUE THREAD

**Issue by quantumlinguist** [strengejacke/ggeffects#139]
I'm trying to use ggpredict for the marginal effects of mixed effects logistic regression with the brms package. Per the help page I need to use "ppd=TRUE" so that the estimated error is taken into account but when I do that I get the following error message. "Case" is a binary predictor and the response variable is also binary with levels "dejar" and "hacer" (causative verbs in Spanish). What am I doing wrong? Thanks

<img width="446" alt="Screenshot 2020-06-07 at 00 25 06" src="https://user-images.githubusercontent.com/65797612/83955675-be807e80-a855-11ea-8101-109da1eb9e96.png">

**Comment by strengejacke** [comment]
Can you please install ggeffects from GitHub and check if it works now?

```r
library(devtools)
devtools::install_github("strengejacke/ggeffects")
```

**Comment by quantumlinguist** [comment]
I had the latest version but I still downloaded it again like you said and get the same error.

**Comment by quantumlinguist** [comment]
I have 14.3 version

**Comment by strengejacke** [comment]
From GitHub? The just recent version including [this change](https://github.com/strengejacke/ggeffects/issues/139)?

**Comment by quantumlinguist** [comment]
That link brings me back to this thread, it doesn't take me to a new page.

**Comment by strengejacke** [comment]
Sorry, updated the link. What I meant was if you were updating **from GitHub** recently?

```r
library(devtools)
devtools::install_github("strengejacke/ggeffects")
```

If this doesn't work, I need a reproducible example.

**Comment by quantumlinguist** [comment]
Sorry but that link still brings me here, it doesn't take me to another page. I installed the package today from that github link you posted. I'll create a reproducible example.

**Comment by strengejacke** [comment]
```r
library(devtools)
devtools::install_github("strengejacke/ggeffects")
```

**Comment by quantumlinguist** [comment]
Never mind, I detached the package and uploaded it again with library() instead of clicking on it and that worked. Thanks for your assistance.

**Comment by strengejacke** [comment]
Great, so the issue is resolved?

**Comment by strengejacke** [comment]
(what I was trying to say was, did you update from GitHub *after* I committed a change, which was about 2 hours ago...)

**Comment by quantumlinguist** [comment]
ahh ok, that explains it then! 
There is an issue now though that with ggpredict() the predictions don't make much sense. For both levels of the factor the predictions are 1 and 95% CI take up the whole range. With conditional_effects() from brms the two levels get different predictions Acc =0.80 and Dat =0.60. 

<img width="253" alt="Screenshot 2020-06-07 at 12 07 43" src="https://user-images.githubusercontent.com/65797612/83965940-8f025e00-a8b7-11ea-81e7-4b16dee67c64.png">

**Comment by strengejacke** [comment]
`conditional_effects()` should be the same as using `ppd = FALSE`.

**Comment by quantumlinguist** [comment]
Oh, Ok. Thanks, I'll look into it then.
