### ISSUE TITLE
`... for ggeffect(), further arguments passed down to Effect` not working with xlevels

### ISSUE THREAD

**Issue by iago-pssjd** [strengejacke/ggeffects#140]
In `ggeffect` help one can read after the `...` argument: `for ggeffect(), further arguments passed down to Effect`, but if I try, with the example below, I get:
```
> data(efc)
> fit <- glm(
+  tot_sc_e ~ c12hour + e42dep + e17age + I(e17age^2) + I(e17age^3),
+  data = efc,
+  family = poisson()
+ )
> ggeffect(fit, terms = "e17age", xlevels = 10)
Can't compute marginal effects, 'effects::Effect()' returned an error.

Reason: formal argument "xlevels" matched by multiple actual arguments
You may try 'ggpredict()' or 'ggemmeans()'.

NULL
```

**Comment by strengejacke** [comment]
`xlevels` is actually used inside `ggeffect()`, so you can't pass down that argument. Instead, use `terms` and `condition` to define the values for focal variables and other variables. See [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html) for all the details.

**Comment by iago-pssjd** [comment]
My problem was that I wanted to give the `xlevels` or `quantiles` options of `Effect` to specify the concrete `x` values (of a continuous/numeric variable) at which this function computes the `predicted` values. 
This is because my real data is aproximated in values 0,10, 20, 30,40 etc, but if I print x-axis till value15 the plot is cut in value 10. Look at trajectory 4 in image. I cannot reproduce it with example given above.
![exple](https://user-images.githubusercontent.com/40892925/84064516-02dd5d00-a9c3-11ea-8442-77bead989dd8.png)

**Comment by iago-pssjd** [comment]
Mmm, sorry. No I saw `"hp [50:60 by=.5]"` I tested it and it works. Thank you!
