### ISSUE TITLE
Possible bug with factor level ordering when plotting

### ISSUE THREAD

**Issue by asierrl** [strengejacke/ggeffects#141]
I might have found a bug when plotting a ggeffects object with a factor with level ordering different from alphabetic order. 
I have a glm model with three factors, A, B and C. I want to plot the effect of B*C on y, with rawdata shown. My code is as follows:

```
levels(model$C)
[1]  "Ctrl" "Clip" "MJ"   "MWh"  "MWl" 

eff<- ggeffect(model, terms=c("B", "C"))
plot(eff, rawdata=TRUE, dodge=0.5) + labs( x="Needle production year", y="Phenol concentration", title="", colour="Herbivory\ntreatment")
```

![image](https://user-images.githubusercontent.com/8058052/85889397-aca65180-b7eb-11ea-9141-c99eabbb05a6.png)

You can notice that factor levels show different order for the effect estimates than for the raw data.
I realized that while attr(eff, "rawdata") respects the original ordering of the factor levels, eff$group does not, and uses factor levels in alphabetic order:

```
levels(eff$group)
[1] "Clip" "Ctrl" "MJ"   "MWh"  "MWl" 

raw<- attr(eff, "rawdata")
levels(raw$group)
```

Is it a bug, or should I detail the needed level ordering in any way?
Best regards, 
Asier

**Comment by strengejacke** [comment]
Do you have a reproducible example? Or can you check if this now works? I cannot reproduce the behavior:

``` r
library(ggeffects)
d <- data.frame(
  y = rnorm(100),
  x1 = factor(sample(letters[1:3], size = 100, replace = TRUE), levels = c("b", "a", "c")),
  x2 = factor(sample(LETTERS[6:9], size = 100, replace = TRUE), levels = c("H", "F", "I", "G"))
)

m <- lm(y ~ x1 * x2, data = d)
p <- ggpredict(m, c("x1", "x2"))
plot(p, add.data = TRUE)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/5ABrlS7.png)

<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by asierrl** [comment]
Sorry for the delay, I've been out these days.
Yes, the difference is I was using ggeffect and you use ggpredict. With my dataset I do not have any problem with ggpredict, the issue only occurs with ggeffect (or when using type="eff" in plot_model). I have checked your example and I get the same result as you, but I get this plot when using ggeffect, instead of ggpredict:

![imagen](https://user-images.githubusercontent.com/8058052/87533052-56168f80-c694-11ea-8e9d-097e7498eceb.png)

**Comment by asierrl** [comment]
Hi, Daniel. Sorry for my question, I am not experienced with the github procedures, but I don't understand why you decided to close the issue. Has been any change in the code? I am aware that using "predict" instead of "effect" is a workaround for the issue, but both estimates are different and have different interpretation. Is there a way to get a plot of an "eff" estimate in a custom order?

**Comment by strengejacke** [comment]
The bug has been fixed (I think). Just update ggeffects from CRAN, and it should work.

**Comment by asierrl** [comment]
Ah, ok!! Thanks a lot for your packages, I think they are great!
