### ISSUE TITLE
ggPredict error when data set has row names other default numbers

### ISSUE THREAD

**Issue by avrenli2** [strengejacke/ggeffects#142]
I am using the **ggPredict** function of the **ggiraphExtra** package and it is returning the following error message when I try to plot a simple linear regression model.
**Error in vapply(grouping_cols, single_value, logical(1)):
object 'single_value' not found**

![Capture](https://user-images.githubusercontent.com/62804852/86155949-2c296e80-bad3-11ea-9989-c55f51e80552.PNG)

I figured that the error message shows up if I use a data set with row names different than the default numbers.
**If I do not use row names other than the default numbers, the error message does not show up** and it plots fine.
Is there a way to fix this?

COLORADO <- lm(PRICE ~ BEDROOMS, data=MOUNTAINS)
ggPredict( COLORADO, interactive=T)

**Comment by strengejacke** [comment]
`ggPredict()` is part of the _ggiraph_ package, not _ggeffects_. The function in my package is named `ggpredict()` (all lowercase).
