### ISSUE TITLE
Insufficient values in manual scale when plotting random effects

### ISSUE THREAD

**Issue by bbachilles** [strengejacke/ggeffects#149]
First off, this is a great package. Thanks so much for all your work on it. 

I am trying to use the new feature to predict and plot the random effects. This is shown in the Vignette with the efc data where you only have 8 grouping levels. My data has 48 groupings, and is attached in Stata's .dta format. It is the Junior Schools Project data from Harvey Goldstein's MLM book. The person-period (or long) version of this data is also available in the `faraway()` package as "jsp". The code I'm using is below with the error in **bold:**

```
#libraries, data read-in, and filtering
library(haven)
library(dplyr)
library(lme4)
library(ggeffects)
library(sjlabelled)
JSP <- read_dta("C:/Users/Erik/OneDrive/CASTL/Teaching Courses/MLM Course 2018/Homework Sets/JSP.dta")
JSP_red <- JSP %>% 
  filter(!is.na(MathTest2), !is.na(MathTest0), !is.na(male), !is.na(manual))
```
```
# centering level 1 variables and creating group means
JSP_red <- JSP_red %>% group_by(School) %>% 
  mutate(smn_male = mean(male, na.rm=TRUE), smn_manual = mean(manual, na.rm=TRUE), 
         smn_math0=mean(MathTest0, na.rm=TRUE)) %>% ungroup() %>% 
           mutate(cwc_male = male - smn_male, cwc_manual = manual - smn_manual, cwc_math0 = MathTest0-smn_math0)
```

```
#model fitting and ggpredict for random effect
JSP_red$School <- as_label(JSP_red$School)
m2 <- lmer(MathTest2 ~ cwc_math0 + cwc_manual + cwc_male + smn_male + smn_manual + smn_math0 + (cwc_math0 | School), JSP_red, REML=FALSE)
school_slopes <- ggpredict(m2, terms = c("cwc_math0", "School"), type = "random") 
plot(school_slopes)
```
**Error: Insufficient values in manual scale. 48 needed but only 9 provided.**

Note that if I use the `sample` function, limiting the number of schools to 9, I can get a graph of 9 schools. But if I increase it to 10, it does not work:

```
ggpredict(m2, terms = c("cwc_math0", "School [sample=9]"), type = "random") %>% plot()
```
![image](https://user-images.githubusercontent.com/11998611/89050761-3aacb500-d321-11ea-9670-3669501f78d7.png)

**Comment by strengejacke** [comment]
The default color scales provided by ggeffects' `plot()` method is limited to 9 or 10 color values. If you need to plot more than that, you may need to provide your own color scale.

Here's an example with 18 colors (see https://easystats.github.io/see/articles/seecolorscales.html#overview-of-palette-colors-1): 

``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)
m <- lmer(Reaction ~ Days + (1 + Days | Subject), sleepstudy)
plot(ggpredict(m, c("Days", "Subject"), type = "re")) + see::scale_color_flat()
#> Loading required namespace: ggplot2
#> Scale for 'colour' is already present. Adding another scale for 'colour',
#> which will replace the existing scale.
```

![](https://i.imgur.com/DbTZtYa.png)

Not sure, but maybe the ggplot2-default palette provides enough colours:

``` r
library(ggplot2)
dat <- ggpredict(m, c("Days", "Subject"), type = "re")
ggplot(dat, aes(x = x, y = predicted, colour = group)) + geom_line()
```

![](https://i.imgur.com/Oka28ZP.png)

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
