### ISSUE TITLE
Wrong predictions with scale in model formula

### ISSUE THREAD

**Issue by frousseu** [strengejacke/ggeffects#153]
Hi

When using `scale` in a model formula, `ggpredict` seems to be returning wrong predictions. At first I tought it could be that predictions were not back-transformed to the response scale, but it does not seem to be the problem. Here is an example:

```r
library(ggeffects)
library(sjmisc)
library(ggplot2)
library(patchwork)

set.seed(123)

n<-100
x<-runif(n,0,100)
z<-1+0.02*x
y<-rpois(n,exp(z))
d<-data.frame(y,x,scalex=scale(x))


m1<-glm(y~x,data=d,family="poisson")
g1<-plot(ggpredict(m1)[[1]])+labs(title="x")

m2<-glm(y~scale(x),data=d,family="poisson")
g2<-plot(ggpredict(m2)[[1]])+labs(title="scale(x)")

m3<-glm(y~std(x),data=d,family="poisson")
g3<-plot(ggpredict(m3)[[1]])+labs(title="std(x)")

m4<-glm(y~scalex,data=d,family="poisson")
g4<-plot(ggpredict(m4)[[1]])+labs(title="scalex")

g1+g2+g3+g4
```

![scale_ggeffects](https://user-images.githubusercontent.com/17189048/90073323-fb8a4680-dcc6-11ea-9664-12a468d28ccc.png)

Another thing I noticed while building the example is that even the three correct graphs appear to differ quite a bit. I would expect them to show (almost) exactly the same predictions (unless of a convergence problem). This is with ggeffects 0.15.1.

Thanks!

**Comment by strengejacke** [comment]
It indeed looks strange, but I think, all results are expected / correct.

First, setup.

``` r
library(ggeffects)
library(sjmisc)
library(ggplot2)
library(patchwork)

set.seed(123)
n <- 100
x <- runif(n, 0, 100)
z <- 1 + 0.02 * x
y <- rpois(n, exp(z))
d <- data.frame(y, x, scalex = scale(x))
```

## Slight differences between plot 1 and 3

The underlying data retrieved from the model have the same values for `x`, thus the x-axis is the same. However, `predict()` gives different results.

``` r
m1 <- glm(y ~ x, data = d, family = "poisson")

head(insight::get_data(m1))
#>    y        x
#> 1  5 28.75775
#> 2 11 78.83051
#> 3  6 40.89769
#> 4 20 88.30174
#> 5 18 94.04673
#> 6  1  4.55565

predict(m1, newdata = data.frame(x = seq(0,100, 10)))
#>         1         2         3         4         5         6         7         8 
#> 0.8887906 1.1005658 1.3123411 1.5241163 1.7358916 1.9476668 2.1594421 2.3712173 
#>         9        10        11 
#> 2.5829926 2.7947678 3.0065431

m3 <- glm(y ~ std(x), data = d, family = "poisson")

head(insight::get_data(m3))
#>    y     std(x)        x
#> 1  5 -0.7402982 28.75775
#> 2 11  1.0166700 78.83051
#> 3  6 -0.3143283 40.89769
#> 4 20  1.3489993 88.30174
#> 5 18  1.5505811 94.04673
#> 6  1 -1.5895088  4.55565

predict(m3, newdata = data.frame(x = seq(0,100, 10)))
#>        1        2        3        4        5        6        7        8 
#> 1.034730 1.216707 1.398684 1.580661 1.762638 1.944615 2.126592 2.308569 
#>        9       10       11 
#> 2.490546 2.672523 2.854500
```

## Differences for plot 2

Due to `scale()`, the `x` from the model-frame has different values. Obviously, predicted values are "rescaled"?!?

``` r
m2 <- glm(y ~ scale(x), data = d, family = "poisson")
head(insight::get_data(m2))
#>    y          x
#> 1  5 -0.7402982
#> 2 11  1.0166700
#> 3  6 -0.3143283
#> 4 20  1.3489993
#> 5 18  1.5505811
#> 6  1 -1.5895088

predict(m2, newdata = data.frame(x = seq(-2, 2, .5)))
#>         1         2         3         4         5         6         7         8 
#> 0.8464355 0.8570243 0.8676130 0.8782018 0.8887906 0.8993793 0.9099681 0.9205569 
#>         9 
#> 0.9311456
```

## Plot 4

Though the `x` values (here: `scalex`) are the same as for `scale(x)`, `predict()` treats the predictions differently from Plot 2 / Model 2. That's why the x-axis has values ranged from -2 to 2, but the correct predicted y.

``` r
m4 <- glm(y ~ scalex, data = d, family = "poisson")

head(insight::get_data(m4))
#>    y     scalex
#> 1  5 -0.7402982
#> 2 11  1.0166700
#> 3  6 -0.3143283
#> 4 20  1.3489993
#> 5 18  1.5505811
#> 6  1 -1.5895088

predict(m4, newdata = data.frame(scalex = seq(-2, 2, .5)))
#>         1         2         3         4         5         6         7         8 
#> 0.7375162 1.0392910 1.3410657 1.6428404 1.9446151 2.2463899 2.5481646 2.8499393 
#>         9 
#> 3.1517140
```

<sup>Created on 2020-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by frousseu** [comment]
I get the same predictions for each model except when using `std`. Perhaps with `std` values have to be given differently?

```r
predict(m1,newdata=data.frame(x=100))
#> 1 
#> 3.006543 

predict(m2,newdata=data.frame(x=100))
#> 1 
#> 3.006543

predict(m3,newdata=data.frame(x=c(100,101)))
#> 1        2 
#> 1.517841 2.371389


predict(m4,newdata=data.frame(scalex=(100-mean(x))/sd(x)))
#> 1 
#> 3.006543 
```

With `scale`, I think the x values to predict with have to be given on the original `x` scale. I think this is why the `m2` graph looks completely different. I agree it is a bit confusing that the m2 `model.frame` returns scaled values when `predict` requires values on the original scale. Notice that I supply a vector to predict with m3. Otherwise, predicting with a single value leads to having an `NA` prediction.

```r
predict(m3,newdata=data.frame(x=100))
#> 1 
#> NA 
```

In fact, supplying different values to m3 gives different predictions:

```r
predict(m3,newdata=data.frame(x=c(100,101)))
#> 1        2 
#> 1.517841 2.371389

predict(m3,newdata=data.frame(x=c(100,0)))
#> 1        2 
#> 2.371389 1.517841 

predict(m3,newdata=data.frame(x=c(100,0,100)))
#> 1        2        3 
#> 2.293075 1.247696 2.293075 
```
I don't know if the problem is on the `predict` or the `std` side. I could open an issue on the sjmisc GitHub if you want to. This is with sjmisc 2.8.5 and R 4.0.2.

**Comment by strengejacke** [comment]
This should work now once _insight_ is updated on CRAN:

``` r
library(ggeffects)
library(sjmisc)
#> Learn more about sjmisc with 'browseVignettes("sjmisc")'.
library(ggplot2)
library(patchwork)

set.seed(123)

n<-100
x<-runif(n,0,100)
z<-1+0.02*x
y<-rpois(n,exp(z))
d<-data.frame(y,x,scalex=scale(x))


m1<-glm(y~x,data=d,family="poisson")
g1<-plot(ggpredict(m1)[[1]])+labs(title="x")

m2<-glm(y~scale(x),data=d,family="poisson")
g2<-plot(ggpredict(m2)[[1]])+labs(title="scale(x)")

m3<-glm(y~std(x),data=d,family="poisson")
g3<-plot(ggpredict(m3)[[1]])+labs(title="std(x)")

m4<-glm(y~scalex,data=d,family="poisson")
g4<-plot(ggpredict(m4)[[1]])+labs(title="scalex")

g1+g2+g3+g4
```

![](https://i.imgur.com/HCuvZDI.png)

<sup>Created on 2020-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
