### ISSUE TITLE
plot() seems to ignore addition of ggplot2 theme() and labs() arguments when plotting 4-way interaction

### ISSUE THREAD

**Issue by jmansour99** [strengejacke/ggeffects#157]
Hi there,

first, great package,thank you. This is my first report so apologies if I have just missed something obvious.

I'm using plot() to graph a ggeffects object with 4 terms from a multilevel model produced by lmer(). 

When I try to plot 4 terms, the theme() and labs() info seems to be ignored. If I plot 3 terms, my graph appears as expected. Here is my code.

Here, I get a graph but it uses the default plot() theme and labels:
a = ggpredict(fullMLM,terms=c("clothes","speed","object", "pose"))
plot(a, one.plot = TRUE, limits=c(0,3), colors="bw",show.title = FALSE, use.theme=FALSE) +
  labs(x = "clothing", y = "summed shoot responses")+
  theme(text=element_text(size=12,family = "Times", color="black"),
        panel.border = element_blank(),
        panel.background = element_blank(),
        strip.background =element_rect(fill="white", color="black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        legend.background = element_rect(fill="white"),
        legend.key = element_rect(fill="white"))

I do get an error message that reads: "Error in plot(a, one.plot = TRUE, limits = c(0, 3), colors = "bw", show.title = FALSE,  : 
  non-numeric argument to binary operator" which appears to be associated with the labs() function (doesn't appear if I remove that line). If I run the plot() function with the theme() function added, R prints the word "NULL".

This graph appears properly (regardless of which combination of 3 terms I use):
b = ggpredict(fullMLM,terms=c("clothes","speed","object"))
plot(b, one.plot = TRUE, limits=c(0,3), colors="bw",show.title = FALSE, use.theme=FALSE) +
  labs(x = "clothing", y = "summed shoot responses")+
  theme(text=element_text(size=12,family = "Times", color="black"),
        panel.border = element_blank(),
        panel.background = element_blank(),
        strip.background =element_rect(fill="white", color="black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        legend.background = element_rect(fill="white"),
        legend.key = element_rect(fill="white"))

Hope that is useful.

**Comment by strengejacke** [comment]
For 4-way-interactions, multiple ggplots are arranged using [`see::plots()`](https://easystats.github.io/see/reference/plots.html). Thus, the return object is no longer a ggplot2-object.

I suggest using `ggplot2::theme_set()` and set `use.theme = FALSE` to use a different theme:

``` r
library(ggeffects)
data(efc)
fit <- lm(neg_c_7 ~ c12hour * barthtot * c161sex * c172code, data = efc)

pr <- ggpredict(fit, c("c12hour", "barthtot", "c161sex", "c172code"))

ggplot2::theme_set(see::theme_abyss())
plot(pr, use.theme = FALSE)
```

![](https://i.imgur.com/BfgEUlf.png)

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jmansour99** [comment]
Worked like a charm. Thank you and sorry for not realizing that this is how the code worked.
