### ISSUE TITLE
Error in sprintf(ngettext(sum(wch), "level %s not allowed for %s", "levels %s not allowed for %s"),  :    too few arguments

### ISSUE THREAD

**Issue by clarefmccann** [strengejacke/ggeffects#158]
pred.tsc <- ggpredict(lin_SC_Transition_covariates, terms = c("Transition"))

Error in sprintf(ngettext(sum(wch), "level %s not allowed for %s", "levels %s not allowed for %s"),  :    too few arguments

This is the code I am using. I thought it could have been returning this error because "Transition" is a factor, but I played around and added some of the continuous covariates from my model and it gave me the same error.

**Comment by strengejacke** [comment]
Do you have a reproducible example? I can't remember having this code: `sprintf(ngettext(sum(wch)` in my package(s).

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_
