### ISSUE TITLE
gamlss + RE : confidence intervals could not be computed

### ISSUE THREAD

**Issue by meriops** [strengejacke/ggeffects#159]
Hi,
With `gamlss` (v 5.2.0) and `ggeffects` (v 0.16.0), when I include a random effect in the formula for the location parameter, I get :

Error: Confidence intervals could not be computed.
* Reason: "non-conformable arguments"
* Source: mm %*% vcm

I am not sure if it's not coming from `gamlss`, because I also get the message : 
New way of prediction in random()  (starting from GAMLSS version 5.0-6)

Here's a dumb example:

```
repmod <- gamlss(Sepal.Length ~ Sepal.Width,
                    sigma.formula = ~ Sepal.Width,
                    data = iris
)

ggpredict(repmod, terms = "Sepal.Width") %>%
  plot()
# CI ok

repmod_re <- gamlss(Sepal.Length ~ Sepal.Width + random(Species),
                    sigma.formula = ~ Sepal.Width,
                    data = iris
)

ggpredict(repmod_re, terms = "Sepal.Width") %>%
  plot()
# no CI

```

**Comment by Ari04T** [comment]
I also can't get the confidence intervals when using a gamlss formula that has a smoother term in it. I don't think this is exactly the same problem but I just thought it was a good idea to add it here.

For example
```
gamlss_mod <- gamlss(x ~ y + ba( ~ s(z, by = w)))

ggpredict(gamlss_mod, terms = c("z", "y")) 

new prediction 
Error: Confidence intervals could not be computed.
* Reason: "object 'z' not found"
* Source: eval(predvars, data, env)
```
