### ISSUE TITLE
error ggeffects with nlme

### ISSUE THREAD

**Issue by Kristinagush** [strengejacke/ggeffects#161]
I ran a multilevel time-series regression model (lme) with nlme package and tried to build a predicted probabilities plot with plot_model. Before the last packages' updates, everything was working. Now I receive the following error from ggeffects:

Error: Must extract column with a single valid subscript.
x Subscript `terms[2]` can't be `NA`.

> rlang::last_error()
<error/vctrs_error_subscript_type>
Must extract column with a single valid subscript.
x Subscript `terms[2]` can't be `NA`.
Backtrace:
  1. sjPlot::plot_model(model10, type = "pred", terms = "rai")
  2. sjPlot:::plot_type_eff(...)
  3. ggeffects::ggpredict(...)
  4. ggeffects:::ggpredict_helper(...)
  5. ggeffects:::.post_processing_predictions(...)
  6. ggeffects:::.add_labels_to_groupvariable(...)
  9. tibble:::`[[.tbl_df`(original_model_frame, terms[2])
 10. tibble:::tbl_subset2(x, j = i, j_arg = substitute(i))
 11. tibble:::vectbl_as_col_location2(j, length(x), names(x), j_arg = j_arg)
 14. vctrs::vec_as_location2(j, n, names)
 15. vctrs:::result_get(...)

Could you, please, help?

**Comment by strengejacke** [comment]
Do you have a reproducible example?

It looks like your input is a tibble, and no data frame. If so, can you try to pass a valid data frame to your model (as `data` argument)?

**Comment by Kristinagush** [comment]
This is my model:

model1 <- lme(dvreg ~ time + rai + elec + reg_quota + gdp,
              random = ~ 1 | country/region,
              method = "REML",
              data = data2,
              correlation = corLin(form = ~ time | country/region),
              control = lmeControl(msMaxIter = 5000),
              na.action = na.omit)

**Comment by strengejacke** [comment]
Do you have some sample data, so I can actually reproduce that model on my computer?

**Comment by Kristinagush** [comment]
I deleted the missing values from the variables included in the model (to avoid NAs in the indices) and re-run the model, but the error does not go away. 

[exampledata.xlsx](https://github.com/strengejacke/ggeffects/files/5312002/exampledata.xlsx)

**Comment by strengejacke** [comment]
Ok, as I said, please use a data frame as input, not a tibble. So just use `data2 <- as.data.frame(data2)`.

**Comment by strengejacke** [comment]
``` r
library(readxl)
library(nlme)
d <- read_excel("C:/Users/mail/Downloads/exampledata.xlsx")
d <- as.data.frame(d)

model1 <- lme(dvreg ~ time + rai + elec + reg_quota + gdp,
              random = ~ 1 | country/region,
              method = "REML",
              data = d,
              correlation = corLin(form = ~ time | country/region),
              control = lmeControl(msMaxIter = 5000),
              na.action = na.omit)


sjPlot::plot_model(model1, type = "pred", terms = "rai")
```

![](https://i.imgur.com/DwI1pgo.png)

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Kristinagush** [comment]
Oh, I did not have this issue before... Thank you very much for help! It works.

**Comment by alaindanet** [comment]
I just have the same bug. Hopefully, I found this issue to fix the bug. Thank you!

As people might use more and more tibble rather than data.frame, it might be worth to add an error message or a warning with an automatic conversion of tibble in data.frame?

**Comment by strengejacke** [comment]
Yes, that might be a solution. On the other hand, if an object is pretending to be a data frame, but does not behave like a data frame, it's rather an issue for the tibble-maintainers.

**Comment by Burren84** [comment]
The problem with the tibble seems to be new.
Until a few months ago I could run the following code with a tibble without any problems. Currently I have to convert the tibble to a dataframe first before the model. What could be the reason for this?
plot_model(mod_8.1, type = "eff", terms= "Alter_LB")

**Comment by strengejacke** [comment]
does `insight::get_data(mod_8.1)` work for you?

**Comment by Burren84** [comment]
Yes, it work for me.
Today I had a new problem with a linear model.
Unfortunately, also the conversion from tibble to a dataframe brings nothing. What could be the reason for this?

Data4 <- as.data.frame(Data4)
mod_1 <-lm(pH ~ Roetungsscore_ICK, data=Data4)
summary(mod_1)
library(sjPlot)
tab_model(mod_1)

Error in `purrr::map2()`:
i In index: 1.
i With name: mod_1.
Caused by error:
! Sorry, `model_parameters()` failed with the following error (possible class `lm` not supported):

  'is_empty_object' is not an exported object from 'namespace:datawizard'
Run `rlang::last_trace()` to see where the error occurred.

**Comment by strengejacke** [comment]
This seems like your packages are not up to date. Try following:

```r
install.packages("easystats")
```

and once you've installed that package, you can easily update all easystats-packages running following code:

```r
easystats::install_latest()
```

Furthermore, make sure you're running the latest version of the _ggeffects_ package, and run:

```r
ggeffects::install_latest()
```

Then it should work, also for tibbles.

**Comment by Burren84** [comment]
ok, now everything is going well. Thank you!
