### ISSUE TITLE
Error with AR1 structure and ggpredict w/ example

### ISSUE THREAD

**Issue by adcorso** [strengejacke/ggeffects#162]
I've been using `ggeffects` for several years now, it is one of my favorite packages. Recently, I began having an issue with the `ggpredict` function for a model generated with `glmmTMB`. It was working fine, but an error and warning message appeared after the last update. I've isolated the AR1 structure as the cause of the error, but I'm not sure why it just started happening. 
```

library(glmmTMB)
library(ggeffects)
data("Salamanders")

### need to make a group with 1's for the AR1 structure in glmmTMB
Salamanders["group"] = 1
Salamanders$group = as.factor(Salamanders$group)

exp_mod = glmmTMB(count ~ Wtemp + (1|DOP) + ar1(site+ 0| group) , ziformula = ~1, 
                data = Salamanders, family = nbinom2)

exp_pred = ggpredict(exp_mod, terms = "Wtemp[n=50"], 
                     type = "re.zi", ci.lvl = 0.95) 
```

```
Error in sqrt(revar) : non-numeric argument to mathematical function
In addition: Warning messages:
1: Can't compute random effect variances. Some variance components equal zero.
  Solution: Respecify random structure! 
2: Random slopes not present as fixed effects. This artificially inflates the conditional random effect variances.
  Solution: Respecify fixed structure! 
```

**Comment by adcorso** [comment]
I apologize I'm not incredibly familiar with github, it appears that you addressed this issue in a new version, 0.16.1, but I don't see how/where to download the new version. Thanks!

**Comment by strengejacke** [comment]
You can download it from GitHub as follows:

```r
library(devtools)
devtools::install_github("strengejacke/ggeffects")
```

**Comment by adcorso** [comment]
I have used `install_github` successfully before for other packages, but unfortunately I'm getting this error for `ggeffects`. Do you have any suggestions? 

```
installing *source* package 'ggeffects' ...
   ** using staged installation
   ** R
   ** data
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
     namespace 'insight' 0.9.6 is being loaded, but >= 0.9.6.1 is required
   Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
   Execution halted
   ERROR: lazy loading failed for package 'ggeffects'
```

I updated `insight `but I'm still getting the error. I double checked my `Rtools` path and I'm using version 2.3.2 of `devtools`.

**Comment by strengejacke** [comment]
I did some more revisions to _ggeffects_ meanwhile, so you need to update _insight_ from Github first:

```r
library(devtools)
devtools::install_github("easystats/insight")
devtools::install_github("strengejacke/ggeffects")
```
