### ISSUE TITLE
Add linetype option to color plots

### ISSUE THREAD

**Issue by Maschette** [strengejacke/ggeffects#163]
Hi when using ggeffects the only option which has linetype is the "bw" option and as a result you cannot use scale_linetype_*() on the plots if you want a combination of color and line type.

**Comment by strengejacke** [comment]
You need to add all scales manually, e.g.

``` r
library(ggeffects)
library(ggplot2)

data(mtcars)
m <- lm(mpg ~ gear + as.factor(cyl) + wt, data = mtcars)

# continuous x-axis
dat <- ggpredict(m, terms = c("gear", "wt"))

plot(dat, colors = "bw") +
  scale_linetype_manual(values = c(4, 7, 9)) +
  scale_color_manual(values = c("green", "blue", "yellow")) +
  scale_fill_manual(values = c("green", "blue", "yellow"))
#> Scale for 'colour' is already present. Adding another scale for 'colour',
#> which will replace the existing scale.
```

![](https://i.imgur.com/LVajewt.png)

<sup>Created on 2020-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Does this help?
