### ISSUE TITLE
error with GLS regression

### ISSUE THREAD

**Issue by athammad** [strengejacke/ggeffects#164]
Hi, 

first of all, thank you for this amazing package!

I am trying to calculate AME using the function `ggpredict` on a `gls` model like the following 
`library(nlme)`
`mymodel<-gls(Y~as.factor(Z)+X1+X2+as.numeric(Date),data = na.omit(Mydata), correlation=corAR1()))`
`ggpredict(mymodel,'Z')`

but I keep getting the following error

```
 Error: Confidence intervals could not be computed.
* Reason: "`Date` does not have enough factor levels. Try to remove `[]`."
* Source: .safe_se_from_vcov(model, prediction_data, value_adjustment, terms, model_class, type, vcov.fun, vcov.type, vcov.args, condition, interval) 
```

any help would be greatly appreciated

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
_bump_
