### ISSUE TITLE
ggpredict and rlmerMod

### ISSUE THREAD

**Issue by Ann1Ko** [strengejacke/ggeffects#166]
Hi Daniel,

first of all, thank you so much for all these wonderful packages you created! 

I'm using robustlmm and lme4 and tried to pass it on to ggeffects() to compute marginal effects for a three-way interaction (continous x continous x binary variable). So far it worked out, but the function returned only for half of the marginal effects standard error, conf.low  and conf.high. 

Additionally applying the plot function on this ggeffect object shows this error message (probably because only half standard.errors were computed?): 
Fehler in `[.data.frame`(x, !sapply(x, function(i) length(i) == 0 || is.null(i) ||  : 
  undefined columns selected

First, I thought this is only an issue for the rlmerMod object but the message also showed up for the lme4-Object

Here my code:
diagnosis/gender = factors
time/resources/age = numeric variables

rlmerMod <- rlmer(y ~ time * resources * diagnosis + age + gender + (1|subject_id), 
                         data = df,
                         na.action = "na.omit")

rlmerMod_pred <- ggpredict(rlmerMod, terms = c("time[T0, T1, T2, T3]", "resources[-SD, mean, +SD]", "diagnosis"))

plot() and plot_model() does not work out, the ggplot2 code from your vignette works, but without confidence interval around the slopes.

Do you have any suggestions for this issue?

**Comment by strengejacke** [comment]
Do you have a reproducible example? You don't need to specify mean/sd for continuous variables as 2nd term, because this is the default. Else, use `meansd`:

``` r
library(lme4)
#> Warning: Paket 'lme4' wurde unter R Version 4.0.3 erstellt
#> Lade nötiges Paket: Matrix
library(robustlmm)
library(ggeffects)
data("sleepstudy")
set.seed(1234)
sleepstudy$cont <- rnorm(nrow(sleepstudy))

m <- rlmer(
  Reaction ~ Days * cont + (Days | Subject),
  data = sleepstudy,
  rho.sigma.e = psi2propII(smoothPsi, k = 2.28),
  rho.sigma.b = chgDefaults(smoothPsi, k = 5.11, s = 10)
)

ggpredict(m, c("Days", "cont [meansd]"))
#> 
#> # Predicted values of Reaction
#> # x = Days
#> 
#> # cont = -1.04
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    255.65 |  8.20 | [239.58, 271.71]
#> 1 |    265.56 |  7.93 | [250.01, 281.11]
#> 3 |    285.39 |  8.58 | [268.58, 302.20]
#> 5 |    305.22 | 10.47 | [284.70, 325.73]
#> 6 |    315.13 | 11.71 | [292.19, 338.07]
#> 9 |    344.87 | 16.05 | [313.41, 376.33]
#> 
#> # cont = -0.06
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    252.22 |  7.41 | [237.70, 266.74]
#> 1 |    262.97 |  7.37 | [248.53, 277.41]
#> 3 |    284.47 |  8.34 | [268.13, 300.81]
#> 5 |    305.98 | 10.32 | [285.75, 326.20]
#> 6 |    316.73 | 11.54 | [294.12, 339.34]
#> 9 |    348.98 | 15.67 | [318.26, 379.70]
#> 
#> # cont = 0.92
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    248.79 |  8.10 | [232.91, 264.68]
#> 1 |    260.38 |  7.88 | [244.94, 275.82]
#> 3 |    283.56 |  8.57 | [266.77, 300.35]
#> 5 |    306.73 | 10.47 | [286.22, 327.25]
#> 6 |    318.32 | 11.70 | [295.39, 341.26]
#> 9 |    353.09 | 16.01 | [321.70, 384.47]
#> 
#> Adjusted for:
#> * Subject = 0 (population-level)

ggpredict(m, c("Days", "cont"))
#> 
#> # Predicted values of Reaction
#> # x = Days
#> 
#> # cont = -1.04
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    255.65 |  8.20 | [239.58, 271.71]
#> 1 |    265.56 |  7.93 | [250.01, 281.11]
#> 3 |    285.39 |  8.58 | [268.58, 302.20]
#> 5 |    305.22 | 10.47 | [284.70, 325.73]
#> 6 |    315.13 | 11.71 | [292.19, 338.07]
#> 9 |    344.87 | 16.05 | [313.41, 376.33]
#> 
#> # cont = -0.06
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    252.22 |  7.41 | [237.70, 266.74]
#> 1 |    262.97 |  7.37 | [248.53, 277.41]
#> 3 |    284.47 |  8.34 | [268.13, 300.81]
#> 5 |    305.98 | 10.32 | [285.75, 326.20]
#> 6 |    316.73 | 11.54 | [294.12, 339.34]
#> 9 |    348.98 | 15.67 | [318.26, 379.70]
#> 
#> # cont = 0.92
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    248.79 |  8.10 | [232.91, 264.68]
#> 1 |    260.38 |  7.88 | [244.94, 275.82]
#> 3 |    283.56 |  8.57 | [266.77, 300.35]
#> 5 |    306.73 | 10.47 | [286.22, 327.25]
#> 6 |    318.32 | 11.70 | [295.39, 341.26]
#> 9 |    353.09 | 16.01 | [321.70, 384.47]
#> 
#> Adjusted for:
#> * Subject = 0 (population-level)

plot(ggpredict(m, c("Days", "cont [meansd]")))
```

![](https://i.imgur.com/cCBv0u0.png)

<sup>Created on 2020-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See also [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html).

**Comment by Ann1Ko** [comment]
Actually as I tried to reproduce my issue - it suddenly worked ("Vorführeffekt" ;-)). The only thing I did do different, was to use a normal R script and not a R - Markdown script. But thanks anyway!

**Comment by strengejacke** [comment]
Ok, thanks! Glad that it works for you now! :-)
