### ISSUE TITLE
GLMMadaptive: Time as random slope throws error in ggpredict

### ISSUE THREAD

**Issue by mamscience** [strengejacke/ggeffects#167]
Hi! 

First of all, great package, it saves a lot of time.

I was fitting a longitudinal GLMM model for a binomial outcome using GLMMadaptive. During the model building, it works well when the random factor is defined for intercept only (e.g. random =~1|patientid). However, when I add the time as random factor, to correct for correlation of multiple measurements within-subject, ggpredict doesn't want it.
Random factor in that case is defined as: random =~time | patientid.
The error ggpredict throws when given this model: 

_**Error in f$conditional[[2L]] : subscript out of bounds.**_

This error disappears when time is removed from random factor. 

I have updated both ggeffects and insight package to the latest version. What could be the issue here?
Looking forward to aid with this issue.

Kind regards
Michel

Reprex:

```R
set.seed(194842)
n <- 100 # number of subjects
K <- 5 # number of measurements per subject
t_max <- 5 # maximum follow-up time
reprex <- data.frame(id = rep(seq_len(n), each = K),
                 time = c(0,1,2,3,4),
                 studygroup = rep(gl(3, n/3, labels = c("1", "2","3")), each = K), binaryoutcome =
                     rbinom(20, 1, 0.5))

reprexmodel <- GLMMadaptive::mixed_model(
    fixed = as.factor(binaryoutcome) ~ time * as.factor(studygroup), 
    random =~  time | id, data = reprex, 
    family = binomial(link="logit"))

ggpredict(reprexmodel,c("time [all]","studygroup")) %>% plot()
```

**Comment by strengejacke** [comment]
Thanks, should be fixed in https://github.com/easystats/insight/commit/0183d79ddb659022b1352185b2c6f57656495633. So please update package _insight_ from GitHub, and it should work.

``` r
library(magrittr)
library(ggeffects)
library(GLMMadaptive)
#> Warning: Paket 'GLMMadaptive' wurde unter R Version 4.0.3 erstellt
set.seed(194842)
n <- 100 # number of subjects
K <- 5 # number of measurements per subject
t_max <- 5 # maximum follow-up time
reprex <- data.frame(
  id = rep(seq_len(n), each = K),
  time = c(0, 1, 2, 3, 4),
  studygroup = rep(gl(3, n / 3, labels = c("1", "2", "3")), each = K),
  binaryoutcome =
    rbinom(20, 1, 0.5)
)

reprexmodel <- GLMMadaptive::mixed_model(
  fixed = as.factor(binaryoutcome) ~ time * as.factor(studygroup),
  random =  ~  time | id,
  data = reprex,
  family = binomial(link = "logit")
)

ggpredict(reprexmodel, c("time [all]", "studygroup")) %>% plot()
#> Warning: Results for MixMod-objects may vary depending on which value
#> the response is conditioned on. Make sure to choose a sensible value for
#> 'binaryoutcome' using the 'condition'-argument.
#> Lade nötigen Namensraum: ggplot2
```

![](https://i.imgur.com/DIedxGy.png)

<sup>Created on 2020-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
