### ISSUE TITLE
ggpredict faceting free scales

### ISSUE THREAD

**Issue by antoine4ucsd** [strengejacke/ggeffects#173]
Hello 
I am trying to plot the results for the following
```r
fit <- lmer(cluster_weigth ~ time *gender + (1|id) +clusterID, data = mydata )
pr <- ggpredict(fit,terms = c("time", "gender","clusterID"))
```
and

```r
plot(pr)
```
and I would like to facet the plot by cluster. It does work but I can't find a way to make the x and y axis scales 'free' like in ggplot. see the current results attached. is it also possible to to annotate the plot with cluster-specific p values?
otherwise, can we use ggplot to plot the pr object? 

thank you!
[_ggpredict.2020-11-10.png.gz](https://github.com/strengejacke/ggeffects/files/5518693/_ggpredict.2020-11-10.png.gz)

**Comment by antoine4ucsd** [comment]
using ggplot

ggplot(pr, aes(x = x, y = predicted, colour = group)) +
        geom_line() +
        facet_wrap(~facet,scales="free")

the facetting is not working as I would expect (same plot for all)
![Rplot](https://user-images.githubusercontent.com/18502631/98703457-5b2cd800-2330-11eb-9c69-0ebba89b0d13.png)

**Comment by strengejacke** [comment]
Have you tried

```r
plot(pr) + facet_wrap(~facet,scales="free")
```

?

**Comment by strengejacke** [comment]
> the facetting is not working as I would expect (same plot for all)

Well, actually it's not completely the same plot, the values on the y-axis vary. Since you have no random slope, the interaction (i.e. the lines for male/female) should indeed have the same slopes in each facet, just the intercept (i.e. y axis) varies. So your code and the plot are both ok.

**Comment by antoine4ucsd** [comment]
I did and actually I think the problem is upfront in my lmer equation. if I apply the following:

> fit <- lmer(cluster_weigth ~ time *gender + (1|pid) +clusterID, data = mydata)
pr <- ggpredict(fit,terms = c("time", "gender","clusterID"))
>
then all facets (by cluster) are the same : it does not seem to be applied cluster by cluster...
so I end up looping through all cluster one by one and then arrangeGrob to make a unique plot.. This is not elegant but I don't get why the cluster term is not taken into account.
![image](https://user-images.githubusercontent.com/18502631/98850848-3b69e280-240a-11eb-8710-bb113c3bad0b.png)


as opposed to 

![_4_Menopause_senescence_ggpredict selected 2020-11-10](https://user-images.githubusercontent.com/18502631/98851100-9f8ca680-240a-11eb-8e4b-c9e6c900123f.png)

**Comment by strengejacke** [comment]
Do you have a small reproducible example? I need to know more details about the structure of the data frame returned by `ggpredict()`.

**Comment by antoine4ucsd** [comment]
see attached with only a few samples
thank you!
[_test.txt](https://github.com/strengejacke/ggeffects/files/5526218/_test.txt)

**Comment by strengejacke** [comment]
Here's an example:

``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)
d <- readr::read_csv("d:/Downloads/_test.txt", col_types = "dffdd")
m <- lmer(cluster_weigth ~ time *gender + (1|id) +clusterID, data = d)
#> Warning: Some predictor variables are on very different scales: consider
#> rescaling
#> boundary (singular) fit: see ?isSingular
pr <- ggpredict(m,terms = c("time", "gender","clusterID"))
plot(pr)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/YvUyVQ3.png)

``` r
plot(pr) + ggplot2::facet_wrap(~facet, scales = "free")
```

![](https://i.imgur.com/T1QJdSF.png)

<sup>Created on 2020-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Everything is indeed working as intended. I'm not sure what kind of plot you'd like to have? Since you have a two-way interaction and the factor `clusterID`, each "interaction-plot" is moved along the y-axis by the coefficient of `clusterID`. I don't see any problem here.

**Comment by antoine4ucsd** [comment]
My goal was to have cluster -specifc lmer, which I got by looping through all clusters one by one.
I end up doing this
        myoutput=subset(mydata,clusterID==mycluster)
        fit_mycluster <- lmer(cluster_weigth ~ time_num *gender + (1|id) , data = myoutput )
        pr_mycluster <- ggpredict(fit_mycluster,terms = c("time_num", "gender"))

Thank you for your help and responsiveness.

--
a

**Comment by strengejacke** [comment]
Your approach looks more like you want to model a 3-way interaction between time, gender and clusterID.

**Comment by strengejacke** [comment]
``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)
d <- readr::read_csv("d:/Downloads/_test.txt", col_types = "dffdd")
m <- lmer(cluster_weigth ~ time * gender * clusterID + (1 | id), data = d)
#> Warning: Some predictor variables are on very different scales: consider
#> rescaling
#> boundary (singular) fit: see ?isSingular
pr <- ggpredict(m, terms = c("time", "gender", "clusterID"))
plot(pr)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/7OyqmJz.png)

``` r
plot(pr) + ggplot2::facet_wrap(~facet, scales = "free")
```

![](https://i.imgur.com/8VvgFOv.png)

<sup>Created on 2020-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by antoine4ucsd** [comment]
Just a quick message because I realize I did not thank you for your last post. We made some progress and I think we are getting closer .. thank you again for being so responsive.
