### ISSUE TITLE
no smoothing ggpredict

### ISSUE THREAD

**Issue by quantumlinguist** [strengejacke/ggeffects#179]
I used ggpredict to compute predicted probabilities of a Bayesian mixed effects model but the graph doesn't look smooth. I used the [all] option as I have in the past but it doesn't look smooth. Is there any way I can fix this? 

p0_acc=as.data.frame(ggpredict(model_rf_scores2_ACC, terms="TransitivityNew[all]",
                               condition=c(Group="0", Causative="dejar",
                                           Tense="0",  Person="0",
                                           NumberSubj="0")))

![plot_zoom_png](https://user-images.githubusercontent.com/65797612/100456914-61a5a880-30c1-11eb-8e22-1bd1749cdc9a.png)

**Comment by strengejacke** [comment]
Do you have a reproducible example? Which package did you use to fit the model?

**Comment by quantumlinguist** [comment]
brms package
it is quite a long process to get to the plot, how do I submit a reproducible example?

**Comment by strengejacke** [comment]
Have you tried `plot(conditional_effects(<yourmodel>))`? What kind of plot does it create?

**Comment by quantumlinguist** [comment]
They are smooth. The other plot I create by changing the reference levels but this is what I get with the same reference level. 
![plot1](https://user-images.githubusercontent.com/65797612/100473377-7d6b7780-30de-11eb-817d-11c240e1f391.png)
![plot2](https://user-images.githubusercontent.com/65797612/100473379-7fcdd180-30de-11eb-875e-b88a12a9fdde.png)

**Comment by strengejacke** [comment]
Can you try `terms="TransitivityNew [0:1 by=.01]"` or something similar (i.e. maybe `by=0.001`)? Maybe this helps? If `[all]` doesn't help, it could be that the range of values in the original data has too few values for a smooth plot, so setting an own range might help..

**Comment by quantumlinguist** [comment]
it worked! I used 0.001. Thank you so much!

![image](https://user-images.githubusercontent.com/65797612/100485060-009cc580-30ff-11eb-85fe-61df41896c05.png)

**Comment by strengejacke** [comment]
Good to hear!
