### ISSUE TITLE
[Question] Points shape for color = "bw" and add.data = TRUE

### ISSUE THREAD

**Issue by andreaphsz** [strengejacke/ggeffects#180]
Is there a way to change points shape for black/white color/theme?

**Comment by strengejacke** [comment]
Do you mean something like in the examples at the end of this page: https://strengejacke.github.io/ggeffects/articles/introduction_plotcustomize.html

?

**Comment by andreaphsz** [comment]
Hmm, I mean for the data points, when ```add.data = TRUE```.
