### ISSUE TITLE
Marginal Effects for Random Effects Models using lme

### ISSUE THREAD

**Issue by michaelsorich** [strengejacke/ggeffects#181]
I am trying to use your great library with the lme function (nlme). When I try to run the vignette examples (Introduction: Marginal Effects for Random Effects Models) I run into some problems for the section 'Marginal effects for each level of random effects'. Specifically, it seems that the predictions for all individuals are identical. If I am doing something wrong I would appreciate a pointer in the right direction. Example below.

<pre>
#can reproduce vignette output using lme4
library(ggeffects)
library(lme4)
data(sleepstudy)
m <- lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)
print(m)
me <- ggpredict(m, terms = c("Days", "Subject [sample=7]"), type = "random")
print(me)
plot(me)
# predict(m, newdata = data.frame(Days = c(0,2,5,9), Subject = 351))
# predict(m, newdata = data.frame(Days = c(0,2,5,9), Subject = 369))

#lme version
library(nlme)
m <- lme(Reaction ~ Days, random = ~ Days | Subject, data = sleepstudy)
print(m)
me <- ggpredict(m, terms = c("Days", "Subject [sample=7]"), type = "random")
print(me)  #predictions the same for all subjects - output of the last two included below
...
# Subject = 352

x | Predicted |           95% CI
--------------------------------
0 |    251.41 | [197.85, 304.96]
2 |    272.34 |                 
5 |    303.74 |                 
9 |    345.61 |                 

# Subject = 370

x | Predicted |           95% CI
--------------------------------
0 |    251.41 | [197.01, 305.80]
2 |    272.34 |                 
5 |    303.74 |                 
9 |    345.61 |                 

plot(me)  #Error in `[.data.frame`(x, !sapply(x, function(i) length(i) == 0 || is.null(i) ||  : undefined columns selected
predict(m, newdata = data.frame(Days = c(0,2,5,9), Subject = 351))  #these predictions don't match those returned by ggpredict?
predict(m, newdata = data.frame(Days = c(0,2,5,9), Subject = 369))
</pre>

**Comment by strengejacke** [comment]
Thanks, should work now with the latest commit.
