### ISSUE TITLE
Add Johnson-Neyman plots

### ISSUE THREAD

**Issue by mattansb** [strengejacke/ggeffects#182]
I'm currently using `interactions::johnson_neyman()`, but it would be nice to switch to `ggeffects` ^_^

This can be done with `emmeans::emtrends()`:

``` r
states <- as.data.frame(state.x77)


states$HSGrad <- states$`HS Grad`

fit <- lm(Income ~ HSGrad * Murder * Illiteracy, 
          data = states)

library(emmeans)
library(ggeffects)
library(ggplot2)
library(magrittr)

at <- list(Illiteracy = ggeffects::pretty_range(states$Illiteracy))
emt <- emtrends(fit, ~ Illiteracy, var = "Murder",
                at = at)
#> NOTE: Results may be misleading due to involvement in interactions

emt %>% 
  summary() %>% 
  ggplot(aes(Illiteracy, Murder.trend, ymin = lower.CL, ymax = upper.CL)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_ribbon(alpha = 0.2, color = NA) +
  geom_line()
```

![](https://i.imgur.com/9nCUzPP.png)

``` r



at <- list(Illiteracy = pretty_range(states$Illiteracy),
           HSGrad = values_at(states$HSGrad))
emt <- emtrends(fit, ~ Illiteracy + HSGrad, var = "Murder",
                at = at)

emt %>% 
  summary() %>% 
  ggplot(aes(Illiteracy, Murder.trend, ymin = lower.CL, ymax = upper.CL, 
             color = ordered(HSGrad), fill = ordered(HSGrad))) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_ribbon(alpha = 0.2, color = NA) +
  geom_line()
```

![](https://i.imgur.com/yNarcuw.png)

<sup>Created on 2020-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mccarthy-m-g** [comment]
Seconding this 😄 

If you do add this it would be nice to include a "marginal rug" that displays the frequency of observed values of the moderator across its displayed range. You can use the `ggplot2::geom_rug()` function for this, and allow users to show/hide it using the `add.data` argument used in other plot methods in the ggeffects package.

See Figure 5 in [Improving Present Practices in the Visual Display of Interactions](https://doi.org/10.1177%2F2515245917746792) for an example.

**Comment by strengejacke** [comment]
Now that _ggeffects_ has the `hypothesis_test()` function, this can be easily replicated. Based on this, I could implement a function that directly produces the plots you asked for:

``` r
library(ggeffects)
library(ggplot2)

states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`

fit <- lm(Income ~ HSGrad * Murder * Illiteracy,
  data = states
)

fit |>
  ggpredict(c("Murder", "Illiteracy [0.5:2.8 by=0.1]")) |> 
  hypothesis_test(test = NULL) |> 
  ggplot(aes(Illiteracy, Slope, ymin = conf.low, ymax = conf.high)) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_ribbon(alpha = 0.2, color = NA) +
    geom_line()
```

![](https://i.imgur.com/XK2xrDD.png)

``` r

fit |>
  ggpredict(c("Murder", "HSGrad", "Illiteracy [0.5:2.8 by=0.1]")) |>
  hypothesis_test(test = NULL) |> 
  ggplot(aes(Illiteracy, Slope,
    ymin = conf.low, ymax = conf.high,
    color = ordered(HSGrad), fill = ordered(HSGrad)
  )) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_ribbon(alpha = 0.2, color = NA) +
    geom_line()
```

![](https://i.imgur.com/kAElCK1.png)

<sup>Created on 2023-08-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
What is the meaning of these plots?

**Comment by mccarthy-m-g** [comment]
The “The marginal-effects approach” section in the paper linked in my previous comment has a nice description of the meaning of the plots.

**Comment by strengejacke** [comment]
Thanks! If I understand right, it mainly boils down to:

> Marginal-effects plots are ultimately used to understand the range of a moderator for which a focal predictor is statistically significantly associated with an outcome.

**Comment by strengejacke** [comment]
Current state of implementation:

``` r
library(ggeffects)
library(ggplot2)
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`

fit <- lm(Income ~ HSGrad * Murder * Illiteracy,
  data = states
)

ggpredict(fit, c("Murder", "Illiteracy [0.5:2.8 by=0.1]")) |> 
  johnson_neyman()
```

![](https://i.imgur.com/jUGXRzL.png)

``` r

ggpredict(fit, c("Murder", "HSGrad", "Illiteracy [0.5:2.8 by=0.1]")) |>
  johnson_neyman()
```

![](https://i.imgur.com/EjzrY9S.png)

``` r

ggpredict(fit, c("HSGrad", "Murder", "Illiteracy [0.5:2.8 by=0.1]")) |>
  johnson_neyman()
```

![](https://i.imgur.com/8dWoenY.png)

<sup>Created on 2023-09-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(ggeffects)
library(ggplot2)
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`

fit <- lm(Income ~ HSGrad * Murder * Illiteracy,
  data = states
)

ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman()
```

![](https://i.imgur.com/4mOhDTb.png)

``` r

ggpredict(fit, c("HSGrad", "Murder", "Illiteracy")) |>
  johnson_neyman()
```

![](https://i.imgur.com/IEIvq5j.png)

``` r

ggpredict(fit, c("Murder", "HSGrad", "Illiteracy")) |>
  johnson_neyman()
```

![](https://i.imgur.com/gN7Ehfe.png)

``` r

ggpredict(fit, c("HSGrad", "Illiteracy", "Murder")) |>
  johnson_neyman()
```

![](https://i.imgur.com/fqBp9Cm.png)

<sup>Created on 2023-09-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Ok, @mattansb, I need your help. This works fine now:

``` r
library(ggeffects)
data(efc)

efc$c172code <- as.factor(efc$c172code)
m <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)

ggpredict(m, c("c12hour", "barthtot")) |>
  johnson_neyman()
```

![](https://i.imgur.com/qdF2EF0.png)

``` r
ggeffect(m, c("c12hour", "barthtot")) |>
  johnson_neyman(vcov = sandwich::vcovHC)
```

![](https://i.imgur.com/PEsw0Um.png)

But how do I correctly place the vertical lines when I have facets?

``` r
ggpredict(m, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman()
```

![](https://i.imgur.com/q2hiFsb.png)

The code is in #371

**Comment by strengejacke** [comment]
Wait, I need to fix some issues first.

**Comment by strengejacke** [comment]
ggplot doesn't like me anymore. If someone knows how to fix overlapping ribbons in the second plot, please let me know.

``` r
library(ggeffects)
data(efc)

efc$c172code <- as.factor(efc$c172code)
m <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)

ggeffect(m, c("c12hour", "barthtot")) |>
  johnson_neyman()
#> For values of `barthtot` lower than 47, the slope of `c12hour` is p < 0.05.

ggeffect(m, c("c12hour", "barthtot")) |>
  johnson_neyman() |>
  plot()
```

![](https://i.imgur.com/aNikXkl.png)

``` r

states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy,
  data = states
)
ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman()
#> For values of `Illiteracy` that are inside the interval [0.79, 2.67], the slope of `Murder` is p < 0.05.

out <- ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman() |> 
  plot()
```

![](https://i.imgur.com/hY5MUVb.png)

**Comment by strengejacke** [comment]
Here's a working example from stackoverflow:
``` r
library(zoo)
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
library(data.table)
library(ggplot2)
df <- tibble::tribble(
  ~year, ~lower, ~upper, ~type,
  2001, 150, 222, "A",
  2002, 53, 64, "A",
  2003, 31, 64, "B",
  2004, 10, 18, "B",
  2005, 30, 49, "B",
  2006, 37, 43, "A",
  2007, 54, 77, "B",
  2008, 58, 89, "A",
  2009, 50, 111, "A",
  2010, 40, 81, "A",
  2011, 49, 63, "A"
)
df$group <- rleid(df$type)
df_plot <- head(do.call(rbind, by(df, df$group, rbind, NA)), -1)
df_plot[, c("group", "type")] <- lapply(df_plot[, c("group", "type")], na.locf)
df_plot[] <- lapply(df_plot, na.locf, fromLast = TRUE)

ggplot(df_plot, aes(x = year, ymin = lower, ymax = upper, fill = type, group = group)) +
  geom_ribbon()
```

![](https://i.imgur.com/aXPG3Xb.png)

<sup>Created on 2023-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(ggeffects)
data(efc)

efc$c172code <- as.factor(efc$c172code)
m <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)

ggeffect(m, c("c12hour", "barthtot")) |>
  johnson_neyman()
#> For values of `barthtot` lower than 47, the slope of `c12hour` is p < 0.05.

ggeffect(m, c("c12hour", "barthtot")) |>
  johnson_neyman() |>
  plot()
```

![](https://i.imgur.com/KS58zBH.png)

``` r

states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy,
  data = states
)
ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman()
#> For values of `Illiteracy` that are inside the interval [0.79, 2.67], the slope of `Murder` is p < 0.05.

out <- ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman() |> 
  plot()
```

![](https://i.imgur.com/C5OJ0Zd.png)

``` r


# not working yet
ggeffect(m, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman()
#> For values of `barthtot` that are inside the interval [47.00, 33.50], the slope of `c12hour` is p < 0.05.

ggeffect(m, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman() |>
  plot()
```

![](https://i.imgur.com/KBCUXLp.png)

<sup>Created on 2023-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@mattansb But how do I correctly place the vertical lines when I have facets?

**Comment by strengejacke** [comment]
``` r
library(ggeffects)
data(efc)

efc$c172code <- as.factor(efc$c172code)
m <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)

ggpredict(m, c("c12hour", "barthtot")) |>
  johnson_neyman()
#> For values of `barthtot` lower than 47, the slope of `c12hour` is p < 0.05.

ggpredict(m, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman()
#> # Level `c172code = 1`
#> For values of `barthtot` lower than 47, the slope of `c12hour` is p < 0.05. 
#> 
#> # Level `c172code = 2`
#> For values of `barthtot` lower than 33.50, the slope of `c12hour` is p < 0.05. 
#> 
#> # Level `c172code = 3`
#> There are no significant slopes of `barthtot` for any value of `c12hour`.

ggpredict(m, c("c12hour", "barthtot")) |>
  johnson_neyman() |>
  plot()
#> Warning: Removed 1 rows containing missing values (`geom_vline()`).
```

![](https://i.imgur.com/RcFzMoU.png)

``` r

ggpredict(m, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman() |>
  plot()
#> Warning: Removed 1 rows containing missing values (`geom_vline()`).
#> Warning: Removed 3 rows containing missing values (`geom_vline()`).
```

![](https://i.imgur.com/huew1gr.png)

``` r

states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad * Murder * Illiteracy,
  data = states
)

ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman()
#> There are no significant slopes of `Illiteracy` for any value of `Murder`.

ggpredict(fit, c("Murder", "HSGrad", "Illiteracy")) |>
  johnson_neyman()
#> # Level `HSGrad = 45.03`
#> There are no significant slopes of `Illiteracy` for any value of `Murder`. 
#> 
#> # Level `HSGrad = 53.11`
#> There are no significant slopes of `Illiteracy` for any value of `Murder`. 
#> 
#> # Level `HSGrad = 61.18`
#> For values of `Illiteracy` lower than 1.02, the slope of `Murder` is p < 0.05.

ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman() |> 
  plot()
#> Warning: Removed 1 rows containing missing values (`geom_vline()`).
#> Warning: Removed 1 rows containing missing values (`geom_vline()`).
```

![](https://i.imgur.com/Rw3VrYM.png)

``` r

ggpredict(fit, c("Murder", "HSGrad", "Illiteracy")) |>
  johnson_neyman() |>
  plot()
#> Warning: Removed 2 rows containing missing values (`geom_vline()`).
#> Warning: Removed 3 rows containing missing values (`geom_vline()`).
```

![](https://i.imgur.com/QCOqV6d.png)

``` r

fit <- lm(Income ~ HSGrad + Murder * Illiteracy,
  data = states
)
ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman()
#> For values of `Illiteracy` that are outside the interval [0.79, 2.67], the slope of `Murder` is p < 0.05.

ggpredict(fit, c("Murder", "Illiteracy")) |>
  johnson_neyman() |>
  plot()
```

![](https://i.imgur.com/9tDJRGe.png)

<sup>Created on 2023-09-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
Continuing the conversation from twitter (and echoing @vincentarelbundock's concerns): the vertical dashed lines in Figure 5 of @mccarthy-m-g's example (McCabe et al 2018) are less pretty than the different colour ribbons, but also less in-your-face. Also, here's what McCabe et al say about the plot:

> The plot thus indicates that X is negatively associated with Y when Z is very low (at least 2.30 SD below the mean) and positively associated with Y when Z is −0.60 SD below the mean or greater.

This is one whisper away from saying that X is **not** associated with Y when Z is between -2.3SD and -0.6SD, which would be accepting the null hypothesis ...

I completely understand that there's a fine line between giving people what they want, what they might need, and what you think is good for them ... (and what they might implement badly anyway if you don't provide it)


McCabe, Connor J., Dale S. Kim, and Kevin M. King. 2018. “Improving Present Practices in the Visual Display of Interactions.” Advances in Methods and Practices in Psychological Science 1 (2): 147–65. https://doi.org/10.1177/2515245917746792.

**Comment by strengejacke** [comment]
> This is one whisper away from saying that X is not associated with Y when Z is between -2.3SD and -0.6SD, which would be accepting the null hypothesis ...

What I usually say instead of non-significant, and what could be added here is to say that, e.g., "within -2.3 to -0.6, we found no clear association" or "within -2.3 to -0.6, associations were inconsistent" (no clear direction).

**Comment by mattansb** [comment]
Thanks @bbolker - this is very intresting!
@strengejacke Maybe you can add a data rug like in McCabe et al. 2018 Fig 5?
And maybe add the coloring of sig/non-sig as a (non-default) option?

![image](https://github.com/strengejacke/ggeffects/assets/35330040/91b7d19a-434a-4396-8935-406c60394742)

**Comment by strengejacke** [comment]
And a small plot series, maybe we could decide on the default for `show_association`?

``` r
library(ggeffects)

data(efc)
efc$c172code <- as.factor(efc$c172code)
m1 <- lm(c12hour ~ neg_c_7 * barthtot, data = efc)
m3 <- lm(neg_c_7 ~ c12hour * barthtot, data = efc)
m4 <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)

states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
m2 <- lm(Income ~ HSGrad + Murder * Illiteracy,
  data = states
)

ggpredict(m1, c("neg_c_7", "barthtot")) |>
  johnson_neyman() |>
  plot(show_association = TRUE)
#> The association between `neg_c_7` and `c12hour` is positive for values
#>   of `barthtot` that range from 46.50 to 49.50. Outside of this interval,
#>   there were no clear associations.
```

![](https://i.imgur.com/KaxqfY7.png)

``` r

ggpredict(m1, c("neg_c_7", "barthtot")) |>
  johnson_neyman() |>
  plot(show_association = FALSE)
#> The association between `neg_c_7` and `c12hour` is positive for values
#>   of `barthtot` that range from 46.50 to 49.50. Outside of this interval,
#>   there were no clear associations.
```

![](https://i.imgur.com/jTl7Jji.png)

``` r

ggpredict(m2, c("Murder", "Illiteracy")) |>
  johnson_neyman() |>
  plot(show_association = FALSE)
#> The association between `Murder` and `Income` is positive for values of
#>   `Illiteracy` lower than 0.79 and negative for values higher than 2.67.
#>   Inside the interval of [0.79, 2.67], there were no clear associations.
```

![](https://i.imgur.com/lTMv1ag.png)

``` r

ggpredict(m2, c("Murder", "Illiteracy")) |>
  johnson_neyman() |>
  plot(show_association = TRUE)
#> The association between `Murder` and `Income` is positive for values of
#>   `Illiteracy` lower than 0.79 and negative for values higher than 2.67.
#>   Inside the interval of [0.79, 2.67], there were no clear associations.
```

![](https://i.imgur.com/ROPIBuK.png)

``` r

ggpredict(m3, c("c12hour", "barthtot")) |>
  johnson_neyman() |>
  plot(show_association = TRUE)
#> The association between `c12hour` and `neg_c_7` is positive for values
#>   of `barthtot` higher than 48. There were no clear associations for
#>   values of `barthtot` lower than 48.
```

![](https://i.imgur.com/BJ6v2rP.png)

``` r

ggpredict(m3, c("c12hour", "barthtot")) |>
  johnson_neyman() |>
  plot(show_association = FALSE)
#> The association between `c12hour` and `neg_c_7` is positive for values
#>   of `barthtot` higher than 48. There were no clear associations for
#>   values of `barthtot` lower than 48.
```

![](https://i.imgur.com/1YO7qPj.png)

``` r

ggpredict(m4, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman() |> 
  plot(show_association = TRUE)
#> # Level `c172code = 1`
#> The association between `c12hour` and `neg_c_7` is negative for values
#>   of `barthtot` lower than 47. There were no clear associations for values
#>   of `barthtot` higher than 47. 
#> 
#> # Level `c172code = 2`
#> The association between `c12hour` and `neg_c_7` is positive for values
#>   of `barthtot` higher than 33.50. There were no clear associations for
#>   values of `barthtot` lower than 33.50. 
#> 
#> # Level `c172code = 3`
#> There are no clear negative or positive associations between `c12hour`
#>   and `neg_c_7` for any value of `barthtot`.
```

![](https://i.imgur.com/Bo87HMY.png)

``` r

ggpredict(m4, c("c12hour", "c172code", "barthtot")) |>
  johnson_neyman() |>
  plot(show_association = FALSE)
#> # Level `c172code = 1`
#> The association between `c12hour` and `neg_c_7` is negative for values
#>   of `barthtot` lower than 47. There were no clear associations for values
#>   of `barthtot` higher than 47. 
#> 
#> # Level `c172code = 2`
#> The association between `c12hour` and `neg_c_7` is positive for values
#>   of `barthtot` higher than 33.50. There were no clear associations for
#>   values of `barthtot` lower than 33.50. 
#> 
#> # Level `c172code = 3`
#> There are no clear negative or positive associations between `c12hour`
#>   and `neg_c_7` for any value of `barthtot`.
```

![](https://i.imgur.com/KBmFXud.png)

<sup>Created on 2023-09-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@mattansb the rug is not really informative...

**Comment by mattansb** [comment]
The rug would need to use the rad data, not the grid.

I think `show_association = FALSE` as default would ease Ben's mind (:

**Comment by strengejacke** [comment]
> The rug would need to use the rad data, not the grid.

It should already use the raw data

**Comment by mccarthy-m-g** [comment]
The rug is informative in both cases, since it tells us which regions of the plot are supported by the raw data. For equidistant points it tells us all regions are supported; whereas for skewed points it tells us which regions have and don’t have support. We only know this if we plot the raw data.

Quote from the McCabe et al article (emphasis added):

> Although marginal-effects plots aid in detecting and communicating interaction effects that may otherwise be missed, **they fail to indicate whether or how much data are represented within the graphed regions and therefore may suggest effects that are not (or are very minimally) supported by the data.** For instance, in the data from Example 1, very few data points are observed when Z is lower than 2.30 SD below the mean (see [Fig. 5](https://journals.sagepub.com/doi/10.1177/2515245917746792#fig5-2515245917746792)). Only two observations (1.3% of the sample) fall within the region of significance where the slope is negative, and there is no indication of the extent to which these observations are consistent with the estimated model. Indeed, in an often-cited article describing the use of the J-N technique in psychology, the authors provided a figure in which one of the tails of the displayed moderator Z had few to no observations, but this was noted only in the text ([Preacher et al., 2006](https://journals.sagepub.com/doi/10.1177/2515245917746792#bibr26-2515245917746792)). **Restricting the range of the horizontal axis to the observed range of Z and including a marginal rug of the observed data, as in [Figure 5](https://journals.sagepub.com/doi/10.1177/2515245917746792#fig5-2515245917746792), helps address this concern (e.g., [Berry et al., 2012](https://journals.sagepub.com/doi/10.1177/2515245917746792#bibr5-2515245917746792)).** The inclusion of the observed data might lead us to infer that they do not support the conclusion that X has a significant effect on Y when Z is 2.30 SD below the mean or lower.

**Comment by strengejacke** [comment]
> I think `show_association = FALSE` as default would ease Ben's mind (:

I think I leave the default `TRUE` for now, as this makes the plot more intuitive. I understand that it's bad practice to support users in "dichotomizing" between sig/non-sig, but on the other hand, good plots should be clear with no additional explanation. And the purpose of the dashed lines *is* clearer when the colors and legend are included.
