### ISSUE TITLE
package or namespace load failed for 'ggeffects'

### ISSUE THREAD

**Issue by PMartin924** [strengejacke/ggeffects#19]
Hi, 

I installed ggeffects_0.3.1 today, from 'https://cran.rstudio.com/bin/windows/contrib/3.3/ggeffects_0.3.1.zip' . The installation appears to work, yet when I attempt to load the package, this happens:

**> library(ggeffects)
Error : object ‘modify_if’ is not exported by 'namespace:purrr'
Error: package or namespace load failed for ‘ggeffects’**

Am I doing something wrong?

Thanks!

**Comment by strengejacke** [comment]
It seems like you need to update your packages, especially package _purrr_.

**Comment by PMartin924** [comment]
That did the trick. Thank you!
