### ISSUE TITLE
plotting average marginal effects for interactions in lmer models

### ISSUE THREAD

**Issue by steelduines** [strengejacke/ggeffects#190]
I am running the following country fixed effects model, and I would like to plot the _average_ marginal effect of parental occupation (par_occ, a five-level factor variable) on years of education across different birth cohorts (cohort). Right now I am only able to get the ggeffects package to plot the marginal effect at each level of par_occ, but I want to instead plot the average marginal effect of par_occ. This would be similar to "margins, dydx(par_occ) over(cohort)" in Stata. Is this possible? Thank you very much.

mod1 <- lmer(edu)yrs ~ par_occ:cohort + gndr + z_agea + sround + ( 1 | cntry), data = edu_occ2)

**Comment by strengejacke** [comment]
No, this is not yet possible (and this issue is related to https://github.com/strengejacke/ggeffects/issues/107, thus I will close this to avoid duplicates). However, the _margins_ package should do what you want, also for lme4 models, I think.
