### ISSUE TITLE
full.data = TRUE argument led down the river?

### ISSUE THREAD

**Issue by Jan-Helb** [strengejacke/ggeffects#193]
In the recent version(s) the full.data = TRUE parameter in the ggpredict/ggeffect/ggemmeans function is not working any longer. It it is now ignored with any error.

I liked this parameter as it produces rawdata, predicted values etc. in a proper data.frame (not having these somewhere in the attributes without rawdata, residuals..).

Thank you
Best,
Jan

**Comment by strengejacke** [comment]
Yes, it was removed ~1.5 years ago, simply because the averaged predictions were not accurately calculated. So I thought it would be better to remove it. The proper implementation would be #107
