### ISSUE TITLE
Issue with ggpredict when using gamlss with family BE() and random effect

### ISSUE THREAD

**Issue by atrolle** [strengejacke/ggeffects#194]
Hi,

I fitted a gamlss model with family BE(), specifying a random effect as follows:

```
model <- gamlss(formula = TAUX_TB ~ CORPUS * SECTEUR + random(CD_RNE),
                                               sigma.formula = ~ 1,  data = data, family = BE(),
                                                    weights = data$NOMBRE_CANDIDATS)
```

I installed the latest versions of `insight` and `ggeffects` from GitHub.
Then I tried to use `ggpredict`:
`ggpredict(model, terms = c("CORPUS","SECTEUR"), type = "re")`

But I've got an error message:
`Error in f$conditional[[2L]] : subscript out of bounds`
As well as a warning message:
`Could not get model data. `

I don't understand this issue; any idea?

Thank you in advance,
Arnaud.

**Comment by strengejacke** [comment]
Thank you! That's probably related to the insight-package, I'll look at it. Do you have a reproducible example?

**Comment by atrolle** [comment]
Here is an example, but I can't reproduce my data set entirely:

```
library(ggplot2)
library(insight)
library(ggeffects)
library(gamlss)

data <- read.csv(file = "Données.csv", header=T, sep = ";",dec = ",", na.strings = "", stringsAsFactors = TRUE)
```
`head(data, 10)`
>      CD_RNE CORPUS TAUX_TB SECTEUR NOMBRE_CANDIDATS
> 1  0590101P      0   0.198  Public                4
> 2  0132210G      0   0.158  Public               11
> 3  0070001N      0   0.148  Public                4
> 4  0951399E      0   0.052  Public                4
> 5  0930125F      0   0.075  Public                2
> 6  0383242T      0   0.422  Public               20
> 7  0741476C      0   0.136  Public               17
> 8  0310039Z      0   0.161  Public               22
> 9  0760052U      0   0.142  Public               21
> 10 0640057P      0   0.129  Public               41
> 

```
model <- gamlss(formula = TAUX_TB ~ CORPUS * SECTEUR + random(CD_RNE),
                                               sigma.formula = ~ 1,
                                               data = data, family = BE(),
                                                    weights = data$NOMBRE_CANDIDATS)
eff <- ggpredict(model, terms = c("CORPUS","SECTEUR"), type = "re")
```
> Error in f$conditional[[2L]] : indice hors limites
> De plus : Warning message:
> Could not get model data. 
> 

`sessionInfo()`
> R version 4.0.1 (2020-06-06)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8.1 x64 (build 9600)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
> [5] LC_TIME=French_France.1252  
> 

Is it sufficient?

Arnaud.

**Comment by strengejacke** [comment]
Could you wrap the `head(...)` in `dput()`, so I can direcly copy the code to create the small dataset?

**Comment by atrolle** [comment]
Here is a small data set:

data <- structure(list(CD_RNE = structure(c(19L, 7L, 2L, 34L, 32L, 14L, 
21L, 11L, 25L, 20L, 30L, 12L, 28L, 9L, 31L, 16L, 6L, 22L, 5L, 
3L, 19L, 7L, 2L, 34L, 32L, 14L, 21L, 11L, 25L, 20L, 30L, 12L, 
28L, 9L, 31L, 16L, 6L, 22L, 5L, 3L, 10L, 27L, 4L, 1L, 17L, 35L, 
26L, 13L, 29L, 15L, 24L, 23L, 33L, 8L, 18L, 10L, 27L, 4L, 1L, 
17L, 35L, 26L, 13L, 29L, 15L, 24L, 23L, 33L, 8L, 18L), .Label = c("0050035L", 
"0070001N", "0130040Y", "0131323T", "0131596P", "0131747D", "0132210G", 
"0160079Z", "0300027S", "0300077W", "0310039Z", "0370036N", "0381683Y", 
"0383242T", "0440274J", "0530010Y", "0541318P", "0560182U", "0590101P", 
"0640057P", "0741476C", "0750704H", "0753598D", "0753824Z", "0760052U", 
"0761707T", "0761710W", "0801853E", "0810079W", "0831407D", "0851401L", 
"0930125F", "0940881X", "0951399E", "9741256X"), class = "factor"), 
    CORPUS = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), TAUX_TB = c(0.198, 
    0.158, 0.148, 0.052, 0.075, 0.422, 0.136, 0.161, 0.142, 0.129, 
    0.143, 0.168, 0.053, 0.074, 0.157, 0.106, 0.072, 0.154, 0.243, 
    0.284, 0.75, 0.363636364, 0, 0.5, 1, 0.15, 0.529411765, 0.363636364, 
    0.380952381, 0.243902439, 0.3, 0.666666667, 0, 0.5, 0.375, 
    0.4, 0.285714286, 0.130434783, 0.285714286, 0.625, 0.201, 
    0.237, 0.49, 0.151, 0.282, 0.409, 0.195, 0.161, 0.106, 0.225, 
    0.262, 0.438, 0.369, 0.119, 0.178, 0.75, 0.294117647, 0.454545455, 
    0.333333333, 0.166666667, 0.583333333, 0.285714286, 0.875, 
    0.25, 0.588235294, 0.666666667, 0.333333333, 0.25, 0, 0.666666667
    ), SECTEUR = structure(c(2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L), .Label = c("Privé", "Public"), class = "factor"), 
    NOMBRE_CANDIDATS = c(4L, 11L, 4L, 4L, 2L, 20L, 17L, 22L, 
    21L, 41L, 20L, 6L, 2L, 4L, 8L, 5L, 7L, 23L, 21L, 16L, 4L, 
    11L, 4L, 4L, 2L, 20L, 17L, 22L, 21L, 41L, 20L, 6L, 2L, 4L, 
    8L, 5L, 7L, 23L, 21L, 16L, 4L, 34L, 22L, 6L, 18L, 24L, 7L, 
    8L, 4L, 17L, 6L, 6L, 16L, 2L, 6L, 4L, 34L, 22L, 6L, 18L, 
    24L, 7L, 8L, 4L, 17L, 6L, 6L, 16L, 2L, 6L)), class = "data.frame", row.names = c(NA, 
-70L))

**Comment by atrolle** [comment]
Is this small data set convenient?

**Comment by atrolle** [comment]
Hi,
Any news ?

**Comment by strengejacke** [comment]
no, did not find the time to look deeper into this, but will do the next days.

**Comment by strengejacke** [comment]
I can't fix the model with that data, the error I get it

> Error in gamlss(formula = TAUX_TB ~ CORPUS * SECTEUR + random(CD_RNE),  : 
  response variable out of range

**Comment by atrolle** [comment]
Hi,

Sorry for my late response.
And sorry again, since in my data set the dependent variable contained 0 and 1 values (which is incompatible with Beta regression).
Here is the same data set, without 0 and 1 values:

data <- structure(list(CD_RNE = structure(c(19L, 7L, 2L, 34L, 32L, 14L, 
21L, 11L, 25L, 20L, 30L, 12L, 28L, 9L, 31L, 16L, 6L, 22L, 5L, 
3L, 19L, 7L, 2L, 34L, 32L, 14L, 21L, 11L, 25L, 20L, 30L, 12L, 
28L, 9L, 31L, 16L, 6L, 22L, 5L, 3L, 10L, 27L, 4L, 1L, 17L, 35L, 
26L, 13L, 29L, 15L, 24L, 23L, 33L, 8L, 18L, 10L, 27L, 4L, 1L, 
17L, 35L, 26L, 13L, 29L, 15L, 24L, 23L, 33L, 8L, 18L), .Label = c("0050035L", 
"0070001N", "0130040Y", "0131323T", "0131596P", "0131747D", "0132210G", 
"0160079Z", "0300027S", "0300077W", "0310039Z", "0370036N", "0381683Y", 
"0383242T", "0440274J", "0530010Y", "0541318P", "0560182U", "0590101P", 
"0640057P", "0741476C", "0750704H", "0753598D", "0753824Z", "0760052U", 
"0761707T", "0761710W", "0801853E", "0810079W", "0831407D", "0851401L", 
"0930125F", "0940881X", "0951399E", "9741256X"), class = "factor"), 
    CORPUS = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), TAUX_TB = c(0.198, 
    0.158, 0.148, 0.052, 0.075, 0.422, 0.136, 0.161, 0.142, 0.129, 
    0.143, 0.168, 0.053, 0.074, 0.157, 0.106, 0.072, 0.154, 0.243, 
    0.284, 0.75, 0.363636364, 0.001, 0.5, 0.999, 0.15, 0.529411765, 
    0.363636364, 0.380952381, 0.243902439, 0.3, 0.666666667, 
    0.001, 0.5, 0.375, 0.4, 0.285714286, 0.130434783, 0.285714286, 
    0.625, 0.201, 0.237, 0.49, 0.151, 0.282, 0.409, 0.195, 0.161, 
    0.106, 0.225, 0.262, 0.438, 0.369, 0.119, 0.178, 0.75, 0.294117647, 
    0.454545455, 0.333333333, 0.166666667, 0.583333333, 0.285714286, 
    0.875, 0.25, 0.588235294, 0.666666667, 0.333333333, 0.25, 
    0.001, 0.666666667), SECTEUR = structure(c(2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Privé", "Public"), class = "factor"), 
    NOMBRE_CANDIDATS = c(4L, 11L, 4L, 4L, 2L, 20L, 17L, 22L, 
    21L, 41L, 20L, 6L, 2L, 4L, 8L, 5L, 7L, 23L, 21L, 16L, 4L, 
    11L, 4L, 4L, 2L, 20L, 17L, 22L, 21L, 41L, 20L, 6L, 2L, 4L, 
    8L, 5L, 7L, 23L, 21L, 16L, 4L, 34L, 22L, 6L, 18L, 24L, 7L, 
    8L, 4L, 17L, 6L, 6L, 16L, 2L, 6L, 4L, 34L, 22L, 6L, 18L, 
    24L, 7L, 8L, 4L, 17L, 6L, 6L, 16L, 2L, 6L)), row.names = c(NA, 
-70L), class = "data.frame")

I've just tested the following code:
```
model <- gamlss(formula = TAUX_TB ~ CORPUS * SECTEUR + random(CD_RNE), sigma.formula = ~ 1,
                              data = data, family = BE(),  weights = data$NOMBRE_CANDIDATS) 
```
 It works now.

**Comment by atrolle** [comment]
Hi,

With this new data set, have you succeded in reproducing the initial error?

**Comment by strengejacke** [comment]
I haven't found time to look closer into this issue, but will do this the next days.

**Comment by strengejacke** [comment]
At this point I am not getting anywhere at the moment:

```r
d <- new_data(model, c("CORPUS","SECTEUR"))
d
#>   CORPUS SECTEUR   CD_RNE NOMBRE_CANDIDATS
#> 1      0   Privé 0050035L               NA
#> 2      1   Privé 0050035L               NA
#> 3      0  Public 0050035L               NA
#> 4      1  Public 0050035L               NA
 
predict(model, newdata = d)
#> Error in data.frame(data, source = namelist) : 
#>   arguments imply differing number of rows: 4, 5
```

**Comment by atrolle** [comment]
Hi,

This error may be due to the fact that weights ("NOMBRE_CANDIDATS") are used in the model.

**Comment by strengejacke** [comment]
There was a similar issue that has been fixed (https://github.com/strengejacke/ggeffects/issues/159), maybe your issue was related and is also fixed
 Can you please download the latest [insight](https://easystats.github.io/insight/) and the latest _ggeffects_ from GitHub and check if it works now?

**Comment by atrolle** [comment]
Hi,

I've just dowloaded the latest versions of `insight` and `ggeffects` from GitHub.
When executing the command:
`eff <- ggpredict(model, terms = c("CORPUS","SECTEUR"), type = "re")`
I get the same error message as you indicated earlier:

> Error in data.frame(data, source = namelist) : 
>   arguments imply differing number of rows: 4, 5

**Comment by atrolle** [comment]
Hi,

Any news ?

**Comment by strengejacke** [comment]
no, not yet. still cannot resolve https://github.com/strengejacke/ggeffects/issues/194#issuecomment-808267345

**Comment by melina-leite** [comment]
Hi all,

I just had the same problem and found [this post on stackoverflow](https://stackoverflow.com/questions/39125600/r-error-in-data-framedata-source-namelist-arguments-imply-differing-num) showing that the problem is in the gamlss package:
>"So I contacted Mikis Stasinopoulos who as usual was very helpful. It turns out that the problem is that the dataset I was using was called "data" and while that's fine for estimation, it's not for prediction. Renaming the dataset "mydata" throughout solved the problem."

The data object should not have the name "data". I just renamed the object and it worked perfectly!
I'm writing this just in case someone with the same problem drop by this page.
