### ISSUE TITLE
problems with poly term persist

### ISSUE THREAD

**Issue by cperk** [strengejacke/ggeffects#197]
I thought updating ggeffects to the current version would eliminate issues with poly terms, but that hasn't been the case. I continue to have problems:

```
#create toy dataset
df1 <- data.frame(production=c(15,12,10,9,6,8,9,5,3,3,2,1,0,0,0,0), Treatment_Num=c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4), Genotype=c(1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2))

#run model with poly term
df1_glmer <- glmer(production ~ poly(Treatment_Num,2,raw=T) +(1|Genotype),
                   data = df1, family = poisson(link = "log"))

#try to run ggeffects, but get error
df1_glmer_fe <- ggpredict(df1_glmer, terms = c("Treatment_Num [all]"), type = "fe")


```
![Screen Shot 2021-03-15 at 12 23 44 PM](https://user-images.githubusercontent.com/21315115/111186362-53ed3380-8589-11eb-88c1-009bd7274f14.png)

I've tried using I(^2) instead of poly() but it results in a different model fit and strange predictions.

**Comment by strengejacke** [comment]
It works when you write `TRUE` instead of `T`:

``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)

#create toy dataset
df1 <- data.frame(production = c(15, 12, 10, 9, 6, 8, 9, 5, 3, 3, 2, 1, 0, 0, 0, 0), 
                  Treatment_Num = c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4), 
                  Genotype = c(1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2))

#run model with poly term
df1_glmer <- glmer(production ~ poly(Treatment_Num, 2, raw = TRUE) + (1 | Genotype), 
                   data = df1, family = poisson(link = "log"))
#> boundary (singular) fit: see ?isSingular

ggpredict(df1_glmer,
          terms = c("Treatment_Num [all]"),
          type = "fe")
#> # Predicted counts of production
#> # x = Treatment_Num
#> 
#> x | Predicted |        95% CI
#> -----------------------------
#> 1 |     11.34 | [8.49, 15.16]
#> 2 |      7.47 | [5.31, 10.50]
#> 3 |      1.78 | [1.01,  3.16]
#> 4 |      0.16 | [0.03,  0.89]
#> 
#> Adjusted for:
#> * Genotype = 0 (population-level)
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
The problem is that `T` is not a reserved word, but a global variable (see `?TRUE`), and thus `all.vars()` returns `"T"` as a model predictor (see below), which causes the error. I'm not sure if it's good practice to treat `T` as reserved word in this case (so I would remove this from the list of predictors), because there might be edge cases where people have a predictor named "T". Thus, I recommend writing `TRUE` instead of `T`.

``` r
library(lme4)
#> Loading required package: Matrix
#create toy dataset
df1 <- data.frame(production = c(15, 12, 10, 9, 6, 8, 9, 5, 3, 3, 2, 1, 0, 0, 0, 0), 
                  Treatment_Num = c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4), 
                  Genotype = c(1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2))

#run model with poly term
df1_glmer <- glmer(production ~ poly(Treatment_Num, 2, raw = T) + (1 | Genotype), 
                   data = df1, family = poisson(link = "log"))
#> boundary (singular) fit: see ?isSingular

all.vars(formula(df1_glmer))
#> [1] "production"    "Treatment_Num" "T"             "Genotype"
```

<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by cperk** [comment]
Thanks, Daniel! "T" is accepted as equivalent to "TRUE" in many other
packages, otherwise I wouldn't have thought to use it! But writing out
"TRUE" in ggeffects is easy enough.
