### ISSUE TITLE
Plot predictions over time for survival model 

### ISSUE THREAD

**Issue by cperk** [strengejacke/ggeffects#199]
Hello @strengejacke ,

I am excited to use ggeffects for generating predictions from survival models; a few days ago I posted this question because I couldn't figure out how to plot survival probabilities over time. Since then I've figured out how to do it using type="survival" (see below). However, I have run into another issue: I cannot figure out how to tell the ggeffects plot function that I want the x axis to start at day 1.

```
#read in dataset; relevant columns include Treatment, Source Salinity, Days_to_death and censored
df1 <- data.frame(production=c(15,12,10,9,6,8,9,5,3,3,2,1,0,0,0,0), Treatment_Num=c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4), Genotype=c(1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2), Source_Salinity=c("Fresh","Fresh","Brackish","Brackish","Fresh","Fresh","Brackish","Brackish","Fresh","Fresh","Brackish","Brackish","Fresh","Fresh","Brackish","Brackish"), Days_to_death <- c(500, 500, 500, 500, 400, 350, 300, 500, 200, 202, 260, 280, 150,150,160,140), censored <- c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0))

```
```
#create surv object
surv_object_toy <- Surv(time = df1$Days_to_death, event = df1$censored)

#run cox survival analysis
Coxfit1_toy <- coxph(surv_object_toy ~ Treatment_Num + Source_Salinity, data = df1)

#run predict with type="survival"
gg_cox_toy <- ggpredict(Coxfit1_toy, c("Treatment_Num [all]", "Source_Salinity [all]"),type = "survival")


#try plotting, but find that X axis doesn't start at day 1

plot(gg_cox_toy)
```

![Screen Shot 2021-03-24 at 3 58 52 PM](https://user-images.githubusercontent.com/21315115/112375979-46872600-8cba-11eb-863c-5bc9893fe98f.png)

```
#trying to specify scale_x_continuous limits throws error
plot(gg_cox_toy, scale_x_continuous(limits = c(1,500)))
```

![Screen Shot 2021-03-24 at 3 58 25 PM](https://user-images.githubusercontent.com/21315115/112376041-5acb2300-8cba-11eb-8ea7-eaefc0606be1.png)

```
#by comparison, ggadjustedcurves can plot it starting with day 1, so we can track individuals all the way from day 1 when all individuals are alive, till day 500 which is the end of the experiment period.

survminer::ggadjustedcurves(Coxfit1_toy,data = df1, variable="Treatment_Num", xlab="Days", ylab="Probability of Maintaining >50% Green Leaf Length", legend.title="")

```
![Screen Shot 2021-03-24 at 3 59 21 PM](https://user-images.githubusercontent.com/21315115/112376006-4dae3400-8cba-11eb-8afe-133dbb7f7c4f.png)

Could you please help me out?

Thank you!

-Carrie

**Comment by strengejacke** [comment]
Hi Carrie, the issue here is that the first event occurs at time = 140. That's why the x-axis isn't starting from 1. I'll see how I can fix that.

**Comment by strengejacke** [comment]
Should work now!
