### ISSUE TITLE
Passing poly objects to ggpredict

### ISSUE THREAD

**Issue by bta258** [strengejacke/ggeffects#2]
I've been struggling for a while now to visualize a set of relatively complex three-way interactions arising from a series of linear mixed effects model in R. I recently came across the ggeffects package, which looked like it might finally offer a solution, and I've mostly been having a lot of success using it. The problem I'm having is that one of my models involves a polynomial term -- for simplicity sake, let's say that the model takes the form of

`m <- lmer(poly(X, 2)*Y*Z + (1|SubjectID))`

where X and Y are continuous variables, and Z is a categorical variable. However, when I attempt to run the command... 

`dat <- ggpredict(model.Test1, terms = c("X", "Y [alpha, beta, gamma]", "Z"), type = "re", allow.new.levels = TRUE)`

...it produces the following error: "Column `poly(x, 2)` must be a 1d atomic vector or a list." I'm wondering if there are any good solutions that might allow me to visualize the three-way interaction while still retaining the polynomial term. Thanks!

**Comment by strengejacke** [comment]
You can use `I()`. Both models are equivalent, according to their predictions:

```
library(lme4)
library(ggeffects)

data(sleepstudy)
sleepstudy$Var <- sample(1:5, size = 180, replace = T)

fit1 <- lmer(Reaction ~ poly(Days, 2) * Var + (Days | Subject), sleepstudy)
fit2 <- lmer(Reaction ~ Days * Var + I(Days ^ 2) * Var + (Days | Subject), sleepstudy)

predict(fit1)
predict(fit2)

dat <- ggpredict(fit2, terms = c("Days", "Var"))
plot(dat)
```

**Comment by strengejacke** [comment]
Should work now, however, for `poly()` or `bs()`, your data needs to be in the environment.
