### ISSUE TITLE
Standard errors 

### ISSUE THREAD

**Issue by niekverw** [strengejacke/ggeffects#207]
I noticed that the standard error output for logistic regression is not entirely what I expected it to be. 

please have a look at the following code, it generates quite large standard errors, much larger than would be expected on the 95% confidence interactions (which I calculate as pred$se_correct). How should I interpret the standard errors? 

```
mydata <- read.csv("https://stats.idre.ucla.edu/stat/data/binary.csv")
mydata$rank <- factor(mydata$rank)
mylogit <- glm(admit ~ gre + gpa + rank, data = mydata, family = "binomial")

pred <- ggeffects::ggeffect(mylogit,terms = c("rank"))
pred$se_correct <- (pred$predicted - pred$conf.low)/1.96
data.frame(pred)
```

<img width="520" alt="image" src="https://user-images.githubusercontent.com/11492933/115459201-11bdae80-a227-11eb-8288-77371c7a712c.png">

Thanks!

**Comment by strengejacke** [comment]
See `?ggpredict`, section "Value":

> the standard error of the predictions. Note that the standard errors are always on the link-scale, and not back-transformed for non-Gaussian models!

Related to #151
