### ISSUE TITLE
ggeffect applied to a factor term

### ISSUE THREAD

**Issue by larmarange** [strengejacke/ggeffects#21]
When you apply ggeffect to a factor term, e.g.

```
ggeffect(mod, "sex")
```

the values of `x` in the return object are numbers (i.e. 1 and 2) instead of the factor labels.

**Comment by strengejacke** [comment]
Yes, that's intended by design, because - afaik - STATA users are used to plot discrete plots with a "connecting line":

```r
library(ggeffects)
library(ggplot2)
data(iris)
m <- lm(Sepal.Width ~ Species, data = iris)
p <- ggpredict(m, "Species")

ggplot(p, aes(x = x, y = predicted)) +
  geom_point() +
  geom_line()
```

But there's an attribute that saves the information if `x` is a factor or not, see `attr(*, "x.is.factor")`. And the `plot()` function from _ggeffects_ plots discrete x-values in the correct manner.

**Comment by strengejacke** [comment]
Oh, and the labels are stored as attribute as well

**Comment by larmarange** [comment]
OK. 

Thank you for your explanation. Maybe it could be relevant to add a quick helper function to transform x as a factor for individuals using the result of ggeffect directly with ggplot2, and not through your plot function?

One additional minor thing: currently, the original order of a factor is not preserved. See the example below:

```r
iris$Species <- relevel(iris$Species, "versicolor")
mod <- lm(Sepal.Length~Species, data = iris)
plot(ggeffect(mod, "Species"))
```

Thanks again for your package

**Comment by strengejacke** [comment]
Just saw that this is an issue with the _effects_ package. If you call `ggpredict()`, order of levels is ok:

```r
data(iris)
iris$Species <- relevel(iris$Species, "versicolor")
mod <- lm(Sepal.Length~Species, data = iris)
plot(ggpredict(mod, "Species"))
```

`ggeffect()` internally calls `effects::effect()`, which then returns the factor with initial level order.

**Comment by larmarange** [comment]
Thanks
