### ISSUE TITLE
Problem adding raw data to interaction plots

### ISSUE THREAD

**Issue by influence-of-canopy-on-temperature** [strengejacke/ggeffects#210]
When I plot the marginal effects with ggplot, the raw data appears correctly, within the range of 0 to 1. However, when I use the interaction plot with the plot() function of ggeffects, the data appears wrongly, from -0.25 to 1.2, and with the dots in strange positions. Besides that, some lines and confidence ribbons of one phase do not go until the end of the X axis, both in ggplot and in the plot() function of ggeffects.
Here are my plots and code, attached. The database is available at: https://yadi.sk/d/Z_VY8DD7Hcf8bg

![Rplot_ggplot_ggeffects](https://user-images.githubusercontent.com/35402312/116028272-cc352300-a624-11eb-9627-56c3aec611c1.png)

![Rplot_interaction_ggeffects](https://user-images.githubusercontent.com/35402312/116028268-cb9c8c80-a624-11eb-83dd-01c3eb13e72c.png)

Code:

[problem_ggeffects.txt](https://github.com/strengejacke/ggeffects/files/6374287/problem_ggeffects.txt)

**Comment by strengejacke** [comment]
By default, dots are "jittered" to prevent overlapping. Try setting `jitter = FALSE` in the plot method:

```r
plot(
  mydf_interaction,
  add.data = TRUE,
  limits = c(0, 1000),
  jitter = FALSE
) +
  labs(
    title = NULL,
    x = "Native plant cover",
    y = "Pest abundance",
    colour = "Phase"
  )
```
