### ISSUE TITLE
Is it possible to expose the "Data grid generation" engine?

### ISSUE THREAD

**Issue by sven-stodtmann** [strengejacke/ggeffects#211]
I really like the way ggeffects handles the "terms" argument flexibly to generate new datasets for prediction. I am also sometimes working with model types that are not supported by emmeans, in which case I build a similar grid manually and perform a parametric bootstrap to get the results. 
Would it be possible to somehow expose the parts of the package that create the data grids with a nice "ggemmeans" like interface ('ggref_grid' I guess) ?
If there is interest, I'd also be happy to contribute my parametric bootstrap code either as a function in the package or separately to integrate with.

**Comment by strengejacke** [comment]
Do you mean just the [`data_grid()`](https://strengejacke.github.io/ggeffects/reference/new_data.html) function?

**Comment by sven-stodtmann** [comment]
Thanks for the quick reply. I think data_grid() is close, but not quite what I am looking for. If I have a model with a factor variable that is not in "terms", I'd expect to get weights for all levels (as I get e.g. with emmeans::ref_grid(mod)@grid). I think thats not currently possible with data_grid().

**Comment by strengejacke** [comment]
Ok, got it. But ggeffects does not generate a data grid comparable to the ref-grid from emmeans. In such cases, I guess you need to use emmeans instead.

**Comment by sven-stodtmann** [comment]
Thanks again. I'll close this and leave my solution (works for me, but I didn't test beyond my use case).
```
ggref_grid <- function(mod,terms,condition=NULL,...){
   gggrid  <- ggeffects::new_data(mod,terms,condition)
   gglst   <- as.list(gggrid)
   ggterms <- gglst[!names(gglst)%in%names(attr(gggrid,'constant.values'))]
   emmeans::ref_grid(mod,at=ggterms,...)@grid
}
```

**Comment by strengejacke** [comment]
Maybe I can implement your code, as alternative to `data_grid()`?

**Comment by sven-stodtmann** [comment]
That would be great! It's probably more work on your side, since I've never done it before, but I am also happy to try myself at making a pull request for this feature...
