### ISSUE TITLE
Marginal effect of interaction

### ISSUE THREAD

**Issue by PatrickDeelen** [strengejacke/ggeffects#213]
I'm sorry if I missed it in the docs.

Is there any way to only get the marginal effect of the interaction between two terms?

I have a model: `y = time + time^2 + x + x * time + confounders`

I'm interested in the only the marginal effect of `x * time`

If I do: `ggeffect(res, terms = c("time", "x") `. The result is very nice prediction and informative plot. Unfortunately it is also based on the individual effect of `time` and `x` in addition to the interaction. 

Is it possible to only run ggeffect to only get the interaction of the two specified terms?

**Comment by strengejacke** [comment]
What do you mean with "individual effect"?

**Comment by PatrickDeelen** [comment]
Both `x` and `time` have a their own marginal effect. x has a simple slope and time has the slope plus the polynomial curve.

On top of those "individual effects", or I suppose marginal effects is a better name, of time and x, we also have a subtle interaction effect. However when this is visualized it is not very clear. 

I have written some code to manually plot the marginal effects by creating dummy data. The top figure is the same as ggeffects however without the confidence interval. Purple is high x, red is mean x, and yellow is low x The bottom figure is only the interaction between x and time, here it is much clearer that with time the effect of x is getting larger over time. Is it possible to use ggeffect to create the bottom plot?

![image](https://user-images.githubusercontent.com/1851172/117015647-379c8600-acf2-11eb-9f7d-db914790ecdd.png)

**Comment by mattansb** [comment]
This is somewhat related to #182 - currently it is not possible.

**Comment by PatrickDeelen** [comment]
Thank you for the suggestion, that is indeed what I'm trying to do.

**Comment by strengejacke** [comment]
closing in favor of #182
