### ISSUE TITLE
Error in plot_model() and ggpredict() with binomial models

### ISSUE THREAD

**Issue by pmanlick** [strengejacke/ggeffects#214]
Hello, I'm having a new issue using `plot_model()` and `ggpredict()` with stanreg objects of family binomial, in this case a betareg model. I'm getting the error "Error in if (binom_fam | exponential_fam | poisson_fam | neg_bin_fam |  : 
  argument is of length zero" using some code that I've been implementing for several years now. Perhaps a bug in a recent update, as this was working ~3 weeks ago. I have attached a reproducible example below:

library(rstanarm)
library(sjPlot)

data(iris)

#Min-max normalize to 0-1 (for beta regression)
max=max(iris$Sepal.Length)
min=min(iris$Sepal.Length)
iris$Sepal.Length <- (iris$Sepal.Length-min)/(max-min)

#Transform for betareg, no 1's or 0's -> Smithson, M., & Verkuilen, J. (2006). A better lemon squeezer? 
iris$Sepal.Length<-(iris$Sepal.Length*149+.5)/150

mod1<- stan_glmer(Sepal.Length ~ Sepal.Width + Petal.Length + Petal.Width + (1|Species), family=mgcv::betar, data=iris)
mod2<- stan_glmer(Sepal.Length ~ Sepal.Width + Petal.Length + Petal.Width + (1|Species), data=iris)
plot_model(mod1)
plot_model(mod2)

mod1 produces the error, while mod2 works as expected. `ggpredict` produces the same error when plotting predicted fixed effects. I have updated all packages from cran and github where available.

Any help is much appreciated! Thanks!

**Comment by strengejacke** [comment]
Thanks, this is a bug in `insight::model_info()`. Closing in favor of https://github.com/easystats/insight/issues/373
