### ISSUE TITLE
collapse.group + residual: first average, then transform

### ISSUE THREAD

**Issue by mattansb** [strengejacke/ggeffects#218]
Currently, for models with links we do:

1. Get residualized data
2. Back transform
3. Average

But the last two should be reversed:

1. Get residualized data
2. Average
3. Back transform

I'll take a crack at it at some point. 
Seeing as how I'm the only one who uses both.... This is low priority (:

**Comment by strengejacke** [comment]
bump @mattansb  :-)

**Comment by mattansb** [comment]
![GameOfThronesNotTodayGIF](https://user-images.githubusercontent.com/35330040/220108852-3e6d0ef0-1f63-4752-82ee-7ed2fd920045.gif)

**Comment by mattansb** [comment]
![NopeNotTodayBabyGIF](https://user-images.githubusercontent.com/35330040/220114293-b66383eb-3787-4524-9cb1-0ed81398f07b.gif)

**Comment by strengejacke** [comment]
Today? 😬

**Comment by mattansb** [comment]
I've completely changed my mind on this!

We should leave it as is.

**Comment by strengejacke** [comment]
Ok!
