### ISSUE TITLE
Confidence intervals for 'averaging' objects

### ISSUE THREAD

**Issue by gee-ive-turkey** [strengejacke/ggeffects#219]
Getting the 'Confidence intervals could not be computed' error for averaging objects.  I updated insights and ggeffects following recommendations here  https://github.com/strengejacke/ggeffects/issues/101  but it did not help.   

Reproducible example using case from Mumin documentation.

# Example from Burnham and Anderson (2002), page 100:
fm1 <- lm(y ~ X1 + X2 + X3 + X4, data = Cement)
options(na.action = "na.fail")
ms1 <- dredge(fm1)
confset.95p <- get.models(ms1, subset = cumsum(weight) <= .95)
avgbart <- model.avg(confset.95p)

pred_fit<-ggpredict(avgbart, terms = "X1")  #Error: Confidence intervals could not be computed
pred_fit<-ggpredict(avgbart)  #Error: Confidence intervals could not be computed

avgbart2<-model.avg(ms1)

pred_fit<-ggpredict(avgbart2, terms = "X1")  #Error in insight::clean_names(colnames(model_frame)):
pred_fit<-ggpredict(avgbart2)  #Error in insight::clean_names(colnames(model_frame)):

avgbart3<-model.avg(ms1, fit = TRUE)
pred_fit<-ggpredict(avgbart3, terms = "X1")  #Could not compute variance-covariance matrix of predictions. No confidence intervals are returned.
pred_fit<-ggpredict(avgbart3) #Could not compute variance-covariance matrix of predictions. No confidence intervals are returned.

**Comment by gee-ive-turkey** [comment]
Update to issue above.  I updated R, and all packages.   ggeffects and mumin seem to play well if I use the 'full' averaging object that contains all the models from the original dredge call (avgbart1 below), as long as the models are refitted.  However, if I do any type of model subsetting to reduce the number of models in the averaging object (avgbart2), ggeffects throws a confidence intervals error.   There must be some difference in the two averaging objects (avgbart1 vs avgbart2) but I can't find it.  Will contact author of Mumin. 

#Testing Barton's example with ggpredict
fm1 <- lm(y ~ X1 + X2 + X3 + X4, data = Cement)
options(na.action = "na.fail")
ms1 <- dredge(fm1)

#Try all models, no refitting
avgbart<-model.avg(ms1)  #model average across ms1..all models, no refitting
pred_fit<-ggpredict(avgbart) #THIS DOES NOT WORK, must refit

#Try all models, with refitting
avgbart1<-model.avg(ms1, fit = TRUE)  #model average across ms1..all models, refit this time
pred_fit1<-ggpredict(avgbart1) #THIS WORKS
pred_fit1a<-ggpredict(avgbart1, terms = "X1") #THIS WORKS
plot(pred_fit1a)  #Good plot with linear effect and CI

#Subset model selection
confset.95p <- get.models(ms1, subset = cumsum(weight) <= .95)
avgbart2 <- model.avg(confset.95p, fit=TRUE)
pred_fit2<-ggpredict(avgbart2) #Error: Confidence intervals could not be computed

**Comment by strengejacke** [comment]
Closing in favor of #388
