### ISSUE TITLE
memory allocation error with ggeffect, ggpredict

### ISSUE THREAD

**Issue by emjonaitis** [strengejacke/ggeffects#22]
I have a three-way interaction from an lmer model that I was able to summarize and plot easily with the `effects` package. However, when I try to summarize it using `ggeffect` I get the following error message: `Error: cannot allocate vector of size 84619.5 Gb`. With `ggpredict` I get a similar but less alarming message (the vector size is ~8.3 Gb). I have no sample data I can share, but the fact that this works in `effects` but not `ggeffects` makes me suspect a bug.

**Comment by richardneilbelcher** [comment]
I just had a similar issue with the ggpredict function. Setting ci.lvl = NA made it work without the vector error (although ggeffect worked for me). With other lme4 prediction tools they can use some intensive methods for degrees of freedom calculations so that may be it.

**Comment by strengejacke** [comment]
If one of the terms is continuous, try to specify some values, e.g. `terms = "cont_var [10, 20, 30, 40, 50]"`, if `cont_var` ranges from 10 to 50. I use `expand.grid()` on all possible values, and computation of CI might be very memory consuming in such cases. The _effects_ package, by default, does not compute effects and CI for _all_ possible values, but also for a selction only.

**Comment by strengejacke** [comment]
Could you please check if this issue still exists in the current dev-version? I have added a `pretty` argument, which creates a sequence of "pretty" numbers for predictor terms with many unique values.

**Comment by strengejacke** [comment]
Since `pretty` does not plot splines nicely, I've changed the default to `pretty = FALSE`. So, if possible, please check if `ggpredict(..., pretty = TRUE)` solves your issue.

**Comment by vspinu** [comment]
I am having same issue with `ggeffects::ggalleffects` which blows to 15GB for 64k row x 9col data set. `ggeffects::predict` doesn't work for me because I have `sales(forecast)` term in my formula:

```R
> labels(terms(M))
 [1] "error"               "scale(forecast)"     "error2"             
 [4] "waste1"              "waste2"              "sales"              
 [7] "family"              "scale(transactions)" "cluster"            
[10] "aweek"               "year"                "holid_nat"          
> ggeffects::ggpredict(M, labels(terms(M)), pretty = T)
`terms` must have not more than three values. Using first three values now.
Error in scale(forecast, center = 276.325019004872, scale = 375.963889410209) : 
  object 'forecast' not found
```

The above works just fine with the effects package.

**Comment by strengejacke** [comment]
Try to standardise the variable before you cal fit the model, does this work?

**Comment by vspinu** [comment]
they are standardized. Sorry, I haven't provided the model formula:

```R
waste ~ error + scale(forecast) + error2 + waste1 + waste2 + 
    sales + family + scale(transactions) + cluster + aweek + 
    year + holid_nat
```

I expect this error has something to do with the inline `scale(forecast)`.

**Comment by strengejacke** [comment]
Yes, please standardize before, and don't use "inline" calls to functions. And it's preferred to use `sjmisc::std()`, because `scale()` changes the input type.

**Comment by vspinu** [comment]
> Yes, please standardize before, and don't use "inline" calls to functions. 

Yerh, one too many restriction; I guess I would stay away then. All other standard R software works with "inline" functions and doesn't require standardization (`effects` package including).  But well, every package is different ;)

As a side note, subsampling or pretty=TRUE should be the default. The splines issue is really not an excuse to blow people's R sessions during basic plotting (especially with small data sets).

**Comment by strengejacke** [comment]
Actually, `ggpredict()` should work with the the inline-use of functions, however, the `term`-argument must use the original term names. So `term = "forecast"` should work.

**Comment by strengejacke** [comment]
@emjonaitis and @richardneilbelcher do you still have the memory allocation issues if you set `pretty = TRUE`? I think I will indeed make this as default option, and print a message if prettifying was done, so the user is not too curious about less smoothed plots.

**Comment by strengejacke** [comment]
I revised the calculation for CI for mixed models, which now should be more efficient. When you now either use:
```r
ggpredict(model, term = "myterm", pretty = TRUE)
```
or
```r
ggpredict(model, term = "myterm [range]")
```
does one of these two options solve your issue? This requires the current GitHub-version of **ggeffects**.

**Comment by strengejacke** [comment]
@vspinu If you want to plot effects for all model terms, you can now simply leave the `terms` argument missing or `NULL`, so just calling `ggeffects::ggpredict(M)` should work, and is comparable (regarding the effort) to `allEffects(M)`.

**Comment by strengejacke** [comment]
I'd be happy if someone who still had problems with memory allocation errors, could check the current GitHub-version. It automatically should calculate a reasonable pretty range of predicted values and should be much more memory efficient when calculating SE/CI for predictions.

**Comment by emjonaitis** [comment]
Thanks for the reminder - I’ll check when I get into work today.

**Comment by strengejacke** [comment]
_bump_

**Comment by emjonaitis** [comment]
Hi Daniel - yes, I am still getting out of memory errors ("Error: cannot
allocate vector of size 84619.5 Gb"). To clarify, do I need to be working
with a branch of the code other than master? Currently I'm just running
devtools::install_github("strengejacke/ggeffects") with no other arguments
set but please let me know if I need to be doing something different.

Erin

**Comment by strengejacke** [comment]
No, it's the correct version you are using, either the master branch or the current GitHub version should be more memory efficient.
When you run `ggpredict()`, does it display a message about prettifying the values?

**Comment by strengejacke** [comment]
Thanks for looking into this. `ggeffect()` calls `effects::effect()`, so it might be an issue of the _effects_ package. I'll try to find out where the issue is located.

**Comment by strengejacke** [comment]
I just realized that `ggeffect()` is not optimized, it only applies to `ggpredict()`. `ggeffect()` was a bit neglected by me, and I was always thinking of `ggpredict()` when talking about this issue. 🙄

**Comment by strengejacke** [comment]
Ok, memory allocation problems with `ggeffect()` should also be solved now.

**Comment by emjonaitis** [comment]
Just closing the loop on this - it works like a charm now. Thanks for all
your work on this project. I have been wanting/needing modifiable effects
plots and I think this will be my answer.

Erin Jonaitis
