### ISSUE TITLE
How are continuous predictors binned into groups? Where is the code/procedure for this?

### ISSUE THREAD

**Issue by JacobElder** [strengejacke/ggeffects#220]
Hi,

Love the package and thanks for the amazing work with it. I am preparing some analyses and for something specific, I need to extract the raw data at each level of the plot. My plot appears as below:
![image](https://user-images.githubusercontent.com/16260312/121234563-af595580-c848-11eb-928c-6bc22a61d768.png)

In order to do so, I have used the function, "raw <- attr(p, "rawdata")".

However, my grouping variable is a continuous variable that was binned into three levels by ggpredict. Here is what the raw data frame looks like:
![image](https://user-images.githubusercontent.com/16260312/121234451-90f35a00-c848-11eb-9888-0b6bd0636c22.png)

Here is what the ggpredict groupings look like:
![image](https://user-images.githubusercontent.com/16260312/121234506-a10b3980-c848-11eb-9690-aca9bab6bffe.png)

I would like to know what function or procedure is used for binning the raw, continuous group variables as seen in the raw data dataframe, into the three levels seen in the ggpredict output p$group variable. There are three levels of a categorical factor there. But in the raw data, the groups are still continuous. I would like to inspect my raw outcome variable "response" at each bin/level of the continuous "group" variable that was coerced into three levels of a categorical factor.

I attempted

if < lowest level, then lowest interval
if between lowest interval and highest interval, then mid interval
if > highest interval, then highest interval

But that doesn't appear to be how this was done.

I understand that values_at is used to determine the levels of this "group" variable. But I am not clear on how the continuous "group" variables are sorted into the levels.

Any insight on how you went about binning these groups would be much appreciated.

**Comment by strengejacke** [comment]
For continuous variables, representative values are chosen. See
https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html
https://strengejacke.github.io/ggeffects/reference/values_at.html

However, you can use `add.data`, which will add raw data points for you:

``` r
library(ggeffects)
data(iris)
m <- lm(Sepal.Width ~ Petal.Width * Petal.Length, data = iris)
pr <- ggpredict(m, c("Petal.Width", "Petal.Length"))
plot(pr, add.data = TRUE)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/Opv8fKw.png)

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
