### ISSUE TITLE
"object is not a matrix" error in ggpredict()

### ISSUE THREAD

**Issue by WillemSleegers** [strengejacke/ggeffects#221]
I'm trying to obtain predicted values of a fixed effect, for each level of a random effect, using the following code:

```
library(tidyverse)
library(lme4)
library(ggeffects)

data <- read_csv("data.csv")

model <- lmer(response ~ condition_bystanders + (condition_bystanders|ID), 
  data = data)

fit <- ggpredict(model, terms = c("condition_bystanders", "ID"), type = "random")
```

But this produces the following error message:
```
Error in model.matrix.default(eval(substitute(~foo, list(foo = x[[2]]))),  : 
  object is not a matrix
```

Any idea what might be the cause here?

The data can be found here: [data.csv](https://github.com/strengejacke/ggeffects/files/6644174/data.csv)

**Comment by strengejacke** [comment]
Not sure what's going on here, it fails with `predict()` as well:

``` r
library(lme4)
data <- read.csv("D:/Downloads/data_(1).csv")
model <- lmer(response ~ condition_bystanders + (condition_bystanders|ID), 
              data = data)

d <- as.data.frame(expand.grid(unique(data$condition_bystanders), unique(data$ID)))
colnames(d) <- c("condition_bystanders", "ID")
predict(model, newdata = d)
#> Error in model.matrix.default(eval(substitute(~foo, list(foo = x[[2]]))), : object is not a matrix
```

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by WillemSleegers** [comment]
Interesting; thanks for comparing it to `predict()`. This allowed me to google the issue more generally, which revealed some posts about column names perhaps being too long. This wasn't the issue, but it made me think whether the ID values might be an issue. I replaced all the character values with numeric values, and now it seems to work:

```
library(lme4)
library(dplyr)
data <- read.csv("data-2.csv")

data <- data %>%
  group_by(ID) %>%
  summarise(ID2 = 1) %>%
  mutate(ID2 = 1:n()) %>%
  ungroup() %>%
  right_join(data, by = "ID")

model <- lmer(response ~ condition_bystanders + (condition_bystanders|ID2), 
  data = data)
summary(model)

d <- as.data.frame(expand.grid(unique(data$condition_bystanders), unique(data$ID2)))
colnames(d) <- c("condition_bystanders", "ID2")
predict(model, newdata = d)
```

**Comment by strengejacke** [comment]
Closes in https://github.com/lme4/lme4/issues/631 - works after you update _lme4_ from GitHub.
