### ISSUE TITLE
Prediction with a specific input value

### ISSUE THREAD

**Issue by sshojiro** [strengejacke/ggeffects#228]
Hi,

Thank you for implementing and publishing such a nice package. Is it possible for `ggpredict` to return a mean value and the corresponding upper and lower bounds of confidence intervals for new data? As long as I understand, `ggpredict` returns predictions of some representative points. I would like to know if there's a way to feed regression models with specific values of explanatory variables.

Thanks,

**Comment by strengejacke** [comment]
Do you mean something like described in this vignette?

https://strengejacke.github.io/ggeffects/articles/introduction_effectsatvalues.html
