### ISSUE TITLE
typical values for mermod object

### ISSUE THREAD

**Issue by richardneilbelcher** [strengejacke/ggeffects#23]
Hello, I am trying to hold other variables in my model at 0 for continuous and the mode for categorical variables, using ggpredict. When I try to run this:
effect<- ggpredict(model, terms = "x1", type = c("fe", "re"),ci.lvl = NA,**typical =c(numeric = "zero", factor = "mode")**)

I get the following error: 
Error in model.frame.default(delete.response(Terms), newdata, na.action = na.action,  : factor x2 has new level 1.

Setting it just to zero gives me the same problem. Is there a way around this? I would ideally like to set factors at their reference level in the model. Thanks.

Richard

**Comment by strengejacke** [comment]
You need the current dev-version from _sjstats_, then it should work. Or you convert your factor variables to factors with numeric levels, using `sjmisc::to_factor(sjmisc::to_value(x))`.
