### ISSUE TITLE
miscalculations of risk and confidence intervals for Cox models with polynomial terms

### ISSUE THREAD

**Issue by chy055** [strengejacke/ggeffects#233]
What a brilliant package, thank you.

Although your vignette describes polynomial and spline terms being supported, miscalculated risk scores and confidence intervals arise when polynomial or spline terms are involved in a "coxph" or "mfp" object.

Note this example of a marginal effects plot for categorical covariate using plot(ggpredict()) with respect to a multiple Cox model:

![image](https://user-images.githubusercontent.com/54862356/130547809-ccfcb7a2-6069-4beb-8612-f82719a7a1c2.png)

If the non-linear term is removed, or if the non-linear term is forced to be linear, the risk scores and confidence intervals look more reasonable (i.e. with a HR of 1 and 95% CI of [1,1] for the reference value):

![image](https://user-images.githubusercontent.com/54862356/130547935-818ddec6-e0f9-4c16-b83a-2dea75faeddb.png)

To resolve this, I have tried to transform the relevant covariate with the polynomial term in the underlying database, and forcing the covariate to be 'linear' in the Cox model. This corrects the HR to a value of 1, but the confidence intervals are still wrong: 

![image](https://user-images.githubusercontent.com/54862356/130548213-8d3ef4ac-ce0d-485b-9c44-82aa669b2bd0.png)

I cannot seem to be able to force these confidence intervals to be [1,1]. 

Any guidance would be enormously appreciated.

With thanks,

**Comment by chy055** [comment]
I think I have solved this problem, and would like to discuss with you how we may be able to modify your package to accommodate polynomial transformations in Cox models.

**Comment by strengejacke** [comment]
Sorry for being so quiet here, but I was busy with other things. I'll get back to working on _ggeffects_ the next days.

**Comment by chy055** [comment]
I'll drop you an email about this issue.

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
_bump_
