### ISSUE TITLE
Contrasts on ggpredict Output

### ISSUE THREAD

**Issue by awaldman123** [strengejacke/ggeffects#234]
Thank you for a very useful package! I have been calculating marginal means taking into account all sources of variation (fixed effects, zero-inflation, and random effects) using the ggpredict command and type="sim" argument. However, I wanted to inquire about whether the package had a way to use the outputs for pairwise comparisons like the contrasts argument in emmeans? 

I tried using the output of ggpredict as part of a call to the emmeans contrasts function and got the following error:

Error in UseMethod("contrast") : 
  no applicable method for 'contrast' applied to an object of class "c('ggeffects', 'data.frame')"

Is there a way to coerce the data frame to be read by the contrasts function?

**Comment by strengejacke** [comment]
I don't think `ggeffects` objects are supported by _emmeans_, so this won't work. But I think for your purpose, the _marginaleffects_ package by @vincentarelbundock might be a good solution:
https://github.com/vincentarelbundock/marginaleffects

**Comment by vincentarelbundock** [comment]
Thanks for the plug @strengejacke !

Yes, there is some support for contrasts (and marginal effects). See here for some example: https://vincentarelbundock.github.io/marginaleffects/articles/contrasts.html

Please be advised that the package is still "under construction" and that the user interface is still subject to change. (In particular, in the next few days there is going to be a new `marginalmeans` function, and the current `marginalmeans` becomes `predictions`).

**Comment by strengejacke** [comment]
I'm probably closing #107 in favor of your package. Would you say it's possible to add support for `ggeffects` objects? I'm not sure what might be necessary to do that, I have to dig deeper into your API, @vincentarelbundock

**Comment by vincentarelbundock** [comment]
Sounds great!

Frankly, I'm not too sure yet, since the precise API is still shifting, and I don't know the structure of `ggeffects` objects super well.

My guess is that in about 2 weeks the overall structure will be pretty set, and I'll have had time to clean up and annotate the code more thoroughly. It might be wise for you to wait before you dig in, because a fair amount is likely to change until then.

After that, I'll turn my attention to interoperability. I'm *very* eager to make this work well with `ggeffects` and `modelbased`, so we have a discussion about what the best strategy is. 

For instance, what does "add support for `ggeffects` objects" mean? Are we "translating" a `ggeffects`-style call to a `marginaleffects`-style call? The two are very similar, so this should be very easy to do.

Alternatively, should `marginaleffects` behave differently when it is fed a `ggeffects` object? At this stage, I'm not sure what this would mean because I don't "support" anything beyond actual model objects.

But to reiterate, I am very eager to collaborate on this. You just need to give me a bit of time :)

**Comment by strengejacke** [comment]
Well, basically, `ggpredict()` returns a "tidy" data frame of predictions, and there is also a `vcov()` method for `ggeffects` objects. So I thought we "just" need to get the output into a similar format that you have after calling all the `sanity`-functions:

``` r
library(ggeffects)
m <- lm(mpg ~ wt + as.factor(cyl), data = mtcars)
ggpredict(m, "cyl")
#> # Predicted values of mpg
#> 
#> cyl | Predicted |         95% CI
#> --------------------------------
#> 4   |     23.68 | [21.63, 25.72]
#> 6   |     19.42 | [17.52, 21.32]
#> 8   |     17.61 | [15.84, 19.38]
#> 
#> Adjusted for:
#> * wt = 3.22
vcov(ggpredict(m, "cyl"))
#>             1           2           3
#> 1  1.08753073  0.05300063 -0.41400240
#> 2  0.05300063  0.93966846 -0.04449124
#> 3 -0.41400240 -0.04449124  0.81451956
newdata <- data.frame(wt = 3.22, cyl = c(4, 6, 8))
predict(m, newdata = newdata, se.fit = TRUE, interval = "confidence")
#> $fit
#>        fit      lwr      upr
#> 1 23.66872 21.52968 25.80776
#> 2 19.41314 17.42715 21.39913
#> 3 17.59786 15.75193 19.44379
#> 
#> $se.fit
#>         1         2         3 
#> 1.0442447 0.9695286 0.9011545 
#> 
#> $df
#> [1] 28
#> 
#> $residual.scale
#> [1] 2.556914
```

<sup>Created on 2021-09-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Got it.

Roughly speaking, we get the contrasts of a logical variable `x` by doing:

1. Call `insight::get_data(model)` and set the value of `x` to FALSE in every row.
2. Create a second dataset where `x` is equal to TRUE in every row
3. Compute predicted values in both datasets using `insight::get_predicted`
4. Compute the average difference (contrast) in between those two sets of prediction. This gives us the contrasts.
5. Use automatic differentiation to compute the Jacobian of the difference in step 4 w.r.t. to the model's parameters. This gives us the standard errors.

Steps 5 actually requires us to repeat the procedure several times for numerical approximation.

If I understood your explanation correctly, the output of `ggpredict` only gives us the dataset in Step 1, so I'm not sure it would be enough.

**Comment by vincentarelbundock** [comment]
FWIW, steps 1 through 4 occur here: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/marginaleffects.R

**Comment by vincentarelbundock** [comment]
Edit (sorry): link to wrong file above: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_dydx_categorical.R

**Comment by abadgerw** [comment]
I stumbled across this thread and wanted to see if we had implemented this? I'm very interested in being able to compute contrasts after taking into account all sources of variation from a zero-inflated model fit with glmmtmb?

**Comment by strengejacke** [comment]
Not yet from my side. I guess this will take some time until I have more time to look at this.

**Comment by vincentarelbundock** [comment]
Hi @abadgerw,

FYI, I just added support for `glmmTMB` models in the `marginaleffects` package. First, install the development version of the package:

``` r
remotes::install_github("vincentarelbundock/marginaleffects")
```

Second, restart `R` entirely.

Third, you can now estimate pairwise contrasts for zero-inflated negative binomial models (and others):

``` r
library(glmmTMB)
library(marginaleffects)

mod <- glmmTMB(
    count ~ spp + mined + (1 | site),
    zi = ~spp + mined,
    family = nbinom2,
    data = Salamanders)

cont <- comparisons(mod, variables = "mined")
summary(cont)
#> Average contrasts 
#>    Term Contrast Effect Std. Error z value   Pr(>|z|) 2.5 % 97.5 %
#> 1 mined no - yes  1.971      0.203   9.706 < 2.22e-16 1.573  2.369
#> 
#> Model type:  glmmTMB 
#> Prediction type:  response
```

Compare the results to manual computation of contrasts:
\`

``` r
dat1 <- dat2 <- Salamanders
dat1$mined <- "yes"
dat2$mined <- "no"
cont_manual <- predict(mod, type = "response", newdata = dat2) -
               predict(mod, type = "response", newdata = dat1)

head(cont_manual)
#> [1] 1.733719 3.465275 1.143714 1.903443 1.922611 1.681371

head(cont)
#>    rowid  term contrast comparison std.error count spp mined site
#> 1:     1 mined no - yes   1.733719 0.3424304     0  GP   yes VF-1
#> 2:     2 mined no - yes   3.465275 0.8756638     0  GP   yes VF-2
#> 3:     3 mined no - yes   1.143714 0.1997239     0  GP   yes VF-3
#> 4:     4 mined no - yes   1.903443 0.2939509     2  GP    no  R-1
#> 5:     5 mined no - yes   1.922611 0.2903838     2  GP    no  R-2
#> 6:     6 mined no - yes   1.681371 0.2481681     1  GP    no  R-3
```

If this doesn't work for you, please report the issue on the `marginaleffects` Github Issue tracker instead of here, to avoid spamming Daniel.

**Comment by strengejacke** [comment]
Closing this, as now a "basic" function for comparisons/contrasts is implemented. for more differentiated needs, I suggest using the _marginaleffects_ package directly. Yet, more clarifying docs are missing, a decision on the final function name has not been made yet, and I'll try to write a vignette showing the features (and limitations) of that function.
