### ISSUE TITLE
ggpredict with gam with random effect

### ISSUE THREAD

**Issue by asherlevin** [strengejacke/ggeffects#238]
Is there a way to drop the conditioning on the default group when a random effect is fit through s(group, bs="re") in gam?
I have type = "fe" but it doesn't seem to recognize the terms s(group, bs="re") as random effects.  Am I missing something?

**Comment by strengejacke** [comment]
Do you have a small example model to reproduce this issue?

**Comment by irenevalori** [comment]
Hi. I am trying to estimate and plot the effects of the following multinomial model:
m1<-gam(list(stimtype ~ group + s(id, bs="re"),
                      ~ group + s(id, bs="re")),
                      data = agency, family = multinom(K=2))

Tryied the following script:
ggpredict(m1, terms = ~ group)

mydf <- ggpredict(m1, terms = "group")
ggplot(mydf, aes(x, predicted)) +
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .1)

Obtained the following error:
Error in model.frame.default(ff, data = newdata, na.action = na.act) : 
variable lengths differ (found for 'id')

Any suggestions are very much appreciated. Thank you :)

**Comment by strengejacke** [comment]
Do you also have some data, so that the example is fully reproducible for me?

**Comment by strengejacke** [comment]
Closing this for now. Please re-open or file a new issue if this issue still exists for you.
