### ISSUE TITLE
Can ggeffects functions be used on tidymodels Random Forest models?

### ISSUE THREAD

**Issue by kamaulindhardt** [strengejacke/ggeffects#239]
Hi, 

I apologize for posting this here however I could not find other platforms relevant for this question.

My question is whether it is possible to use the ggeffects functions to generate a marginal effects plot where predictions are generated by the Random Forest (regression) model when holding the non-focal variables constant and vary the focal variable?

Thank you

**Comment by strengejacke** [comment]
Do you have a reproducible example?
