### ISSUE TITLE
Problems with offsets

### ISSUE THREAD

**Issue by mdpillet** [strengejacke/ggeffects#24]
For calls to ggpredict on glm model objects from poisson family with more than one offset, the following error occurs:
Error in offset(log(xxxxxx)) : 
  object 'xxxxxx' not found

For calls to ggpredict on glm model objects from poisson family with an offset with arithmetic performed within the offset call (e.g. offset(log(xxxxxx + 0.00001)), the same error as above occurs.

**Comment by strengejacke** [comment]
Please provide a reproducible example.

**Comment by strengejacke** [comment]
should be fixed in https://github.com/strengejacke/sjstats/commit/f8fd653b235731bb960578203f924f1fea51994b, so you need to install the latest GitHub version of **sjstats** in order to solve this issue with **ggeffects**.

**Comment by joehoover** [comment]
Hi, 

This fix does not appear to be working for me. I installed the latest sjstats: 

    devtools::install_github("strengejacke/sjstats")


and then I installed the dev versions in sequence as you suggest in the sjstats readme: 

    devtools::install_github("strengejacke/sjlabelled")
    devtools::install_github("strengejacke/sjmisc")
    devtools::install_github("strengejacke/sjstats")
    devtools::install_github("strengejacke/ggeffects")
    devtools::install_github("strengejacke/sjPlot")

The new installations had no effect on the errors thrown by the following code:

    d = data.frame(x1 = rnorm(100, 0, 1), 
                            x2 = rnorm(100, 0, 1), 
                            pop = rpois(100, 100)) 
 
    d$y = rpois(100, exp(0 + d$x1*.3 + d$x2*-.4 + d$x1*d$x2*.5)) 
    d$log_pop = log(d$pop)
    m <- glm(y ~ x1*x2, offset=log(pop), data=d)
    plot_model(m, type = "pred", terms = c("x1", "x2", "pop")) 

   is.na() applied to non-(list or vector) of type 'NULL'Error in names(datlist) <- names(first) : 
   'names' attribute [3] must be the same length as the vector [2]

    m <- glm(y ~ x1*x2, offset=log_pop, data=d)
    plot_model(m, type = "pred", terms = c("x1", "x2", "log_pop")) 

    ERROR: is.na() applied to non-(list or vector) of type 'NULL'Error in names(datlist) <- names(first) : 
   'names' attribute [3] must be the same length as the vector [2]

    names(sjstats::model_frame(m))`

returns a model frame where the offset term is called `(offset)`.

**Comment by strengejacke** [comment]
This fix addressed a different issue, where the `offset` was part of the formula. Could you please file an issue at the sjstats-repo? https://github.com/strengejacke/sjstats/issues

**Comment by joehoover** [comment]
Oh, perfect. I apologize for not noticing that. I will open the issue, but am glad that there is a workaround!
