### ISSUE TITLE
can't plot raw data by group

### ISSUE THREAD

**Issue by cperk** [strengejacke/ggeffects#245]
Hi!

How can I make the last plot in this tutorial with add.data=T so that the raw data is grouped by color of the error bars and jittered around them so that you can still see the bars? Nothing I try seems to work.

https://mran.microsoft.com/snapshot/2020-02-23/web/packages/ggeffects/vignettes/introduction_plotmethod.html

Thanks!

-Carrie

**Comment by strengejacke** [comment]
I think this is the same issue as #246 - so closing this one.
