### ISSUE TITLE
ordinal::clmm - problem with terms = c("random effect [rf_i]")

### ISSUE THREAD

**Issue by LuiNov** [strengejacke/ggeffects#247]
Hello, 

I thought it was a mistake but I tried it with a classical lmer model and with a clmm (multilevel ordinal model):

I can't specify the levels of the random effects that are conditioned on. In my case it is (1|year_f) where year is a 4 level factor of interview years.

I did an example with the famous species..... now an ordered variable ... there was not better dataset...
```
#datasets::iris %>% glimpse
#get ordered variable and a factor for random effects
iris %>% mutate(species_o = ordered(Species), petal_length_cut_f = cut(iris$Petal.Length,4) )->temp
#fit model
clmm(species_o~Sepal.Width+(1|petal_length_cut_f), data = temp, link = "probit")->clmm_fit
#predict
ggpredict(clmm_fit, terms = c("petal_length_cut_f [all]", "Sepal.Width [all]"), type = "re")-> gp
```
Throws an error just like in my own data: 
`Predicted values can't be computed for levels of random effects from 'clmm' models.
Please remove following variables from 'terms': petal_length_cut_f`

With lmer (likewise also with other multilevel model functions) it is working without any bugs. 
```
#fit model
lmer(as.numeric(species_o) ~Sepal.Width+(1|petal_length_cut_f), data = temp)->lmer_fit
#predict
ggpredict(lmer_fit, terms = c("petal_length_cut_f [all]", "Sepal.Width [all]"), type = "re")-> gp

# Predicted values of species_o

# Sepal.Width = 2

petal_length_cut_f | Predicted |        95% CI
----------------------------------------------
(0,994,2,48]       |      1.01 | [-0.03, 2.04]
(2,48,3,95]        |      2.00 | [ 0.97, 3.04]
(3,95,5,43]        |      2.36 | [ 1.33, 3.40]
(5,43,6,91]        |      3.00 | [ 1.96, 4.03]

# Sepal.Width = 2,2

petal_length_cut_f | Predicted |        95% CI
----------------------------------------------
(0,994,2,48]       |      1.01 | [-0.02, 2.04]
(2,48,3,95]        |      2.00 | [ 0.97, 3.03]
(3,95,5,43]        |      2.36 | [ 1.33, 3.39]
(5,43,6,91]        |      3.00 | [ 1.97, 4.03]

# Sepal.Width = 2,3

petal_length_cut_f | Predicted |        95% CI
----------------------------------------------
(0,994,2,48]       |      1.01 | [-0.02, 2.03]
(2,48,3,95]        |      2.00 | [ 0.97, 3.03]
(3,95,5,43]        |      2.36 | [ 1.33, 3.39]
(5,43,6,91]        |      3.00 | [ 1.97, 4.03]

# Sepal.Width = 2,4

petal_length_cut_f | Predicted |        95% CI
----------------------------------------------
(0,994,2,48]       |      1.01 | [-0.02, 2.03]
(2,48,3,95]        |      2.00 | [ 0.97, 3.03]
(3,95,5,43]        |      2.36 | [ 1.33, 3.39]
(5,43,6,91]        |      3.00 | [ 1.97, 4.02]
```
……asoasf … for every level of the random effect. 

It would be great to get some help or a recommendation which models (other than clmm) could do this job.

Best, Luise

**Comment by LuiNov** [comment]
I also posted on stack (https://stackoverflow.com/questions/71333702/calculate-marginal-effects-for-ordinalclmm) and posted a link to this issue there.

**Comment by strengejacke** [comment]
Hi Luise,
the problem is that the package *ordinal* does not have a `predict()` method for models of class `clmm`. Thus, internally I only rely on package *emmeans* for `ordinal::clmm()` - and `emmeans()` does not handle random effects. 
Unfortunately, this issue cannot be resolved at the moment (unless the maintainers of package *ordinal*  provide a `predict.clmm()` method).
