### ISSUE TITLE
predicted probabilities different for ggeffect() vs. prediction() and Stata

### ISSUE THREAD

**Issue by sgenter1** [strengejacke/ggeffects#249]
Hi,

I'm attempting to calculate predicted probabilities for a logit model and noticed differences in results when comparing `ggeffect` on the one hand and `prediction` and Stata output on the other. The predicted values given by `prediction` and Stata line up, though the standard errors are apparently different, but `ggeffect`, `ggpredict`, and `ggemmeans` all give different predicted values compared to `prediction` and Stata (but they are the same among these functions). Do you know why this is happening? Is Stata or `ggeffects` correct, or is this a result of user error? Ideally, I would either be able to reproduce the results given by Stata using `ggeffects` or to better understand why one or the other is incorrect.

Kind regards.

``` r
suppressWarnings(suppressPackageStartupMessages({
  library(dplyr)
  library(prediction)
  library(ggeffects)
}))

# model
mod <- glm(vs ~ mpg + cyl + hp,
                family=binomial, data = mtcars)


# for the following commands, stata gives the following: 
# (code to reproduce results at the bottom of post) 

# glm vs mpg cyl hp, family(binomial) 
# margins, at(cyl = (4, 6, 8))

# |            Delta-method
# |     Margin   Std. Err.      z    P>|z|     [95% Conf. Interval]
# _at |
# 1  |   .7317152   .3783261     1.93   0.053    -.0097904    1.473221
# 2  |     .36381   .1229849     2.96   0.003      .122764    .6048561
# 3  |   .0622145   .1750529     0.36   0.722    -.2808829    .4053119


# with prediction(), predicted means match Stata
prediction(mod, at = list(cyl = c(4, 6, 8)))
#> Data frame with 96 predictions from
#>  glm(formula = vs ~ mpg + cyl + hp, family = binomial, data = mtcars)
#> with average predictions:
#>  cyl       x
#>    4 0.73172
#>    6 0.36381
#>    8 0.06221

# but se's do not
prediction(mod, at = list(cyl = c(4, 6, 8))) %>% 
  group_by(cyl) %>% 
  summarise(mean = mean(fitted),
            se = mean(se.fitted))
#> # A tibble: 3 x 3
#>     cyl   mean    se
#>   <dbl>  <dbl> <dbl>
#> 1     4 0.732  0.413
#> 2     6 0.364  0.287
#> 3     8 0.0622 0.184

# from reading your documentation and trying things out elsewhere, my
# understanding is that ggeffect is the closet thing to "margins" in this
# instance, but the results are different from Stata
ggeffect(mod, "cyl")
#> # Predicted probabilities of vs
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |      0.81 | [0.02, 1.00]
#>   6 |      0.23 | [0.03, 0.75]
#>   8 |      0.02 | [0.00, 0.69]

# ggpredict and ggemmeans give the same values in this case
ggpredict(mod, "cyl") 
#> # Predicted probabilities of vs
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |      0.81 | [0.02, 1.00]
#>   6 |      0.23 | [0.03, 0.75]
#>   8 |      0.02 | [0.00, 0.69]
#> 
#> Adjusted for:
#> * mpg =  20.09
#> *  hp = 146.69
ggemmeans(mod, "cyl")
#> Loading required namespace: emmeans
#> # Predicted probabilities of vs
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |      0.81 | [0.02, 1.00]
#>   6 |      0.23 | [0.03, 0.75]
#>   8 |      0.02 | [0.00, 0.69]
#> 
#> Adjusted for:
#> * mpg =  20.09
#> *  hp = 146.69



# # code to reproduce results in stata
# suppressWarnings(suppressPackageStartupMessages({
#   library(haven)
# }))
# 
# mtcars %>%
#   write_dta(here("mtcars.dta"))
# 
# use mtcars, clear
# glm vs mpg cyl hp, family(binomial)
# margins, at(cyl = (4, 6, 8))
```

<sup>Created on 2022-03-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
You usually won't see differences between `ggpredict()`, `ggeffect()` and `ggemmeans()` when you have only numerical predictors, because these are all held constant at their mean value. The difference arises when factors are included (see https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html).

I don't know much about Stata, but I think that you have marginal effects here, not predictions? See this vignette: https://strengejacke.github.io/ggeffects/articles/introduction_marginal_effects.html

Else, I guess the [_marginaleffects_](https://vincentarelbundock.github.io/marginaleffects/) package might be what comes close to what Stata is doing. It offers what ggeffects offers ("adjusted predictions"), but beyond can also compute (avaerage)  marginal effects and contrasts. 

Tagging @vincentarelbundock who knows Stata (and the equivalents in R) much better than me.

**Comment by strengejacke** [comment]
NB: If Stata really computes predicted _probabilities_, they're probably not doing well, when the CI has negative values, or values beyond 100% (see also https://strengejacke.github.io/ggeffects/articles/technical_stata.html).

**Comment by jolyphil** [comment]
Thanks a lot for the clarification! That's really useful. 

I now get the same estimates with the argument `grid.type = "counterfactual"` but the standard errors are still different. 

``` r
library(margins)
library(marginaleffects)
library(dplyr)

df <- mtcars

df$vs <- as.factor(df$vs)
df$am <- as.factor(df$am)

hp_values <- c(100, 200, 300)

m2 <- lm(mpg ~ am * hp * vs, data = df)

margins(
  m2,
  variables = "am",
  at = list(hp = hp_values)) |>
  summary() |>
  select(AME, SE)
#>    AME    SE
#>  4.386 1.789
#>  4.171 3.482
#>  3.955 6.713

marginaleffects(
  m2,
  variables = "am",
  newdata = datagrid(hp = hp_values,
                     grid.type = "counterfactual")) |> 
  group_by(hp) |> 
  summarize(across(c(dydx, std.error), mean))
#> # A tibble: 3 × 3
#>      hp  dydx std.error
#>   <dbl> <dbl>     <dbl>
#> 1   100  4.39      2.38
#> 2   200  4.17      4.18
#> 3   300  3.96      8.31
```

**Comment by vincentarelbundock** [comment]
> does `predictions` with `grid.type = "counterfactual"` also produce standard errors? Based on the link you posted above (which in turn links to here [vincentarelbundock/marginaleffects#216](https://github.com/vincentarelbundock/marginaleffects/issues/216) ), it seems like maybe not, but it looks like other times `predictions` will based on your examples above.

`grid.type="counterfactual"` will always produce estimates and standard errors **for individual predictions.** If you give 3 values to `margins(mod, at = list...))`, the `mtcars` is replicated 3 times and you get 96 observations, 96 predictions, and 96 standard errors. These are exactly the values you get from `predictions`.

Under-the-hood, Stata does exactly the same thing, but it only reports *average predictions* by taking the mean of the observation-level estimates. For standard errors, the computation is a little more involved. See here for an analogous issue with marginal effects: https://github.com/vincentarelbundock/marginaleffects/issues/226#issuecomment-1069087157

The [vincentarelbundock/marginaleffects#216](https://github.com/vincentarelbundock/marginaleffects/issues/216) issue refers to the standard error of the *Average* prediction, which is not yet supported by `marginaleffects::predictions()`. I do plan to implement this as soon as possible, but I can't give you a specific timeline.

> Third, is one method or the other generally going to be more "accurate"?

No, I don't think about this in terms of "accuracy". Personally, I prefer to work with two kinds of predictions:

1. Predictions at the Observed Values (the default in `marginaleffects::predictions`)
2. Predictions at Representative Values

Ultimately, it's the analyst's preference, and none of this is likely to make much difference in practice. It's just important to understand precisely what we are doing, and I think the vignette is useful in that regard:

https://vinentarelbundock.github.io/marginaleffects/articles/predictions.htmlc

> My instinct is always to attempt to replicate what Stata does since many of my colleagues use it and I need to be able to replicate their work, but is there an advantage to using a "3 row data grid" approach over the counterfactual approach? 

What Stata does here is kind of a hybrid of the two, replicating the full dataset many times. Frankly, I find this super weird, but to each its own. 

> Relatedly, will adding the `"counterfactual"` argument always replicate Stata/prediction?

As I said above, the counterfactual argument does *exactly* the same as Stata under the hood, so the answer is "yes": using the `aggregate()` function (or `dplyr::group_by`) to take the group-wise averages as I showed above should always give the same results as Stata. But again, standard errors are not yet available for "average counterfactual predictions."

**Comment by strengejacke** [comment]
> My instinct is always to attempt to replicate what Stata does

This is what I tried for a long time with SPSS, after switching from SPSS to R - until I realized, it's better to try to replicate R under SPSS, because in my experience, is SPSS or Stata that do stupid things you're not aware of (see my example above for Stata, or e.g. weighting data sets in SPSS to perform a regression analysis with weights - it took a long time to find out why SPSS and R results differ, because in SPSS, when you have missing values in your data, you should not use `WEIGHT BY .`, but rather `/REGWGT`, else results are wrong. Of course everybody (who used SPSS) thought that R was to blame, but actually it was SPSS's fault.

**Comment by strengejacke** [comment]
I don't doubt that. It's rather the difference in credibility accorded to Stata and SPSS on the one hand, and R on the other hand, and this is not always justified. R isn't wrong just because it's for free. :-) On the other hand, SPSS/Stata are not always right just because you spend an outrageous amount of money for them. ;-)

**Comment by sgenter1** [comment]
Thanks again. This has been very helpful.
