### ISSUE TITLE
Change color in ggeffects plot (one level)

### ISSUE THREAD

**Issue by lukasla** [strengejacke/ggeffects#252]
Hi! 

I would like to change the color for my plot that I made using the ggeffects::plot function. But I didn't find any option to do so. The following code for example does not work: 

library(sjlabelled)
data(efc)
efc$c172code <- as_label(efc$c172code)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)

dat <- ggpredict(fit, terms = "c12hour")
plot(dat,colors="red") #this does not change the color!!! 

Is there another way to do it? 

Thanks a lot! 
Lukas

**Comment by strengejacke** [comment]
Hm, that's strange. Even this doesn't work:

```r
plot(dat) + ggplot2::scale_color_manual(values = "red", aesthetics = "colour")
```

**Comment by annalenahendel** [comment]
Hey, I am having the same issue and have the newest developement version installed ...
Despite the color doesnt change I am getting the warning 'Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale'

Thank you, Lena

**Comment by strengejacke** [comment]
Have you tried this? This should install version 1.2.1.9.

```r
install.packages("ggeffects", repos = "https://strengejacke.r-universe.dev")
```

And this version should have fixed this issue:

``` r
library(ggeffects)
data(efc)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)

dat <- ggpredict(fit, terms = "c12hour")
plot(dat, colors = "red")
```

![](https://i.imgur.com/0AqjesE.png)

<sup>Created on 2023-04-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by annalenahendel** [comment]
Thank you so, so much it works now!  Just changing color settings in ggplot using '+ scale_color_manual(values = "red", aesthetics = "colour")' doesn't yet.

**Comment by strengejacke** [comment]
Yes, because for "single color" plots, no colour-aes is used. Instead, the `colour` argument for the geom is used.
