### ISSUE TITLE
Differences between outcomes for ggemmeans and emmeans

### ISSUE THREAD

**Issue by AnnePdM** [strengejacke/ggeffects#254]
I have been using the `ggeffects` package to create marginal effects and adjusted predictions. I have contented myself with the differences between the outcomes for `ggeffect`, `ggemmean` and `ggpredict`. I am creating a binary response multilevel model which is complex and is created with sensitive data so I have recreated the problem I am experiencing with a dataset in the public domain. My problem is two-fold:
1. I am finding that I get different predictions and confidence intervals when I use `ggemmeans` and `emmeans` (in the example I provide the difference is only in the confidence intervals). Why is this happening when the former is a wrapper round the latter?
2.  The reason I started making this comparison in the first place is that I want to be able to report the contrasts that can be extracted from `emmeans` using the command `contrast(emmeans(model, ....))`. Can this be done in `ggemmeans`? Is it even sensible to use the standard deviations from the `contrast(emmeans(model, ....))` command to construct confidence intervals around the `differences?`

Here is the code that I have written to recreate the problem described in 1. The model by the way, makes absolutely no sense, it was just data that could be used to illustrate the point

```
library(haven)
mlmdata <- read_dta("https://stats.idre.ucla.edu/stat/examples/imm/imm10.dta")

mlmdata <- mlmdata %>%
  mutate(homework.bin = ifelse(homework <= 1, 0, 1))
 
model <- glmer(homework.bin ~ factor(white) + ses + (1 | schid), family = binomial, data=mlmdata, 
              control = glmerControl(optimizer = "bobyqa", calc.derivs = FALSE, nAGQ=0))
summary(model)

ggemmeans <-  ggemmeans(model, c("white"), type = "fe", x.as.factor = TRUE) 
emmeans <- as.data.frame(emmeans(model, c("white"), type = "fe", transform = "response", x.as.factor = TRUE))
emmeans.contrast <- as.data.frame(contrast((emmeans(model, c("white"), type = "fe", transform = "response", x.as.factor = TRUE))))
```

**Comment by AnnePdM** [comment]
Thanks Daniel, I think you are right about versions. I have a shared workspace in my job and updating the packages is more difficult. However, I have now tried running the code below on my home computer. I have updated all the packages (and R and Rstudio) and am now confronted with another problem. When I run the code:

`pr1 <-  as.data.frame(ggemmeans(model, "white", type = "fe") )`

I get the following error. Any ideas?

```
Can't compute estimated marginal means, 'emmeans::emmeans()' returned an error.

Reason: non-numeric argument to mathematical function
You may try 'ggpredict()' or 'ggeffect()'.
```

**Comment by strengejacke** [comment]
This is an issue which is fixed in the current GitHub version of _ggeffects_.
Try
```r
library(devtools)
devtools::install_github("strengejacke/ggeffects")
```
and it should work.

**Comment by AnnePdM** [comment]
That works. Thanks!

Given that, at work, I struggle to update packages as freely as at home and that I plan to use the `contrast` function, is it safe to assume that the differences between `ggemmeans` and `emmeans` that previously existed was an issue with `ggemmeans` rather than `emmeans`? In other words, is it safe to use `emmeans` without updating the packages?

**Comment by strengejacke** [comment]
Yes, I think so.
