### ISSUE TITLE
Number of predictions from ggpredict()

### ISSUE THREAD

**Issue by GregHKim** [strengejacke/ggeffects#255]
Hello, thank you for the amazingly useful package! It could be a stupid question, but I was wondering how to get a larger number of predictions from the ggpredict() function. Based on the description of the function, I tried like:
ggpredict(m3, "x [sample = 30]", "y"), type = "re") 
However, it still gives me only 6 predictions for randomised x. 
Interestingly, I could decrease the number of predictions, e.g. ggpredict(m3, "x [sample = 3]", "y"), type = "re"), but cannot increase.. 
Is there any possible way to get more predictions?

**Comment by strengejacke** [comment]
I guess the data is there, it's just that the `print()` method only prints a fraction on the complete data frame. You can either use:
``` r
ggpredict(m3, "x [sample = 30]", "y"), type = "re") |> print(n = 100)
``` 
(vary the `n` argument) or
```r
ggpredict(m3, "x [sample = 30]", "y"), type = "re") |> as.data.frame()
```
to see all results.
