### ISSUE TITLE
Can't compute marginal effects- non-positive values not allowed for the 'Gamma' family

### ISSUE THREAD

**Issue by frustratedeggs** [strengejacke/ggeffects#257]
Hello Daniel,

I have run some hurdle GLMM models using glmmTMB with gamma distribution and log link to analyze cost data. To get marginal effects, I tried your ggeffects package using ggpredict() and ggeffect() functions. However, the ggpredict() worked well for GLMM but had errors of "cannot allocate vector of size 3.0Gb" which seems to be a memory issue. So I tried ggeffect and it showed "Can't compute marginal effects- non-positive values not allowed for the 'Gamma' family". I was wondering if ggeffect cannot work with two-part model with gamma distribution.

My second question is about calculating confidence intervals for predicted values produced by predict(). Since my Rstudio server doesn't have enough memory to run ggpredict(), I was thinking to get predicted values and SE from predict.glmmTMB() and estimate C.I. based on them. For conditional model only, I can see the C.I. is calculated as exp($fit+/-1.96*$SE.fit) when type="link". But I have no idea how the C.I. considering both ZI part and conditional part can be estimated based on two sets of predicted values and SEs from the conditional model and the ZI model. Could you advise how C.I. is calculated in ggpredict()?

Thank you!

**Comment by strengejacke** [comment]
Regarding the SE / CI for both conditional and zi-part, see docs:

> Thus, confidence intervals for type = "zero_inflated" are based on quantiles of simulated draws from a multivariate normal distribution (see also Brooks et al. 2017, pp.391-392 for details).

_Brooks ME, Kristensen K, Benthem KJ van, Magnusson A, Berg CW, Nielsen A, et al. glmmTMB Balances Speed and Flexibility Among Packages for Zero-inflated Generalized Linear Mixed Modeling. The R Journal. 2017;9: 378–400._

I have adopted the approach described in the Brooks et al. paper.

**Comment by frustratedeggs** [comment]
Thank you for your reply! Following up on my first question, I was also wondering if ggeffect() cannot work with two-part model with gamma distribution.

**Comment by strengejacke** [comment]
`ggeffect()` calls `effects::Effect()`. You could try that function directly and see whether that model is supported.
