### ISSUE TITLE
Differences between ggpredict and ggemmeans (mixed-effects models and CI calculation)

### ISSUE THREAD

**Issue by jukicivan** [strengejacke/ggeffects#258]
Dear Daniel,

I briefly explained my issue [here](https://github.com/strengejacke/ggeffects/issues/126), but you kindly suggested to open a new issue about this, so here it goes.

Namely, I have the same issue some other people had with missing confidence intervals after using `ggpredict` on the lmer-generated model. However, I actually used `"type = fixed"` (i.e., default behaviour of the function) because I'd be fine with predictions on the population-level that do not account for the random effect variances. Unfortunately, while doing so, I realised that I'm missing confidence intervals (CIs) for some of the groups. In one instance, I'm missing CIs for both groups (i.e., levels of the predictor). 

Now, while preparing some data for you here, I think I stumbled upon a source of this issue which is rather weird to me. Because it would be quite length for me to expand on it here, I'll attach the script and the data.

Briefly, I realised that I'm able to get confidence intervals while using `ggpredict` function and specifying all the "terms" I'm interested in. In contrast, everything seems to be working with `ggemmeans`. After preparing the dataset to illustrate this issue, I realised that simply renaming one variable (ie.., `Emotional Stability` to ES), resolved all the issues, and `ggpredict` calculated everything, and even aligned (almost perfectly) with the output from `ggemmeans`. Similarly, renaming the mentioned variable to `emotional_stability` instead, also didn't cause any issues. Now, this creates three questions for me.

1) Why renaming the variable makes the difference? I really tried my best to get down to this (I spent hours on it), but I couldn't find the source of the issue. Do you have any ideas?

2) The effects returned by `ggpredict` are conditional effects (i.e. these are conditioned on certain (reference) levels of factors), whereas `ggemmeans` returns marginal means, since the effects are “marginalised” (or “averaged”) over the levels of factors. Now, looking at the outputs of both `ggpredict` and `ggemmeans`, one can appreciate that both functions give the same result (well, almost the same, as outlined [here](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html)) as long as we specify all the variables on interest with `terms` argument. In this regard, specifying all the variables included in the model leads to identical results from these two functions when `type = "fixed"` is used, at least. Does this make sense? If so, perhaps that could be added in the description or documentation. 

3) More importantly, but still related to the question 2 above, I'm wondering about the behaviour of these two functions (and their differences) once we specify all the variables with `terms` argument, but also now choose `type = "random"`. Based on the above definition, something should be "averaged across both fixed and random (levels of the) factors. I would really appreciate if you could expand on this and point me to the obvious differences which explain different CIs between `ggpredict` and `ggemmeans` when `type = "random"` is used.

Thank you for your time!

[Data-Script-GH.zip](https://github.com/strengejacke/ggeffects/files/8848943/Data-Script-GH.zip)

**Comment by strengejacke** [comment]
At 1) Should be fixed in #314. The column name in the model-matrix contained backticks due to the white space in the column name, which no longer matched the term name. I strongly recommend using "valid" variable names, as any special or white space character can lead to unintended results.

At 2) The "averaging" across levels only applies to **non-focal** categorical variables (that are not specified in `terms`). If all non-focal terms are numeric, the mean is used both by `ggpredict()` and `ggemmeans()`. I added more details to the comparison-vignette to make this clearer.

At 3) I _think_ the difference is that `predict()` has a `re.form` argument which can be used to account for random effects, which emmeans doesn't. This may explain the slightly different CIs.
