### ISSUE TITLE
Change in ggpredict output tables

### ISSUE THREAD

**Issue by DrAngelaT** [strengejacke/ggeffects#259]
Hi There! I need a little sanity check since my code worked this morning and not this afternoon, and my data are the same, but something has changed.

I am using ggpredict() to plot model fits. The code refers to the output from ggpredict as x, predicted, conf.low and conf.high, and it plotted just fine:
[line_mod1 <- ggpredict(mod1, c("Contiguousness"))
geom_ribbon(data = line_mod1, aes(x = x, ymin = conf.low, ymax = conf.high), alpha = 0.2) +
  geom_line(data = line_mod1, aes(x = x, y = predicted))]
Now, when I try to run it,  those aren't recognized. When I call line_mod1 the columns headers are Contiguousness  Predicted and 95% CI

What has happened? Is there a way to get the previous headers back or do I have to extract the upper and lower bounds and recode? Thank you!

**Comment by strengejacke** [comment]
Do you have a small reproducible example?

**Comment by DrAngelaT** [comment]
Of course! I'm also included a list of the loaded packages since that is the thing most likely to have changed between when the output showed conf.low and conf.high.

(.packages())
 [1] "sjmisc"       "sjPlot"       "usethis"      "remotes"      "sjlabelled"  
 [6] "flextable"    "ggeffects"    "coefplot"     "modelsummary" "lmerTest"    
[11] "corrplot"     "ggplot2"      "mgcv"         "nlme"         "lme4"        
[16] "Matrix"       "MASS"         "car"          "carData"      "readxl"      
[21] "readr"        "dplyr"        "plyr"         "stats"        "graphics"    
[26] "grDevices"    "utils"        "datasets"     "methods"      "base"  

Depend <- c(2, 4, 6, 8, 10, 2, 4, 6, 8, 10, 2, 4, 6, 8, 10, 2, 4, 6, 8, 10)
Independ <- c(1, 25, 50, 100, 200, 1, 25, 50, 100, 200, 1, 25, 50, 100, 200, 1, 25, 50, 100, 200)
Rand <- c(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5)
toy = data.frame(Independ, Depend, Rand)
mod_toy <- lme4::lmer(Depend ~ Independ + (1|Rand), data = toy, na.action=na.exclude)
line_toy <- ggpredict(mod_toy, c("Independ"))
line_toy
