### ISSUE TITLE
4-way interaction visualization details 

### ISSUE THREAD

**Issue by ncz11** [strengejacke/ggeffects#274]
Hi!

First of, many thanks for an amazing package. 
I have a novice question regarding the Panel Plots for more than three Terms.  Following on the example in the vignette:
a.  Is there a way to display just the value of neg_c_7- say 8—instead of having neg_c_7=8? 
b.  Is there a way to display the y-axis label just once, instead of for each panel?

**Comment by strengejacke** [comment]
The ways of customizing plots are described in these two vignettes:
https://strengejacke.github.io/ggeffects/articles/introduction_plotmethod.html
https://strengejacke.github.io/ggeffects/articles/introduction_plotcustomize.html

Any further customization needs to be done manually, I'm afraid, i.e. you have to build your plot from scratch using ggplot2.
