### ISSUE TITLE
Getting dataframe with original variable names

### ISSUE THREAD

**Issue by fredcallaway** [strengejacke/ggeffects#275]
I want to produce a dataframe of predicted effects with the same column names as in my input dataframe, i.e. without renaming things as x, y, group, facet, panel. I figured I could write such a function myself using `get_x_title` etc... but I can't figure out how to get facet and panel titles. It would be nice if there was an option to disable relabeling altogether.

**Comment by strengejacke** [comment]
You can use `as.data.frame(..., terms_to_colnames = TRUE)` now to get the term names as column names now:

``` r
library(ggeffects)
data(efc)
m <- lm(barthtot ~ c12hour + neg_c_7 * c161sex + e42dep, data = efc)
p1 <- ggpredict(m, terms = c("neg_c_7", "c161sex", "e42dep"))

colnames(p1)
#> [1] "x"         "predicted" "std.error" "conf.low"  "conf.high" "group"    
#> [7] "facet"
colnames(as.data.frame(p1, terms_to_colnames = TRUE))
#> [1] "neg_c_7"   "predicted" "std.error" "conf.low"  "conf.high" "c161sex"  
#> [7] "e42dep"
```

<sup>Created on 2023-02-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
