### ISSUE TITLE
Minor addition to ggpredict documentation

### ISSUE THREAD

**Issue by clayford** [strengejacke/ggeffects#276]
In the "Holding covariates at constant values" section of the ggpredict documentation it says, 

> "Numeric values are set to the mean (unless changed with the condition or typical-argument), factors are set to their reference level (may also be changed with condition) and character vectors to their mode (most common element)."

I recommend updating this to include behavior for integers: 

> "Numeric values are set to the mean (unless changed with the condition or typical-argument), **integer values are set to their median**, factors are set to their reference level (may also be changed with condition) and character vectors to their mode (most common element)."

I recommend this change since the `.typical_value` function does the following for integers.

```
if (is.integer(x)) {
        out <- stats::median(x, na.rm = TRUE)
    }

```

Thanks for all your work on this package!
Clay Ford

**Comment by strengejacke** [comment]
Thanks!
