### ISSUE TITLE
examples for `hypothesis_test()` are failing

### ISSUE THREAD

**Issue by strengejacke** [strengejacke/ggeffects#290]
See https://github.com/strengejacke/ggeffects/actions/runs/4250891044/jobs/7392551834

@vincentarelbundock any ideas why this happens? Is it because examples only work interactively in this case?

**Comment by vincentarelbundock** [comment]
Not 100% sure, but that's possible. I don't know how your wrapper works, but if you are calling `hypotheses()`, then the function needs to extract the original call and data, modify it, and re-evaluate. Sometimes this fails in nested function calls or weird environments. 

Also just released 0.10.0, which may improve things (not sure if the mirror that Github Actions is using was updated yet).

**Comment by strengejacke** [comment]
I'm calling `predictions()`, `slopes()`, `avg_predictions()` and `avg_slopes()`, with the `hypothesis` argument. But tests don't fail, I'm still trying to find the reason. I guess it's an environment issue in this code example:

```r
# passing a `ggeffects` object
# pred <- ggpredict(m, "c172code")
# hypothesis_test(pred)
```

but not sure yet...

**Comment by vincentarelbundock** [comment]
sorry, I don't know.
