### ISSUE TITLE
Error hypothesis_test categorial variable

### ISSUE THREAD

**Issue by fjochum1** [strengejacke/ggeffects#292]
Hello, 

First of all I would like to thank you for your incredible package that I use for my complex regression models. I already love your new hypothesis_test() function. Unfortunately I have a problem when using it with categorical variables.

I have a mixed linear regression model :
lmer(x ~ sex * age + (1 | Cancer)) 

The function works very well for the continuous variable "age" :

> hypothesis_test(lm_mixed, "age")

Slope |         95% CI |      p
-------------------------------
-5.07 | [-5.49, -4.65] | < .001

However, for the sex (Women - Men) variable I have an error that appears: 

> hypothesis_test(lm_mixed, "sex")

Error: The `by` argument must be either:
  
  1. Character vector in which each element is part of: sex, age, Cancer
  
  2. A data frame with a `by` column of labels, and in which all other columns are elements of:
  sex, age, Cancer
  
  It can sometimes be useful to supply a data frame explicitly to the `newdata` argument in order to
  be able to group by different columns.

It works very well for the interaction also (hypothesis_test(lm_mixed, c=('age','sex'), test = NULL).  It is only when I want to use if for a single categorial variable. I'm not sure I understand what I'm doing wrong...

Thank you very much for your help !

**Comment by strengejacke** [comment]
``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)
d <- nlme::Orthodont
m <- lmer(distance ~ age * Sex + (1 | Subject), data = d)

hypothesis_test(m, "age")
#> # Linear trend for age
#> 
#> Slope |       95% CI |      p
#> -----------------------------
#> 0.66  | [0.54, 0.78] | < .001

hypothesis_test(m, "Sex")
#> # Pairwise comparisons
#> 
#> Sex         | Contrast |       95% CI |     p
#> ---------------------------------------------
#> Male-Female |     2.32 | [0.81, 3.83] | 0.003

hypothesis_test(m, "age", test = NULL)
#> # Linear trend for age
#> 
#> Slope |       95% CI |      p
#> -----------------------------
#> 0.66  | [0.54, 0.78] | < .001

hypothesis_test(m, "Sex", test = NULL)
#> Sex    | Predicted |         95% CI |      p
#> --------------------------------------------
#> Male   |     24.97 | [24.00, 25.93] | < .001
#> Female |     22.65 | [21.49, 23.81] | < .001
```

<sup>Created on 2023-02-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
thanks! Should be fixes. Wait a few minutes until r-universe has updated the latest commit, then run `ggeffects::install_latest()` and you should get the update to version 1.2.0.4 - that version should include the fix.

**Comment by fjochum1** [comment]
Amazing ! Thanks a lot !
