### ISSUE TITLE
Problemu with installing glmmTMB

### ISSUE THREAD

**Issue by ilonanenko** [strengejacke/ggeffects#301]
Hi, i can not install glmmTMB i continue getting a massage:

Error in library(package, pos = pos, lib.loc = lib.loc, character.only = TRUE,  : 
  there is no package called ‘glmmTMB’

Is there ani solution for that? 

I am using R version 4.2.3 on Mac

**Comment by strengejacke** [comment]
I'm not sure this is a ggeffects related issue. Maybe you ask at the glmmTMB repository?
