### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by cdcrabtree** [strengejacke/ggeffects#31]
Hi @strengejacke. I'm currently moving my way through your JOSS review. I can't seem to find any information about how the function of the software is verified. Is this done through either manual or automatic tests? My apologies if this information is listed in documentation or paper, but I couldn't find it in either. Thanks!

**Comment by strengejacke** [comment]
Hi Charles,
thanks for reviewing my paper! From my experience from a former paper submission, examples (in docs), and a test-suite are recommended. You can find all tests for my package here:
https://github.com/strengejacke/ggeffects/tree/master/tests
I don't think tests have to be explicitely mentioned in the paper, but probably @leeper as assigned editor may clarify this.

**Comment by leeper** [comment]
Tests don't need to be explicitly mentioned in the paper, but the documentation should have executable examples and there should be a `/tests` folder with automatically checked tests.

**Comment by strengejacke** [comment]
Ok, thanks! That is already there. Examples in the documentation and vignettes are all executable, automatic tests that check if function arguments work as intended are in the `/tests`-folder.
