### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by cdcrabtree** [strengejacke/ggeffects#32]
It would be nice to include in the README file some discussion of what users should do if they need support.

**Comment by strengejacke** [comment]
Thanks! I have added a paragraph where I describe how they can get support. Furthermore, I moved this paragraph up to the beginning of the README. so it's more apparent to the user. After the examples, there's a specific "CONTRIBUTION" section, where I also describe how users can contribute to the package.

Is this sufficient, or do you like more details on how users can get support?
