### ISSUE TITLE
X value seemingly transformed for partial residuals plot

### ISSUE THREAD

**Issue by Deleetdk** [strengejacke/ggeffects#347]
Reprex:

``` r
#partial residuals with bounded predictor

library(ggeffects)
library(tidyverse)
library(car)
#> Loading required package: carData
#> 
#> Attaching package: 'car'
#> The following object is masked from 'package:dplyr':
#> 
#>     recode
#> The following object is masked from 'package:purrr':
#> 
#>     some

#make up some data
set.seed(1)
ex_data = tibble(
  pred_bounded = runif(n = 200, min = 0, max = 1),
  pred_normal = rnorm(200),
  y = pred_bounded * 1 + pred_normal + rnorm(200)
)

#fit a model
ex_fit = lm(y ~ pred_bounded + pred_normal, data = ex_data)

#pred data
ex_fit_preds = ggpredict(ex_fit, terms = c("pred_bounded"))

#plot partial residuals
ex_fit_preds %>% plot(residuals = T) + scale_x_continuous(breaks = seq(-1, 1, by = .2))
```

![](https://i.imgur.com/E1Lfy9c.png)

``` r

#X values are outside of the 0-1 range??

#does not happen with car package version
crPlot(ex_fit, variable = "pred_bounded")
```

![](https://i.imgur.com/zJsF9t3.png)

<sup>Created on 2023-07-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
That's probably due to the jitter. Try the `jitter` argument in the `plot()` method.

**Comment by Deleetdk** [comment]
Wow. That seems like a very bad default setting! You are right. Here's a full example:

``` r
#partial residuals with bounded predictor

library(ggeffects)
library(tidyverse)
library(car)
#> Loading required package: carData
#> 
#> Attaching package: 'car'
#> The following object is masked from 'package:dplyr':
#> 
#>     recode
#> The following object is masked from 'package:purrr':
#> 
#>     some

#make up some data
set.seed(1)
ex_data = tibble(
  pred_bounded = runif(n = 200, min = 0, max = 1),
  pred_normal = rnorm(200),
  y = pred_bounded * 1 + pred_normal + rnorm(200)
)

#fit a model
ex_fit = lm(y ~ pred_bounded + pred_normal, data = ex_data)

#pred data
ex_fit_preds = ggpredict(ex_fit, terms = c("pred_bounded"))

#plot partial residuals
ex_fit_preds %>% plot(residuals = T) +
  scale_x_continuous(breaks = seq(-1, 1, by = .2))
```

![](https://i.imgur.com/oJRBRye.png)

``` r

#X values are outside of the 0-1 range??

#caused by jitter??!
ex_fit_preds %>% plot(residuals = T, jitter = F) +
  scale_x_continuous(breaks = seq(-1, 1, by = .2))
```

![](https://i.imgur.com/Cb0iE0q.png)

I think it's a very bad default setting because:

1. Jitter is technically error in the plots, showing unreal data variation. There are better methods for showing overplotting, such as alpha < 1 (already in use) or other geoms (e.g. `geom_bin2d`).
2. Users don't expect jitter to be added by default, and they most likely don't want it. I asked another good R coder about this issue, and he was also negatively surprised.
3. Since jitter is random, the plots are not reproducible by default, making studies published with them also not reproducible. One can avoid this by setting a lot of seeds (cumbersome), running the code to produce plots only as a single once-through script with an initial seed,  or using a default seed in an argument.

Example of rerunning plots:

![image](https://github.com/strengejacke/ggeffects/assets/6759913/51a618dc-f155-4e7d-a54b-535b5feb52bb)


I would like to request then that the default be changed to `jitter=0`.

<sup>Created on 2023-07-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Yes, maybe you're right. I'm rarely adding data points to the plots, so this issue did not really catch my attention.
