### ISSUE TITLE
ggpredict fails with one term when data used for modelling was a tibble

### ISSUE THREAD

**Issue by see24** [strengejacke/ggeffects#354]
My input data is a tibble and I was getting the below error message when trying to get predictions with only one term. An easy enough workaround was to convert to a data.frame before modelling. 

It looks like the issue is that `terms[2]` returns NA when terms is only length 1, when subsetting a data.frame this returns NULL but for a tibble it throws this error. 

If you changed [this line](https://github.com/strengejacke/ggeffects/blob/b6245408094abef0fffe6e558eb82f74e349cfd9/R/ggpredict.R#L654) to 
`original_model_frame <- as.data.frame(model_frame)` I think it would solve this but not sure if there is a better spot to do that.
 
``` r
library(ggeffects)
library(tibble)

mtcars_tbl <- as_tibble(mtcars)
fm2 <- lm(mpg ~ cyl + disp, mtcars_tbl)
ggpredict(fm2, terms = "cyl")
#> Error in `original_model_frame[[terms[2]]]`:
#> ! Can't extract column with `terms[2]`.
#> ✖ Subscript `terms[2]` must be a location, not a character `NA`.
#> Backtrace:
#>      ▆
#>   1. └─ggeffects::ggpredict(fm2, terms = "cyl")
#>   2.   └─ggeffects:::ggpredict_helper(...)
#>   3.     └─ggeffects:::.post_processing_predictions(...)
#>   4.       └─ggeffects:::.add_labels_to_groupvariable(...)
#>   5.         ├─sjlabelled::get_labels(...)
#>   6.         ├─original_model_frame[[terms[2]]]
#>   7.         └─tibble:::`[[.tbl_df`(original_model_frame, terms[2])
#>   8.           └─tibble:::tbl_subset2(x, j = i, j_arg = substitute(i))
#>   9.             └─tibble:::vectbl_as_col_location2(...)
#>  10.               ├─tibble:::subclass_col_index_errors(...)
#>  11.               │ └─base::withCallingHandlers(...)
#>  12.               └─vctrs::vec_as_location2(j, n, names, call = call)
#>  13.                 └─vctrs:::result_get(...)
#>  14.                   └─rlang::cnd_signal(x$err)
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Which version of _ggeffects_ are you using?
