### ISSUE TITLE
Adding ggplot2 functionality to ggeffects plot() fails when not setting "terms" 

### ISSUE THREAD

**Issue by lukasla** [strengejacke/ggeffects#355]
Hi, 

This is a minor thing but bugged me a while today because I couldn't figure out what was wrong. Maybe something to fix, to avoid that others also spend time on trying to 'solve' an issue that can be easily avoided (or add the 'issue' to your ggeffects website that people know). 

The issue: ggplot2 plot functions (such as labs()) cannot be added to a ggeffects-plot if 'term' was not set explicitly in the ggpredict function. 

Thanks a lot for your hard work! 
Lukas 

Here is an example (taken from your example from the website and slightly changed to reproduce the issue): 

library(ggeffects)
library(ggplot2)

data(mtcars)

#run a model
m <- lm(mpg ~ gear, data = mtcars)

#############################################
#### **this below works (with type specified )**
dat <- ggpredict(m, terms = c("gear"))

# plot with labs added is produced
plot(dat)+
  labs(
    x = "Number of forward gears",
    y = "Miles/(US) gallon",
    title = "Predicted mean miles per gallon"
  )

###############################################
###**this doesn't work (with type unspecified and automatically picked )**
dat <- ggpredict(m)

#code fails to produce a plot because labs cannot be added .
plot(dat)+
  labs(
    x = "Number of forward gears",
    y = "Miles/(US) gallon",
    title = "Predicted mean miles per gallon"
  )

**Comment by strengejacke** [comment]
When `term` is not specified, a list of plots (one per model predictor) is created, and you cannot add layers to a plot _list_.

Thus, you need to do `plot(dat)[[1]] + ...`. However, for just one plot, I could simply return that plot instead of wrapping it into a list.
