### ISSUE TITLE
`marginaleffects` 0.14.0 breaking change

### ISSUE THREAD

**Issue by vincentarelbundock** [strengejacke/ggeffects#363]
I apologize for this, but the next release of `marginaleffects` includes a small breaking change, which interferes with `ggeffects` tests: Row order has changed for some model objects. We now get more consistent alphabetical sort for rows.

I think that this is probably what explains the failing tests below. They seem like hard-coded snapshot-style tests, where numeric values stay similar but the order has changed.

Sorry again for the trouble.

```r
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-hypothesis_test.R:90:7'): hypothesis_test, categorical, pairwise ──
    out$Contrast (`actual`) not equal to c(...) (`expected`).
    
         actual | expected               
     [1] 0.420  - -0.205   [1]           
     [2] -0.205 - 0.067    [2]           
     [3] -0.153 - 0.420    [3]           
     [4] 0.067  - -0.153   [4]           
     [5] 0.119  | 0.119    [5]           
     [6] -0.625 - 0.272    [6]           
     [7] -0.573 - 0.625    [7]           
     [8] -0.353 - 0.052    [8]           
     [9] -0.301 - 0.324    [9]           
    [10] 0.052  - 0.353    [10]          
     ... ...      ...      and 5 more ...
    ── Failure ('test-hypothesis_test.R:99:7'): hypothesis_test, categorical, pairwise ──
    out$groups (`actual`) not identical to c(...) (`expected`).
    
         actual                | expected                          
     [1] "control-treatment"   - "control-control"   [1]           
     [2] "control-control"     | "control-control"   [2]           
     [3] "control-treatment"   | "control-treatment" [3]           
     [4] "control-control"     - "control-treatment" [4]           
     [5] "control-treatment"   | "control-treatment" [5]           
     [6] "treatment-control"   - "control-control"   [6]           
     [7] "treatment-treatment" - "control-treatment" [7]           
     [8] "treatment-control"   - "control-treatment" [8]           
     [9] "treatment-treatment" - "control-treatment" [9]           
    [10] "control-treatment"   | "control-treatment" [10]          
     ... ...                     ...                 and 5 more ...
    ── Failure ('test-hypothesis_test.R:113:7'): hypothesis_test, categorical, NULL ──
    out$Predicted (`actual`) not equal to c(0.0559, 0.2611, -0.0107, -0.364, 0.2087, -0.0628) (`expected`).
    
      `actual`: 0.056 -0.364  0.261  0.209 -0.011 -0.063
    `expected`: 0.056  0.261 -0.011 -0.364  0.209 -0.063
    ── Failure ('test-hypothesis_test.R:117:7'): hypothesis_test, categorical, NULL ──
    out$groups (`actual`) not identical to structure(...) (`expected`).
    
        actual      | expected       
    [1] "control  " | "control  " [1]
    [2] "treatment" - "control  " [2]
    [3] "control  " | "control  " [3]
    [4] "treatment" | "treatment" [4]
    [5] "control  " - "treatment" [5]
    [6] "treatment" | "treatment" [6]
```

**Comment by vincentarelbundock** [comment]
The next version is available in this branch:

```r
remotes::install_github("vincentarelbundock/marginaleffects@0_14_0")
```

**Comment by strengejacke** [comment]
Thanks, will look into this. I guess, following tests might also be affected:

- test-print_hypothesis_test.R
- test-print_hypothesis_test-ordinal.R

These snapshots are not considered during revdep checks.

**Comment by strengejacke** [comment]
What's your schedule for submitting _marginaleffects_? I'm currently on vacation and not be able to work much on this.

**Comment by vincentarelbundock** [comment]
I'm very sorry, it's already on CRAN. I should really have given you a heads-up, especially in summer like that. Apologies!

Peace offering: This PR should solve all the failing tests in `test-hypothesis_test.R` https://github.com/strengejacke/ggeffects/pull/364 

When I run the test suite locally, I don't get other errors.

**Comment by strengejacke** [comment]
> I'm very sorry, it's already on CRAN.

😄  ok, I didn't get a notification yet, so it's probably not too urgent.

I remember I made some effort to extract "cleaned" parameter names for those cases where _marginaleffects_ returns `b1` etc. - see this vignette:

https://strengejacke.github.io/ggeffects/articles/introduction_comparisons.html

And I think some of the edge cases are covered by snapshot tests:
https://github.com/strengejacke/ggeffects/blob/master/tests/testthat/_snaps/print_hypothesis_test.md

Regarding the vignette, see [this example](https://strengejacke.github.io/ggeffects/articles/introduction_comparisons.html#does-difference-between-two-levels-of-episode-in-the-control-group-differ-from-difference-of-same-two-levels-in-the-treatment-group), where I'm relying on the order how coefficients are returned by `predictions()`. If this isn't affected at all, only fixing the one test file should be indeed enough.

**Comment by strengejacke** [comment]
I think these are more breaking changes. The following example returns contrasts on the odds ratios, now on the link scale:

``` r
library(marginaleffects)
library(ggeffects)


set.seed(123)
dat <- data.frame(
  outcome = rbinom(n = 100, size = 1, prob = 0.35),
  var_binom = as.factor(rbinom(n = 100, size = 1, prob = 0.2)),
  var_cont = rnorm(n = 100, mean = 10, sd = 7),
  groups = sample(letters[1:4], size = 100, replace = TRUE)
)

m <- glm(outcome ~ var_binom * var_cont + groups,
  data = dat, family = binomial()
)

grid <- ggeffects::data_grid(m, "var_binom")
predictions(
  m,
  by = "var_binom",
  newdata = grid,
  hypothesis = "pairwise",
  transform_post = "exp"
)
#> 
#>   Term Estimate Std. Error      z Pr(>|z|)   S  2.5 % 97.5 %
#>  0 - 1  -0.0133      0.108 -0.123    0.902 0.1 -0.225  0.198
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

<sup>Created on 2023-08-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I guess it requires a careful revision of how tests results changed, and which of those breaking changes just require fixing tests, or revising code.

**Comment by vincentarelbundock** [comment]
Very sorry about this. The `transform_post` argument has been renamed to `transform` since version 0.11.0. I think some backward compatibility code was blown up by a refactor in the latest version. Totally slipped by me.

This commit should return results back to the proper scale: https://github.com/strengejacke/ggeffects/pull/364/commits/bdbde11cf53ce7b6955901c392cee466da1994d3
