### ISSUE TITLE
New issue possibly due to changes in **emmeans**

### ISSUE THREAD

**Issue by rvlenth** [strengejacke/ggeffects#366]
The downstream CRAN checks for my submission of an update to **emmeans** reveals some failures in the test scripts for **ggeffects**. I don't understand what those failures are, as the file `testthat` file(s) seem to have changed and what I think is the same code as tested runs the same with both the old and new versions of **emmeans**.  

Here is the summary of the tests:
[summary.txt](https://github.com/strengejacke/ggeffects/files/12361520/summary.txt)

One possible source of error is the fact that I changed the `vcov()` function so that it returns only covariances of the *displayed* estimates in a nested model.

I would appreciate it if you would install the updated emmeans from https://github.com/rvlenth/emmeans and let me know what problems come up?

**Comment by strengejacke** [comment]
Looks like test failures are false positive and related to #363. No problems with _emmeans_.

**Comment by rvlenth** [comment]
Many thanks!

Russ

On Aug 17, 2023, at 2:41 AM, Daniel ***@***.***> wrote:

﻿

Looks like test failures are false positive and related to #363<https://github.com/strengejacke/ggeffects/issues/363>. No problems with emmeans.
