### ISSUE TITLE
`ggeffects` 1.3.0 displays predictions but no raw data for a generalised mixed-effect model

### ISSUE THREAD

**Issue by marcoplebani85** [strengejacke/ggeffects#372]
Hello! I cannot get `ggeffects` 1.3.0 to display both the predictions for a generalised mixed-effect model and the data used to parametrise the model. Reproducible example:

```
RIKZ <- read.csv(text = RCurl::getURL("[https://raw.githubusercontent.com/marcoplebani85/datasets/master/RIKZ.csv")](https://raw.githubusercontent.com/marcoplebani85/datasets/master/RIKZ.csv%22))
RIKZ$Exposure <- as.factor(RIKZ$Exposure)
mem1 <- glmmTMB(Richness ~ NAP+Exposure + (1 | Beach), family="poisson", data = RIKZ, REML=T)
```
I can easily represent the model predictions as follows:
```
plot(ggpredict(mem1, terms = c("NAP", "Exposure")))
```
Adding `rawdata=T `doesn't add the observations to the graph, giving the message **"Raw data not available."** This is an issue I have had in other instances (see, for example: https://github.com/strengejacke/ggeffects/issues/370). For models with a single fixed-effect predictor I can work around this issue with `geom_point()`, but for some reason this doesn't work for mixed-effect models with multiple fixed-effect predictors:
```
plot(ggpredict(mem1, terms = c("NAP", "Exposure"))) +
geom_point(data=RIKZ, # observed data
           aes(y=Alga_length, x=Depth, shape=Exposure))
```
The error I get is:
```
Error in `geom_point()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 3rd layer.
Caused by error in `.data[["group_col"]]`:
! Column `group_col` not found in `.data`.
```
The problem is not `glmmTMB` because I have the same issue with linear models with multiple predictors in `lm()`. This situation is very similar to the one addressed here: https://stackoverflow.com/questions/55151771/plot-poisson-mixed-models-with-ggplot2/56170574 but for some reason that solution doesn't work for me.

The only solution I found so far is as follows:
```
pr <- as.data.frame(predicted.richness)
pr$Exposure <- as.factor(pr$group)
ggplot() +
  geom_ribbon(data=pr, 
              aes(x=x,ymin = conf.low, ymax = conf.high, group=group), 
              fill="grey", alpha = 0.5) +
  geom_line(data=pr, aes(x=x,y=predicted, linetype=Exposure)) +
  geom_point(data = RIKZ, aes(y = Richness, x = NAP, shape = Exposure)) +
  scale_shape_manual(values = c(1,4,2))
```
It is still a fairly tidy solution, but not as straightforward as `plot(ggpredict(mem1, terms = c("NAP", "Exposure")), rawdata=T)`. Any feedback is appreciated!

Best

Marco

**Comment by strengejacke** [comment]
This works for me:

``` r
library(ggeffects)
library(ggplot2)
library(glmmTMB)
RIKZ <- read.csv(text = RCurl::getURL("https://raw.githubusercontent.com/marcoplebani85/datasets/master/RIKZ.csv"))
RIKZ$Exposure <- as.factor(RIKZ$Exposure)
mem1 <- glmmTMB(Richness ~ NAP+Exposure + (1 | Beach), family="poisson", data = RIKZ, REML=T)

plot(ggpredict(mem1, terms = c("NAP", "Exposure")), add.data = TRUE)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/ZSm5EeY.png)

There was a bug in version 1.3.0, so you may need to update to the current dev-version: `ggeffects::install_latest()`, and then retry your example.

**Comment by marcoplebani85** [comment]
Thanks! I updated the package with `ggeffects::install_latest()`. If I run the code in R version 4.3.1 (2023-06-16) it works correctly displaying both data and model predictions, **but** if I run the code in RStudio (the latest version: 2023.06.1+524) the problem persists. For completeness, I am working on a 2014 Apple Mac mini running MacOS Monterey version 12.6.1 (21G217)

**Comment by strengejacke** [comment]
I wonder what this could have to do with RStudio? Maybe you have different package directories? What does `packageVersion("ggeffects")` return on RStudio?

**Comment by marcoplebani85** [comment]
It is puzzling. 
```
> packageVersion("ggeffects")
[1] ‘1.3.0.7’
```
Same version in R and RStudio.

**Comment by strengejacke** [comment]
Strange. I tested with VSCode and the latest RStudio (2023.06.2-561), and it works fine.

![image](https://github.com/strengejacke/ggeffects/assets/26301769/4c1be5aa-c618-487c-814e-daabb91def60)

**Comment by marcoplebani85** [comment]
After making me lose my mind for the past couple of days, this issue seems to have fixed itself. I don't have any problems with the code running on RStudio anymore. This is the weirdest thing.

**Comment by strengejacke** [comment]
Thanks, I'm closing this then. Feel free to re-open if you find any issues again.
