### ISSUE TITLE
How to get t value of the two-way interaction in linear mixed-effect model?

### ISSUE THREAD

**Issue by zhaoliang0302** [strengejacke/ggeffects#390]
Hi, I'm currently researching linear mixed-effects models and need to calculate t-values for two-way Interactions. Could you please provide guidance on using the "ggeffect" package for obtaining t-values in two-way Interactions? A example in the academic paper was shown below.
![image](https://github.com/strengejacke/ggeffects/assets/42333702/203f88f3-5ed6-4458-bbec-d6dd4c50f39a)

**Comment by strengejacke** [comment]
Is there a coefficient table? Could it be the t value from that table? Else, if you want to test contrasts, you may look at this series of vignettes: https://strengejacke.github.io/ggeffects/articles/introduction_comparisons_1.html

**Comment by zhaoliang0302** [comment]
The original code of the paper is unavailable. `summary()` function for lmer  model object can return `t` values. But I don't know whether `t` value can represent the statistics of the two-way interaction. `hypothesis_test` function can return a table containing `contrast` column. Does the `contrast` equal to `t` value? If not, does `contrast` can be used in academic paper?

**Comment by strengejacke** [comment]
Currently, the standard error is not included, but required to calculate the t-value / test-statistic. I opened a PR to fix this, now you can at least calculate the t-value by hand:

``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)
data(sleepstudy)
set.seed(123)
sleepstudy$f <- as.factor(sample(1:2, nrow(sleepstudy), replace = TRUE))
m <- lmer(Reaction ~ Days * f + (Days | Subject), sleepstudy)
out <- ggpredict(m, c("Days", "f")) |>
  hypothesis_test()

# Standard error for contrasts or comparisons, saved as attribute
se <- attributes(out)$standard_error

# to get t-value / test-statistic, devide estimate by standard error
# in this example, the estimate is "Contrast"
out$Contrast / se
#> [1] -0.05237771
```

<sup>Created on 2023-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by zhaoliang0302** [comment]
Thanks. This new feature will be included in future releases of the `ggeffects`?

**Comment by strengejacke** [comment]
Yes, and there will be a `get_statistic()` method in package _insight_ and `model_parameters()` in package _parameters_ to get a complete output including standard error and test statistic. I'll keep you updated.

**Comment by zhaoliang0302** [comment]
the output of `test_predictions` function for lmer model is the negative values of `model_parameters` functiuon. `Contrast` corresponds to the `coefficient` parameter.
```r
library(lme4)
library(ggeffects)
data(sleepstudy)
set.seed(123)
sleepstudy$f <- as.factor(sample(1:2, nrow(sleepstudy), replace = TRUE))
m <- lmer(Reaction ~ Days * f + (Days | Subject), sleepstudy)
ggpredict(m, c("Days", "f")) |>
  hypothesis_test()
```
```r
# Linear trend for Days

f   | Contrast |      95% CI |     p
------------------------------------
1-2 |    -0.08 | -3.06, 2.91 | 0.958
```

```r
model_parameters(m,digits=3)
```

```r
# Fixed Effects 

Parameter    | Coefficient |    SE |             95% CI | t(172) |      p
-------------------------------------------------------------------------
(Intercept)  |     247.541 | 8.026 | [231.698, 263.384] | 30.841 | < .001
Days         |      10.589 | 1.704 | [  7.225,  13.954] |  6.213 | < .001
f [2]        |       6.457 | 7.834 | [ -9.007,  21.920] |  0.824 | 0.411 
Days * f [2] |       0.079 | 1.522 | [ -2.925,   3.083] |  0.052 | 0.959 

# Random Effects 

Parameter                     | Coefficient |    SE |           95% CI
----------------------------------------------------------------------
SD (Intercept: Subject)       |      24.523 | 5.840 | [15.377, 39.110]
SD (Days: Subject)            |       5.867 | 1.246 | [ 3.870,  8.896]
Cor (Intercept~Days: Subject) |       0.078 | 0.321 | [-0.505,  0.611]
SD (Residual)                 |      25.577 | 1.518 | [22.769, 28.731]
```
