### ISSUE TITLE
missing errors when using fixest models

### ISSUE THREAD

**Issue by aseimel** [strengejacke/ggeffects#403]
Hello,

It its really nice that ggeffects now supports the great fixest package. However, I have noticed that the ggpredict fucntion is quite sensitive to incorrectly code factors. R and the fixest package do not really need the fixed effects or any dummy variables to be coded as factors to run properly. However, ggpredict does not produce results when any factor variable is not coded as a factor in the used dataset. This also applies when the variables are coded as factors in the formula. The function does not produce an error that make this easy to identify so I would suggest: could you add an error code or warning for this to avoid people going through the same process of confusion I just went through. 

Also, the function does not produce results in cases when observations are dropped because of 0 weights or panel data logit models where values are constant across an individual or group. Again with a warning or error code that tells you this that would be no issue at all. 

Thank you for this great tool!
best regards,
Armin

**Comment by strengejacke** [comment]
_bump_

**Comment by aseimel** [comment]
Hello,
I am very sorry for not getting back to you about this. Please see the example below where for the same model Attempt 1 with the variable not coded as a factor does not produce confidence intervals and Attempt 2 with the variable coded as a factor does generate confidence intervals:

`
# Required Libraries
library(ggeffects)
library(fixest)

# Simulate Data
set.seed(101)  # For reproducibility
df <- data.frame(
  y = rnorm(200),
  year = sample(c(2010, 2011, 2012), 200, replace = TRUE),
  var = rnorm(200)
)

# Model: Simple example with a year variable and continuous predictor
model <- feols(y ~ var | year, data = df)

# Attempt 1: Making 'year' a character (could lead to issues)
test1 <- ggpredict(model, terms = 'var')

# Attempt 2: 'year' as a proper factor 
df$year <- as.factor(df$year) 
test2 <- ggpredict(model, terms = 'var') 
`

**Comment by strengejacke** [comment]
Thanks, should be fixed in #445
