### ISSUE TITLE
Johnson-Neyman FDR Correction

### ISSUE THREAD

**Issue by jgeller112** [strengejacke/ggeffects#408]
I don't see a multiple comparison correction argument in the johnson_neyman function. It is part of the sim_slopes function https://interactions.jacob-long.com/reference/sim_slopes. Can this be included?

**Comment by jgeller112** [comment]
Sorry. I know about p_adjust. I am talking about the figure produced—its not corrected.


On Nov 26, 2023, at 1:30 PM, Daniel ***@***.***> wrote:

﻿

It should be possible to use the p_adjust argument, see documentation here<https://strengejacke.github.io/ggeffects/reference/hypothesis_test.html>.

**Comment by jgeller112** [comment]
Did you push new changes? I tried downloading latest version but the p_adjust is still not working inside the function.

**Comment by jgeller112** [comment]
> > I don't see a multiple comparison correction argument in the johnson_neyman function. It is part of the sim_slopes function https://interactions.jacob-long.com/reference/sim_slopes. Can this be included?
> 
> btw, how to do multiple comparison with `sim_slope()`?

Sorry. It is here: https://interactions.jacob-long.com/reference/johnson_neyman. Not sim_slopes.

**Comment by strengejacke** [comment]
> Did you push new changes? I tried downloading latest version but the p_adjust is still not working inside the function.

It's currently in this PR-branch: #409 - but I just realized that the implementation is not accurate. I'll take a look at the implementation of the _interactions_ package.

**Comment by strengejacke** [comment]
Ok, `p_adjust = "fdr"` seems to do the same adjustment as in the _interactions_ package, however, it only adjusts the p-level, not the confidence intervals. I now also implemented method `"esarey"`, which also adjusts confidence intervals.

``` r
library(ggeffects)
data(efc, package = "ggeffects")
efc$c172code <- as.factor(efc$c172code)
m1 <- lm(neg_c_7 ~ c12hour * barthtot * c172code, data = efc)
pr <- ggpredict(m1, c("c12hour", "barthtot"))
out1 <- johnson_neyman(pr)
out2 <- johnson_neyman(pr, p_adjust = "fdr")
out3 <- johnson_neyman(pr, p_adjust = "esarey")

plot(out1)
#> The association between `c12hour` and `neg_c_7` is negative for values
#>   of `barthtot` lower than 47. There were no clear associations for values
#>   of `barthtot` higher than 47.
```

![](https://i.imgur.com/QYHUbnv.png)

``` r

plot(out2)
#> The association between `c12hour` and `neg_c_7` is negative for values
#>   of `barthtot` lower than 38.20. There were no clear associations for
#>   values of `barthtot` higher than 38.20. 
#> 
#>  P-values were adjusted using the Benjamini & Hochberg (1995) method.
```

![](https://i.imgur.com/ItUqeOl.png)

``` r

plot(out3)
#> The association between `c12hour` and `neg_c_7` is negative for values
#>   of `barthtot` lower than 38.20. There were no clear associations for
#>   values of `barthtot` higher than 38.20. 
#> 
#>  P-values were adjusted using the Esarey & Sumner (2017) method.
```

![](https://i.imgur.com/VhAhOub.png)

<sup>Created on 2023-11-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Once all tests pass, I'll merge the PR.
