### ISSUE TITLE
Relicensing {ggeffects}

### ISSUE THREAD

**Issue by strengejacke** [strengejacke/ggeffects#410]
I would like to re-license _ggeffects_ to use the MIT licence, to make the package's licence as clear and permissive as possible. To do so, Ineed the approval of all potential copyright holders (people who contributed any amount of non-trivial code, as indicated in the DESCRIPTION file).

Would you permit me to re-license _ggeffects_ with the MIT licence?
If so, please comment "I agree" below. Thanks!

@mattansb 
@crsh
@sam-crawley 
@seananderson

**Comment by mattansb** [comment]
I agree 👍

**Comment by crsh** [comment]
I agree!

**Comment by sam-crawley** [comment]
I agree
