### ISSUE TITLE
"Collapse_group" produces many data points

### ISSUE THREAD

**Issue by sandrushba** [strengejacke/ggeffects#428]
Hi, 
I would like to add collapsed data points of my random effects (e.g., participants) on my plot of estimated marginal means. However, using the argument `collapse_group = "subjects"` produces many data points (even though I only have 50 subjects in the df), the collapsing across a specific random factor doesn't seem to work. Adding the jitter doesn't change that, neither does changing the number of random factors added to the collapse_group argument.

I feel like this used to work well. Can you help? 
Thanks!
This is the output with `collapse_group = "subjects"`
![m_RT_cond_cong_collapse_group240115](https://github.com/strengejacke/ggeffects/assets/47183688/50d9c751-ed0d-4d59-9838-ce25fea3d0fa)

This is the "normal" output without
![m_RT_cond_cong_240115](https://github.com/strengejacke/ggeffects/assets/47183688/34de43f1-b235-4d7d-be64-5e42cf8f6e0b)

**Comment by strengejacke** [comment]
@mattansb Not sure if you have any ideas?

**Comment by sandrushba** [comment]
Hi, 
apologies for the delay! Sure, here's an example dataset where I would expect added datapoints per chick and diet (about 9-20 data points per diet) but it appears that all observed data points are added. It seems that the collapsing by the random factor "Chick" doesn't work.
```
library(lme4) 
library(ggeffects)  
m <- lmer(weight ~ Diet + Time + (1 | Chick), data = ChickWeight)
summary(m)
plot(predict_response(m, terms = "Diet", margin = "empirical"), collapse_group = "Chick")
````
![image](https://github.com/strengejacke/ggeffects/assets/47183688/59d244cc-336c-42e2-aed6-b4ecfe903674)

**Comment by mattansb** [comment]
@strengejacke It seems like at some point a column was added to the "rawdata" called rowname? When we remove it, things work fine:

``` r
library(lme4)
#> Loading required package: Matrix
library(ggeffects)

m <- lmer(weight ~ Diet + Time + (1 | Chick), data = ChickWeight)

gge <- ggpredict(m, terms = "Diet")
plot(gge, collapse_group = TRUE)
#> Collapsing usually not informative across a continuous variable.
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/BEiGBy4.png)

``` r

attr(gge, "rawdata") <- 
  attr(gge, "rawdata") |> dplyr::select(-rowname)

plot(gge, collapse_group = TRUE)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/m3U1uzU.png)

<sup>Created on 2024-03-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Ok, found it. We indeed added row names intentionally, from a comment in the code:

> # add rownames, for labelling data points in plots

I think we can safely remove this column in `collapse_by_group()`.
