### ISSUE TITLE
ggpredict outputs only 6 values at the time

### ISSUE THREAD

**Issue by ajsikanap** [strengejacke/ggeffects#461]
This in the input dataset for which a model is fitted:

> df
 A tibble: 16 × 4
   anno_proc     n     person_year  log_person_year
       <dbl>   <int>       <dbl>           <dbl>
 1         1     36798     127193828         18.7
(...............................................up to 16 rows)
16        16 39182    94996689            18.4
mod_fit<-gam(...)
> rates1 <- ggpredict(
  model = mod_fit,
   terms = c("anno_proc[1:16]", "log_person_year[6.907755]")
 ) %>%
   mutate_at(vars(predicted, conf.low, conf.high), ~ . * 1000) |> as.data.frame()
> rates1
  x predicted   std.error conf.low conf.high    group
1 1  288.1361 0.004794263 285.4413  290.8563 6.907755
(.................................................................)
6 6  309.8535 0.003108311 307.9715  311.7469 6.907755

Even though I specified that I want to fit the prediction from 1 to 16 it only fits the first six rows.
How can i solve this issue?
Thanks,

AK

**Comment by strengejacke** [comment]
Do you have a reproducible example? If there are more rows, there should be a message how to show all rows:

``` r
library(ggeffects)
m <- lm(Petal.Width ~ Sepal.Width, data = iris)
predict_response(m, "Sepal.Width")
#> # Predicted values of Petal.Width
#> 
#> Sepal.Width | Predicted |      95% CI
#> -------------------------------------
#>        2.00 |      1.88 |  1.57, 2.18
#>        2.20 |      1.75 |  1.49, 2.00
#>        2.60 |      1.49 |  1.33, 1.66
#>        3.00 |      1.24 |  1.12, 1.35
#>        3.20 |      1.11 |  0.99, 1.23
#>        3.40 |      0.98 |  0.83, 1.13
#>        3.80 |      0.72 |  0.50, 0.95
#>        4.40 |      0.34 | -0.03, 0.71
#> 
#> Not all rows are shown in the output. Use `print(..., n = Inf)` to show
#>   all rows.

# show all rows
print(predict_response(m, "Sepal.Width"), n = Inf)
#> # Predicted values of Petal.Width
#> 
#> Sepal.Width | Predicted |      95% CI
#> -------------------------------------
#>        2.00 |      1.88 |  1.57, 2.18
#>        2.20 |      1.75 |  1.49, 2.00
#>        2.40 |      1.62 |  1.41, 1.83
#>        2.60 |      1.49 |  1.33, 1.66
#>        2.80 |      1.36 |  1.23, 1.50
#>        3.00 |      1.24 |  1.12, 1.35
#>        3.20 |      1.11 |  0.99, 1.23
#>        3.40 |      0.98 |  0.83, 1.13
#>        3.60 |      0.85 |  0.67, 1.04
#>        3.80 |      0.72 |  0.50, 0.95
#>        4.00 |      0.60 |  0.32, 0.87
#>        4.20 |      0.47 |  0.14, 0.79
#>        4.40 |      0.34 | -0.03, 0.71
```

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
