### ISSUE TITLE
Issue with plotting an interaction with a quadratic variable through plot_model from a multi-level and logistic model

### ISSUE THREAD

**Issue by jtp014** [strengejacke/ggeffects#463]
I have encountered an issue which I cannot overcome. I have this approximate multi-level and logistic model:
```
model<-(glmer(dummy1~dummy2+continuous_variable1+I(continuous_variable1^2)+dummy2*continuous_variable1+rest+(1|level1_variable)+(1|level2_variable), data = df_def, family = binomial, nAGQ=1))
```
The same outcomes are got if I shift the interaction for the quadratic variable:
```
model<-(glmer(dummy1~dummy2+continuous_variable1+dummy2*I(continuous_variable1^2)+I(continuous_variable1^2)+rest+(1|level1_variable)+(1|level2_variable), data = df_def, family = binomial, nAGQ=1))
```

And I want to plot the quadratic effects of continuous_variable1 using the following code.

```
plot_model(model, type="eff",
            pred.type = "re",
            terms = c("continuous_variable1[all]","dummy2"), show.data = F,ci.lvl=0.9)+ geom_jitter()+theme_minimal())+aes(linetype=group)
```

However, the result I get is this one, which makes no sense, because continuous_variable1 ranges from 0 to 7. It is like it counted the sum of continuous_variable1 and continuous_variable1^2:
![imagen](https://github.com/strengejacke/ggeffects/assets/80269742/dfcfded8-440a-48a8-953c-4b552a48e049)

What I would expect to get is something like this (with a U form and with a range from 0 to 7):
![imagen](https://github.com/strengejacke/ggeffects/assets/80269742/4dbc2262-9a76-42a3-b5b1-acbcc0493f7c)

Does anyone know if my code is failing at some point? Or what should I do to correct it? 

Thank you very much in advance for your help!

**Comment by strengejacke** [comment]
Do you have some data for a reproducible example?

**Comment by jtp014** [comment]
Hello, 
Sorry for the late response. I had been trying new strategies and now it perfectly works! Sorry for the inconvenience and thank you for your time!
