### ISSUE TITLE
modify_if() has stricter requirements with data frame columns

### ISSUE THREAD

**Issue by lionel-** [strengejacke/ggeffects#50]
This line is problematic with the new implementation of `modify()`:

https://github.com/strengejacke/ggeffects/blob/951ba67f78d95ec531571554f459e3553720f930/R/utils_expand_data_to_grid.R#L13

We're now wrapping around `[[<-` instead of `[<-`. The data frame method for `[[<-` is stricter and throws an error when the output is too long. The method for `[<-` just truncates with a warning, which you're hiding with suppressWarnings.

Could you fix this problem please? We're planning to release purrr in a couple of weeks.

**Comment by strengejacke** [comment]
Thanks, should be fixed now. Will you remind pkg maintainers before submitting to CRAN, so they can submit their update before?

**Comment by lionel-** [comment]
I'll send revdep emails next week. Thanks for the quick fix!
