### ISSUE TITLE
terms in ZI formula not found

### ISSUE THREAD

**Issue by mdwhitby** [strengejacke/ggeffects#52]
It appears that terms that only appear in the ZI formula are not included in the new data when using ggpredict() (ggeffect version 0.7.0.9000)

The following code produces an error: "Error in eval(predvars, data, env) : object 'DOY' not found"
```

library(glmmTMB)
library(ggeffects)
library(ggplot2)
data("Salamanders")

# View(Salamanders)

fit = glmmTMB(count~spp + cover + mined +(1|site), 
              ziformula=~DOY, 
              dispformula = ~spp,
              data = Salamanders, 
              family=nbinom2)


ggpredict(fit, c("cover", "mined", "spp"), type = "fe.zi") 
```

**Comment by strengejacke** [comment]
Thanks, fixed! Needs the latest fix in sjstats as well, which I'm submitting to CRAN today or tomorrow.
