### ISSUE TITLE
plot add data=TRUE not making sense

### ISSUE THREAD

**Issue by abadgerw** [strengejacke/ggeffects#522]
I am working with the attached dataset: [Test.csv](https://github.com/strengejacke/ggeffects/files/15278982/Test.csv)

I am running the following model:

```
library(ggeffects)
library(jtools)

df<-read.csv("Test.csv",header=T,row.names=1)

model<-lm(log(Molecule) ~ Volume + Pred1 + Pred2 + Pred3, data=df)

```

I then try and plot the results which seems to work when not adding points:

```
ggpredict(model = model, terms = "Volume", back.transform = FALSE) %>%
plot()

```

![Log](https://github.com/strengejacke/ggeffects/assets/90532108/7202e262-f995-4da8-87a6-6513b00a860e)

```
ggpredict(model = model, terms = "Volume", back.transform = TRUE) %>%
plot()

```

![No Log](https://github.com/strengejacke/ggeffects/assets/90532108/b724262e-5100-4cbf-8672-a280f46e398a)

However, when adding the points, I get very wonky results:

```
ggpredict(model = model, terms = "Volume", back.transform = FALSE) %>%
plot(show_data = TRUE)

```

![Log](https://github.com/strengejacke/ggeffects/assets/90532108/0ff57b91-0d09-44ef-9bec-d2441fbf6bea)

```
ggpredict(model = model, terms = "Volume", back.transform = TRUE) %>%
plot(show_data = TRUE)

```

![No Log](https://github.com/strengejacke/ggeffects/assets/90532108/a9f14529-c35e-4ad9-92df-1357ae4d8f95)

I compared this with effect_plot from the jtools package which can overlay the data points but only for the non-transformed data:

```
effect_plot(model,pred="Volume",interval=TRUE,plot.points = TRUE,data=df)

```

![Effect_Plot](https://github.com/strengejacke/ggeffects/assets/90532108/bf4cc0c5-c754-426e-9f48-30038033a3e2)

Any insight into why I can't overlay the data using ggeffects in either the log or backtransformed scales?

**Comment by abadgerw** [comment]
I also notice the same outputs when using the marginaleffects package and the plot_predictions function once I try and display the data points. Any insights @vincentarelbundock?

**Comment by strengejacke** [comment]
Or pass it directly to `plot()`, see this example:
https://strengejacke.github.io/ggeffects/articles/introduction_plotmethod.html#control-y-axis-appearance

**Comment by abadgerw** [comment]
@strengejacke Thanks! Why do the plots when using back.transform TRUE and FALSE look the same? I was expecting the plot with back.transform FALSE to look like the plot created with jtools without weird scaling since the log transformation shrinks all data points to be in the same range.

**Comment by strengejacke** [comment]
I'm not sure, I guess back-transforming only affects predictions, not the raw data. I'll look into this.

**Comment by strengejacke** [comment]
Current state of the development:

``` r
library(ggeffects)
data(sleepstudy, package = "lme4")
model <- lme4::lmer(log(Reaction) ~ Days + (1 | Subject), data = sleepstudy)

pr <- ggpredict(model, "Days", back_transform = FALSE)
#> Model has log-transformed response. Predictions are on log-scale.
plot(pr, show_data = TRUE)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/y79G6Ld.png)

``` r

pr <- ggpredict(model, "Days", back_transform = TRUE)
#> Model has log-transformed response. Back-transforming predictions to
#>   original response scale. Standard errors are still on the log-scale.
plot(pr, show_data = TRUE)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/Xj7b6i3.png)

<sup>Created on 2024-05-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
