### ISSUE TITLE
Curvilinear interaction is significant, then how do I get the significances of the linear term and quadratic term of the focal variable at the +1SD, mean, -SD points of moderator?

### ISSUE THREAD

**Issue by joshua-zh** [strengejacke/ggeffects#529]
Hi, I have a question. If curvilinear interaction is significant, then can I and how do I get the significances of the linear term and quadratic term of the focal variable at the +1SD, mean, -SD points of moderator? Thank you for your help!
Like this interaction plot. For example, could I know the linear term and quadratic term of the red curve? 

![curvilinear interaction](https://github.com/strengejacke/ggeffects/assets/59653591/db715817-b5f8-487f-942e-1fe92dd01d71)

**Comment by strengejacke** [comment]
If you want to test for statistically significant differences, use `test_predictions()`, or in case of numeric interaction terms, `johnson_neyman()`. Here's a toy example:

``` r
library(splines)
library(ggeffects)

dat <- data.frame(
  length = c(
    284, 290, 290, 290, 298, 299, 302, 306, 306, 309,
    310, 311, 317, 317, 320, 323, 334, 334
  ),
  clutch = c(
    3, 2, 7, 7, 11, 12, 10, 8, 8, 9, 10, 13, 7, 9,
    6, 13, 2, 8
  )
)

set.seed(123)
dat2 <- data.frame(
  length = dat$length[sample.int(nrow(dat), nrow(dat), replace = FALSE)],
  clutch = dat$clutch[sample.int(nrow(dat), nrow(dat), replace = FALSE)]
)

dat$groups <- as.factor("A")
dat2$groups <- as.factor("B")

d <- rbind(dat, dat2)
m <- lm(clutch ~ ns(length, df = 2) * groups, data = d)

# plot predictions
predict_response(m, terms = c("length", "groups")) |> plot()
```

![](https://i.imgur.com/VkFhpRT.png)

``` r

# save ggeffects object
pr <- predict_response(m, terms = c("length", "groups"))

# test interaction term with two numeric predictors
out <- johnson_neyman(pr)
out
#> # Difference between levels `A-B` of groups
#> There are no statistically significant differencens between the levels
#>   `A-B` of `groups` for any value of `length`.
```

``` r

plot(out)
#> # Difference between levels `A-B` of groups
#> There are no statistically significant differencens between the levels
#>   `A-B` of `groups` for any value of `length`.
```

![](https://i.imgur.com/1gyeIBM.png)

<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
The relevant docs are:
https://strengejacke.github.io/ggeffects/articles/introduction_comparisons_1.html
https://strengejacke.github.io/ggeffects/articles/introduction_comparisons_2.html

**Comment by joshua-zh** [comment]
Sorry, Dr. Strenge Jacke, the JN plot is confusing, given that the significant difference should be at the higher or lower tails of the moderator TRAIN_C from the interaction simple slope plot. I guess that the simple slope is not linear, these comparisons is not appropriate.
![JN](https://github.com/strengejacke/ggeffects/assets/59653591/148c814c-c096-4775-9d40-92aa6cac0356)

**Comment by joshua-zh** [comment]
[Uploading Moderation-PDW-data.sav.zip…]
This is the spss file and the R commands
model <- lm(WELLBEING ~ RESP_C*TRAIN_C + I(RESP_C**2) + I(RESP_C**2):TRAIN_C, data = Moderation_PDW_data)
summary(model)
predict_interaction <- predict_response(model, terms = c("RESP_C", "TRAIN_C"))
plot(predict_interaction)
Dr. Strenge Jacke
Could I manage to get the linear terms and quadratic terms of the three simple slopes?

**Comment by strengejacke** [comment]
The association (i.e. slope) between `RESP` and the outcome `WELLBEING` is statistically significant for _specific values_ of `TRAIN` only, due to the involved interaction. Since both interaction terms are numeric, you need to find out at which values of `TRAIN` - this is what the `johnson_neyman()` function does.

It states that:

> The association between `RESP_C` and `WELLBEING` is negative for values of `TRAIN_C` that range from -0.88 to 0.29. Outside of this interval, there were no clear associations.

For quadratic terms, the _average slope_ is tested when you look for statistical significance. Below you see the interaction for some single values of `TRAIN`, and you can roughly see that the _average trend_ is indeed only roughly significant for values between -0.88 and 0.29.

You can also use `test_predictions()` to test your interaction at specific values of ´TRAIN`. Not that, unlike the `summary()` output, you don't get values for "linear" or "quadratic" terms, but for the "final" association of your predictors and outcome.

``` r
library(easystats)
#> # Attaching packages: easystats 0.7.1.2
#> ✔ bayestestR  0.13.2.1    ✔ correlation 0.8.4.2  
#> ✔ datawizard  0.10.0.4    ✔ effectsize  0.8.8    
#> ✔ insight     0.19.11.2   ✔ modelbased  0.8.7    
#> ✔ performance 0.11.0.9    ✔ parameters  0.21.7.1 
#> ✔ report      0.5.8.2     ✔ see         0.8.4.1
```

``` r
library(ggeffects)
#> 
#> Attaching package: 'ggeffects'
#> The following object is masked from 'package:easystats':
#> 
#>     install_latest
```

``` r

d <- data_read("c:/Users/mail/Downloads/Moderation-PDW-data.sav.zip")
#> Reading data...
#> Variables where all values have associated labels are now converted into
#>   factors. If this is not intended, use `convert_factors = FALSE`.
#> 2 out of 19 variables were fully labelled and converted into factors.
```

``` r
model <- lm(WELLBEING ~ RESP_C * TRAIN_C + I(RESP_C^2) * TRAIN_C, data = d)
summary(model)
#> 
#> Call:
#> lm(formula = WELLBEING ~ RESP_C * TRAIN_C + I(RESP_C^2) * TRAIN_C, 
#>     data = d)
#> 
#> Residuals:
#>      Min       1Q   Median       3Q      Max 
#> -2.29947 -0.36422  0.01575  0.43853  1.70305 
#> 
#> Coefficients:
#>                      Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)          3.399998   0.043950  77.361  < 2e-16 ***
#> RESP_C              -0.099578   0.040992  -2.429   0.0156 *  
#> TRAIN_C             -0.001774   0.066813  -0.027   0.9788    
#> I(RESP_C^2)         -0.172009   0.042461  -4.051 6.08e-05 ***
#> RESP_C:TRAIN_C       0.034313   0.061305   0.560   0.5760    
#> TRAIN_C:I(RESP_C^2)  0.156078   0.062914   2.481   0.0135 *  
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.6871 on 418 degrees of freedom
#> Multiple R-squared:  0.07658,    Adjusted R-squared:  0.06554 
#> F-statistic: 6.933 on 5 and 418 DF,  p-value: 3.103e-06
```

``` r

predict_interaction <- predict_response(model, terms = c("RESP_C", "TRAIN_C"))
plot(predict_interaction)
```

![](https://i.imgur.com/YRWzK9T.png)

``` r

out <- johnson_neyman(predict_interaction)
plot(out)
#> The association between `RESP_C` and `WELLBEING` is negative for values
#>   of `TRAIN_C` that range from -0.88 to 0.29. Outside of this interval,
#>   there were no clear associations.
```

![](https://i.imgur.com/SOCi6xV.png)

``` r

# TRAIN_C lower than -0.88 is *not* significant
predict_response(model, terms = c("RESP_C", "TRAIN_C [-2]")) |> plot()
```

![](https://i.imgur.com/d81f2tT.png)

``` r
predict_response(model, terms = c("RESP_C", "TRAIN_C [-1]")) |> plot()
```

![](https://i.imgur.com/CYjibiI.png)

``` r

# TRAIN_C between -0.88 and 0.29 *is* significant
predict_response(model, terms = c("RESP_C", "TRAIN_C [-0.5]")) |> plot()
```

![](https://i.imgur.com/6UCfwIG.png)

``` r
predict_response(model, terms = c("RESP_C", "TRAIN_C [0]")) |> plot()
```

![](https://i.imgur.com/rRTdHqS.png)

``` r

# TRAIN_C larger than 0.29 is *not* significant
predict_response(model, terms = c("RESP_C", "TRAIN_C [0.5]")) |> plot()
```

![](https://i.imgur.com/z1JY8l9.png)

``` r
predict_response(model, terms = c("RESP_C", "TRAIN_C [1]")) |> plot()
```

![](https://i.imgur.com/2ytUNPY.png)

``` r

# check slopes for selected values of TRAIN_C
test_predictions(model, terms = c("RESP_C", "TRAIN_C [-2, -1, 0, 1]"), test = NULL)
#> # (Average) Linear trend for RESP_C
#> 
#> TRAIN_C | Slope |       95% CI |     p
#> --------------------------------------
#> -2.00   | -0.17 | -0.42,  0.08 | 0.187
#> -1.00   | -0.13 | -0.28,  0.01 | 0.064
#> 0.00    | -0.10 | -0.18, -0.02 | 0.016
#> 1.00    | -0.07 | -0.21,  0.08 | 0.387

# at mean +/- 1 SD
test_predictions(model, terms = c("RESP_C", "TRAIN_C [-0.66, 0, 0.66]"), test = NULL)
#> # (Average) Linear trend for RESP_C
#> 
#> TRAIN_C | Slope |       95% CI |     p
#> --------------------------------------
#> -0.66   | -0.12 | -0.23, -0.01 | 0.030
#> 0.00    | -0.10 | -0.18, -0.02 | 0.016
#> 0.66    | -0.08 | -0.19,  0.04 | 0.193
```

<sup>Created on 2024-05-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by joshua-zh** [comment]
Thank you for your kind reply. I follow the tricks of Prof. Jeremy Dawson, the R codes are as below:
```
library(dplyr)
Moderation_PDW_data <- Moderation_PDW_data |> mutate(TRAIN_H = TRAIN - (mean(TRAIN) + sd(TRAIN)),
                                                     TRAIN_L = TRAIN - (mean(TRAIN) - sd(TRAIN)))

model_h <- lm(WELLBEING ~ RESP_C*TRAIN_H + I(RESP_C^2)*TRAIN_H, data = Moderation_PDW_data)
summary(model_h)

model_l <- lm(WELLBEING ~ RESP_C*TRAIN_L + I(RESP_C^2)*TRAIN_L, data = Moderation_PDW_data)
summary(model_l)
```
This gives the results:

`Coefficients:
                     Estimate Std. Error t value Pr(>|t|)    
(Intercept)          3.398826   0.061698  55.088   <2e-16 ***
RESP_C              -0.076916   0.058999  -1.304   0.1931    
TRAIN_H             -0.001774   0.066813  -0.027   0.9788    
I(RESP_C^2)         -0.068927   0.060974  -1.130   0.2589    
RESP_C:TRAIN_H       0.034313   0.061305   0.560   0.5760    
TRAIN_H:I(RESP_C^2)  0.156078   0.062914   2.481   0.0135 *  `

and 

`Coefficients:
                     Estimate Std. Error t value Pr(>|t|)    
(Intercept)          3.401170   0.062856  54.110  < 2e-16 ***
RESP_C              -0.122241   0.056201  -2.175   0.0302 *  
TRAIN_L             -0.001774   0.066813  -0.027   0.9788    
I(RESP_C^2)         -0.275090   0.057804  -4.759 2.68e-06 ***
RESP_C:TRAIN_L       0.034313   0.061305   0.560   0.5760    
TRAIN_L:I(RESP_C^2)  0.156078   0.062914   2.481   0.0135 *  `

The coefficients of RESP_C and RESP_C^2 are what I need. 

I wander if there is more convenient or more general operation. 
Thanks for consideration.

**Comment by joshua-zh** [comment]
Thank you for your kind reply. I follow the tricks of Prof. Jeremy Dawson, the R codes are as below:
```
library(dplyr)
Moderation_PDW_data <- Moderation_PDW_data |> mutate(TRAIN_H = TRAIN - (mean(TRAIN) + sd(TRAIN)),
                                                     TRAIN_L = TRAIN - (mean(TRAIN) - sd(TRAIN)))

model_h <- lm(WELLBEING ~ RESP_C*TRAIN_H + I(RESP_C^2)*TRAIN_H, data = Moderation_PDW_data)
summary(model_h)

model_l <- lm(WELLBEING ~ RESP_C*TRAIN_L + I(RESP_C^2)*TRAIN_L, data = Moderation_PDW_data)
summary(model_l)
```
This gives the results:

`Coefficients:
                     Estimate Std. Error t value Pr(>|t|)    
(Intercept)          3.398826   0.061698  55.088   <2e-16 ***
RESP_C              -0.076916   0.058999  -1.304   0.1931    
TRAIN_H             -0.001774   0.066813  -0.027   0.9788    
I(RESP_C^2)         -0.068927   0.060974  -1.130   0.2589    
RESP_C:TRAIN_H       0.034313   0.061305   0.560   0.5760    
TRAIN_H:I(RESP_C^2)  0.156078   0.062914   2.481   0.0135 *  `

and 

`Coefficients:
                     Estimate Std. Error t value Pr(>|t|)    
(Intercept)          3.401170   0.062856  54.110  < 2e-16 ***
RESP_C              -0.122241   0.056201  -2.175   0.0302 *  
TRAIN_L             -0.001774   0.066813  -0.027   0.9788    
I(RESP_C^2)         -0.275090   0.057804  -4.759 2.68e-06 ***
RESP_C:TRAIN_L       0.034313   0.061305   0.560   0.5760    
TRAIN_L:I(RESP_C^2)  0.156078   0.062914   2.481   0.0135 *  `

The coefficients of RESP_C and RESP_C^2 are what I need. 

I wander if there is more convenient or more general operation. 
Thanks for consideration.

**Comment by strengejacke** [comment]
Good to here you found a solution. Looks like this is actually no issue with the ggeffects package then, so closing this issue.
