### ISSUE TITLE
predict_response() vs ggeffect()

### ISSUE THREAD

**Issue by YyLu5** [strengejacke/ggeffects#533]
I'm confused by the difference between these two functions. I've read that the predict_response is a "wrapper" function for ggeffect(). I used both the ggeffect(model, term) and predict_response (model, term) to compare, the results are different, they differ by small values and the SE is slightly larger in the ggeffect() function. Later when my model contains a random effect, I'm able to use ggeffect(model,term,vcov_fun="CR3"), while use predict_response(model,term,vcov_fun="CR3") caused an error "Error in vcovCR.default(obj = list(obj = list(par = c(beta = 5.34256429246318,  : 
  argument "cluster" is missing, with no default" 

So I'm not sure which one is correct to use. Thank you!

**Comment by strengejacke** [comment]
In a [recent commit](https://github.com/strengejacke/ggeffects/commit/5fcfc107d10224fc66e179349da37c54e306d362), I added warnings when non-supported arguments are used in function calls.

**Comment by YyLu5** [comment]
sounds great, this is very helpful, thank you!
