### ISSUE TITLE
error in trying to predict with interaction between 2 categorical variables 

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#54]
Hello, 

This seems like a great package, but I'm stuck in trying to use it to produce a plot where 2 categorical variables have a significant effect in the model.  I try to run the following,
`mydf <- ggpredict(mod_total2, terms = "trtmt", "near.far")`
but get this error message: Error in 1 - ci.lvl : non-numeric argument to binary operator.

Thank you in advance for your help!

**Comment by strengejacke** [comment]
The argument for `terms` is just one value, you need to supply a character vector.

```r
mydf <- ggpredict(mod_total2, terms = c("trtmt", "near.far"))
```

**Comment by rpmady** [comment]
That is so simple a fix, thank you! I'm new to coding, so I must have overlooked that when I was reading about how to use it. Thank you very much.
