### ISSUE TITLE
Clustered SEs with margin=marginalmeans

### ISSUE THREAD

**Issue by GiladHu** [strengejacke/ggeffects#545]
Hi, Thanks for the very useful package.

In a nutshell, I have two questions:
1. Any way to incorporate clustered standard errors into predict_response(margin="marginalmeans")?
2. Any way to give equal weight to the levels of the non-focal covariate in predict_response(margin="marginalmeans")?

the first question follows your answer to issue #533:

"ggeffect() has no vcov_* argument. This is only supported by ggpredict() or ggaverage() (or: predict_response() and predict_response(margin = "empirical")). ggeffect() ignores the vcov_fun argument and therefore throws no error."

If I am not mistaken, when setting the margin argument in predict_response to "marginalmeans", ggemmeans is called, which calls emmeans::emmeans.  I think emmeans does support recalculations of vcov. 

is there any way to incorporate clustered standard errors in predict_response where margin = "marginalmeans"? Or any idea for a workaround? Or is there any reason I am not thinking of that this should not be possible?

on a related note, what margin = "marginalmeans" does is "Marginalizing over the factor levels of non-focal terms computes a kind of “weighted average” for the values at which these terms are hold constant. Thus, non-focal categorical terms are conditioned on “weighted averages” of their levels." I assume this means the average is weighted by the proportion of the different levels of the non-focal covariate in my dataset. Is it possible to give equal weight to the levels of the non-focal covariate when averaging? 

Thank you very much.

**Comment by strengejacke** [comment]
@mattansb Can you say something to the last question? Does _emmeans_ allow to specify "weights" for the non-focal categorical terms?

>  I assume this means the average is weighted by the proportion of the different levels of the non-focal covariate in my dataset. Is it possible to give equal weight to the levels of the non-focal covariate when averaging?

**Comment by strengejacke** [comment]
``` r
library(ggeffects)

data(mtcars)
fit <- lm(mpg ~ hp + as.factor(cyl), data = mtcars)

ggemmeans(fit, "cyl")
#> # Predicted values of mpg
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |     25.12 | 22.32, 27.93
#>   6 |     19.16 | 16.60, 21.71
#>   8 |     16.60 | 13.98, 19.22
#> 
#> Adjusted for:
#> * hp = 146.69
```

``` r

ggemmeans(fit, "cyl", vcov_fun = "vcovHC", vcov_type = "HC0")
#> # Predicted values of mpg
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |     25.12 | 21.38, 28.87
#>   6 |     19.16 | 17.59, 20.73
#>   8 |     16.60 | 14.20, 19.00
#> 
#> Adjusted for:
#> * hp = 146.69
```

``` r

ggemmeans(fit, "cyl", vcov_fun = sandwich::vcovHC, vcov_args = list(type = "HC0"))
#> # Predicted values of mpg
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |     25.12 | 21.38, 28.87
#>   6 |     19.16 | 17.59, 20.73
#>   8 |     16.60 | 14.20, 19.00
#> 
#> Adjusted for:
#> * hp = 146.69
```

<sup>Created on 2024-06-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
I don't think emmeans supports differential weighting by variable.

**Comment by strengejacke** [comment]
I think it's just the `weight` argument, which you can pass to emmeans, e.g. `ggemmeans(model, "x", weights = "proportional")`. See https://rvlenth.github.io/emmeans/reference/emmeans.html#weights

**Comment by GiladHu** [comment]
this is great! And so fast, I really appreciate it, thanks!
the only problem is that I am not sure how to specify the clustering variable for vcovCR. 


`data(mtcars)
fit <- lm(mpg ~ hp + as.factor(cyl), data = mtcars)

mtcars$gear<-as.factor(mtcars$gear)

ggemmeans(fit, "cyl", vcov_fun = clubSandwich::vcovCR, vcov_type = "CR0",
          vcov_args = list(cluster = mtcars$gear))`



Can't compute estimated marginal means, 'emmeans::emmeans()' returned an error.

Reason: You must specify a clustering variable.
You may try 'ggpredict()' or 'ggeffect()'.


what am I missing?

Thanks!

**Comment by strengejacke** [comment]
There was a minor issue with passing the correct arguments when a function is provided for `vcov_args`, but still, the problem remains. It looks that this is an emmeans issue:

``` r
data(mtcars)
fit <- lm(mpg ~ hp + as.factor(cyl), data = mtcars)
mtcars$gear <- as.factor(mtcars$gear)
emmeans::emmeans(fit, "cyl", vcov = clubSandwich::vcovCR, type = "CR0", cluster = mtcars$gear)
#> Registered S3 method overwritten by 'clubSandwich':
#>   method    from    
#>   bread.mlm sandwich
#> Error in vcovCR.lm(object, ...): argument "type" is missing, with no default
```

<sup>Created on 2024-06-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
What works is this:

``` r
library(ggeffects)
data(mtcars)
fit <- lm(mpg ~ hp + as.factor(cyl), data = mtcars)

mtcars$gear <- as.factor(mtcars$gear)
ggemmeans(fit, "cyl",
  vcov_fun = clubSandwich::vcovCR(fit, type = "CR0", cluster = mtcars$gear)
)
#> Registered S3 method overwritten by 'clubSandwich':
#>   method    from    
#>   bread.mlm sandwich
#> # Predicted values of mpg
#> 
#> cyl | Predicted |       95% CI
#> ------------------------------
#>   4 |     25.12 | 21.61, 28.64
#>   6 |     19.16 | 17.71, 20.60
#>   8 |     16.60 | 14.61, 18.60
#> 
#> Adjusted for:
#> * hp = 146.69
```

<sup>Created on 2024-06-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

For the above mentioned issue, I suggest opening an issue at the emmeans-repo.
