### ISSUE TITLE
Using an offset with method='empirical' 

### ISSUE THREAD

**Issue by AMCOOK** [strengejacke/ggeffects#558]
Good day, 
I am working with some mgcv::gam models which have an offset term. I am trying to apply your predict_response function with margin='empirical' to obtain predictions on the fYear term. As the offset term is really just a structural predictor I was wondering if there is any way to 'fix' the offset as I would do with estimating conditional means.

out = mgcv::gam(WEIGHT_KG~s(time)+fYear+offset(leffort),data=rawD,family = Gamma(link='log'),method='REML')

bb=predict_response(rawD,terms='fYear',margin='empirical',condition = c(leffort=0))

Thank you for any guidance you can offer

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by strengejacke** [comment]
Should be fixed!
