### ISSUE TITLE
Breaking change in `marginaleffects` 0.22.0

### ISSUE THREAD

**Issue by vincentarelbundock** [strengejacke/ggeffects#564]
I'm sorry but there is a breaking change in `marginaleffects` 0.22.0, and some of your tests will need updating. It has to do with the order of operations in backtransformations and mean, in `avg_predictions()`. The default value of `type` for this function is now "response" rather than "invlink(link)". See:

https://github.com/vincentarelbundock/marginaleffects/blob/main/NEWS.md

Setting the `type` argument explicitly in this line will likely fix the problem:

https://github.com/strengejacke/ggeffects/blob/master/tests/testthat/test-avg_predictions.R#L74

Apologies.

**Comment by strengejacke** [comment]
Which branch can I use for testing?

**Comment by vincentarelbundock** [comment]
It's merged in main
