### ISSUE TITLE
Add support for multi-response model

### ISSUE THREAD

**Issue by therimalaya** [strengejacke/ggeffects#58]
It is nice to have this package. I have been creating the effect plot taking the effects data from effect plot every time. I have been working with the multi-response model and I had to extract a part of code from effects package to make it work for the model. It would be very nice if you can add support for the multi-response model as well.

**Comment by strengejacke** [comment]
Do you have a reproducible example? You can already plot marginal effects for multivariate response models from the packages brms and rstanarm (stanmvreg).

**Comment by therimalaya** [comment]
I figured out that `effects` package handles the multi-response model but I get an error with `ggeffects` as,

``` r
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggeffects)
})
dta <- ggplot2::mpg %>% 
  select(cty, hwy, class, cyl) %>% 
  filter(class %in% c('compact', 'suv'),
                cyl %in% c(4, 6)) %>% 
  mutate_at(vars(class, cyl), as.factor)

mdl <- lm(cbind(cty, hwy) ~ class * cyl, data = dta)
ggeffect(mdl, "cyl")
#> Error in `$<-.data.frame`(`*tmp*`, "group", value = structure(1L, .Label = "1", class = "factor")): replacement has 1 row, data has 0
```

With some digging, the problem is in `ggeffect_helper` function at https://github.com/strengejacke/ggeffects/blob/cce7e2fc93bf05ca28e109ad034b51a092931de5/R/ggeffect.R#L132.
