### ISSUE TITLE
Disconnect discrete points (predict_response, connect_lines)

### ISSUE THREAD

**Issue by august-18** [strengejacke/ggeffects#596]
Fantastic package.

I'm running into a new issue with some old code that I think was written under version 1.5.0

Is there a way to remove the line connecting discrete points on a plot?

I'm plotting the predicted probabilities (options(ggeffects_margin = "marginalmeans")) of a multivariable GEE model with a binary predictor (coded as 1,2)

Using this code
```
plot(
  predict_response(model, terms = "x"),
  ci_style = "errorbar"
) +
  scale_x_continuous(
    labels = c("\n No",
               "\n Yes"),
    breaks = c(1, 2),
    expand = c(0,0)
  )
```
Produces this graph

<img width="671" alt="image" src="https://github.com/user-attachments/assets/1e237e93-cc43-4c86-ae85-c1f04fe7f737">

But when I try to remove the line connecting the discrete points using the connect_lines argument, it does not remove it
```
plot(
  predict_response(model, terms = "x"),
  ci_style = "errorbar",
  connect_lines = FALSE
) +
  scale_x_continuous(
    labels = c("\n No",
               "\n Yes"),
    breaks = c(1, 2),
    expand = c(0,0)
  )

```

edit:
```
[1] stringr_1.5.1   forcats_1.0.0   patchwork_1.2.0 ggeffects_1.7.2
[5] geepack_1.3.12  gtsummary_2.0.3 ggplot2_3.4.4   dplyr_1.1.4
```

**Comment by strengejacke** [comment]
Do you have a reproducible example? I can't reproduce your issue.

**Comment by august-18** [comment]
Thank you for checking!

I tried this public data set from https://library.virginia.edu/data/articles/getting-started-with-generalized-estimating-equations. I was not able to reproduce the error either, so it must be something with my data rather than the package

```
library(geepack)
library(ggeffects); options(ggeffects_margin = "marginalmeans")

URL <- "http://static.lib.virginia.edu/statlab/materials/data/depression.csv"
dat <- read.csv(URL, stringsAsFactors = TRUE)
dat$id <- factor(dat$id)
dat$drug <- relevel(dat$drug, ref = "standard")

gee = geeglm(
  depression ~ drug + diagnose,
  data = dat,
  id = id,
  family = "binomial",
  corstr = "exchangeable",
  scale.fix = TRUE,
  std.err = "san.se"
)

pp = plot(
  ggemmeans(gee, terms = "drug"),
  show_ci = TRUE,
  dot_size = 2,
  line_size = 1
)
```

<img width="707" alt="image" src="https://github.com/user-attachments/assets/5efb68a0-c3a2-455c-89c6-de85ba709c19">

**Comment by strengejacke** [comment]
I now know where this issue comes from, here's a reprex.
`x` is numeric. By default, numeric values are represented by lines:

``` r
library(geepack)
library(ggeffects)

### Example adapted from the geepack user guide
n_cluster <- 6
n_time <- 2
set.seed(1213)
timeorder <- rep(1:n_time, n_cluster)
x <- timeorder
idvar <- rep(1:n_cluster, each = n_time)
uuu <- rep(rnorm(n_cluster), each = n_time) # A 'random intercept'
yvar <- 1 + 2 * x + uuu + rnorm(length(x))
simdat <- data.frame(idvar, timeorder, x, yvar)

mod1 <- geeglm(yvar ~ x, id = idvar, data = simdat, corstr = "ar1")
plot(predict_response(mod1, terms = "x"), show_ci = FALSE)
```

![](https://i.imgur.com/9QNoZJI.png)

Now you changes the CI style to error bars. Error bars are shown at each valid data point. The numeric `x` has only two data points, thus, you get the impression of having a discrete/categorical variable, which is not the case:

``` r
plot(predict_response(mod1, terms = "x"), ci_style = "errorbar")
```

![](https://i.imgur.com/zdu6xFG.png)

If you want "real" plots for discrete values, simply convert `x` into a factor:

``` r
simdat$x <- factor(simdat$x)
mod1 <- geeglm(yvar ~ x, id = idvar, data = simdat, corstr = "ar1")
plot(predict_response(mod1, terms = "x"))
```

![](https://i.imgur.com/7zVr8wR.png)
