### ISSUE TITLE
closure error

### ISSUE THREAD

**Issue by bshor** [strengejacke/ggeffects#6]
I have a simple multilevel (mixed) model I am fitting with glmer(). Here is the call:

`fit.r <- glmer(switch~(1|st)+(1|year)+(1|k.id)+diff, family="binomial", data=subset(sw.sample,party=="R"),control=glmerControl(optimizer="bobyqa"))`

I have no problem fitting it, I get sensible results, etc.

```
> summary(fit.r)
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: binomial  ( logit )
Formula: switch ~ (1 | st) + (1 | year) + (1 | k.id) + diff
   Data: subset(sw.sample, party == "R")
Control: glmerControl(optimizer = "bobyqa")

     AIC      BIC   logLik deviance df.resid 
   697.2    726.4   -343.6    687.2     2549 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
 -1.62  -0.17  -0.10  -0.06 323.79 

Random effects:
 Groups Name        Variance  Std.Dev. 
 k.id   (Intercept) 2.297e-14 1.516e-07
 st     (Intercept) 1.605e+00 1.267e+00
 year   (Intercept) 2.852e-01 5.341e-01
Number of obs: 2554, groups:  k.id, 2229; st, 49; year, 31

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -4.4517     0.3195 -13.934   <2e-16 ***
diff         -4.3385     0.4461  -9.724   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
     (Intr)
diff 0.446 
```

When I try to use ggeffects on the fit object and the primary variable of interest (diff), I get the following error:

```
ggpredict(fit.r,terms="diff")
Error in model.frame.default(object, data, xlev = xlev) : 
  invalid type (closure) for variable 'diff'
```

**Comment by strengejacke** [comment]
Do you have a reproducible example, or could send me some data to reproduce it?

**Comment by strengejacke** [comment]
I guess there are conflicts with the variable name and R's base function `diff()`. This error does not automatically occur for every user.

Workaround: rename the variable "diff". And try `conflicts()`, to see whether there's indeed a naming conflict...
