### ISSUE TITLE
type ="re" and type="fe" are returning the same predicted values

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#61]
It looks like ggpredict() only returns predicted values on the response scale now? I'm not sure I'm reading [this](https://strengejacke.github.io/ggeffects/reference/ggpredict.html#arguments) correctly, but that is what I'm getting in my output. 
```
p1 <- ggpredict(zip_mod5, terms="trtmt", type="re"); p1

# Predicted counts of sum.50 
# x = trtmt 

 x predicted std.error conf.low conf.high
 1     0.144     0.533    0.051     0.411
 2     3.690     0.189    2.548     5.345
 3     5.437     0.194    3.719     7.950
 4     1.397     0.333    0.727     2.684
```

```
p1.1 <- ggpredict(zip_mod5, terms="trtmt", type="fe"); p1.1

# Predicted counts of sum.50 
# x = trtmt 

 x predicted std.error conf.low conf.high
 1     0.144     0.524    0.052     0.403
 2     3.690     0.160    2.699     5.046
 3     5.437     0.165    3.933     7.517
 4     1.397     0.318    0.749     2.603
```

**Comment by strengejacke** [comment]
Yes, `ggpredict()` always returns predicted values on the response scale. Predictions are always on the population level by default. You can, however, get predicted values for specific levels of random effects. See here:

https://strengejacke.github.io/ggeffects/articles/randomeffects.html

**Comment by rpmady** [comment]
Okay, I was confused because reading the following made me think it was on the untransformed scale since  I thought "=link" means that. 

"Similar to mixed models without zero-inflation component, type = "fe" and type = "re" for glmmTMB-models (with zero-inflation) both return predictions on the population-level, where the latter option accounts for the uncertainty of the random effects. In short, predict(..., type = "link") is called."
[https://strengejacke.github.io/ggeffects/articles/marginaleffects.html#short-technical-note]( https://strengejacke.github.io/ggeffects/articles/marginaleffects.html#short-technical-note)

**Comment by strengejacke** [comment]
Where do you exactly have this quote from?

**Comment by rpmady** [comment]
Sorry, I think the wrong link got pasted. I found it here, [https://strengejacke.github.io/ggeffects/articles/randomeffects.html](https://strengejacke.github.io/ggeffects/articles/randomeffects.html), under the section titled, "Marginal effects for zero-inflated mixed models"

**Comment by strengejacke** [comment]
Ok thanks. I should add that the predicted values are back transformed to the response scale.

**Comment by rpmady** [comment]
Thanks, @strengejacke. That clarification definitely helps.
