### ISSUE TITLE
Tests failing on upcoming `marginaleffects` 0.24.0

### ISSUE THREAD

**Issue by vincentarelbundock** [strengejacke/ggeffects#612]
This may be due to either:

* Change in row order
* Change in row labels

Unfortunately, I can't be sure because your test suite doesn't allow me to run it in my mac.

Sorry for the inconvenience!

**Comment by strengejacke** [comment]
Do you know which particular example is failing?

**Comment by strengejacke** [comment]
And, can I test on the _marginaleffects_ main branch, or any PR branch?

**Comment by vincentarelbundock** [comment]
The log file is a mess, but the relevant part to identify the file and line starts about here: https://github.com/vincentarelbundock/marginaleffects/actions/runs/11999543243/job/33447585194?pr=1284#step:14:29

Yes, this should be tested against `main`

**Comment by strengejacke** [comment]
Ok, should be (almost) fixed. I guess I also have to change a few things in the vignettes, where I refer to exact lines in the output of `test_predictions()`, since row-order has changed in the _marginaleffects_ output.

**Comment by vincentarelbundock** [comment]
Yeah, sorry about that. The good news is that the row order should now be more "stable". It used to depend on the order of the I put data, which is a pretty bad idea...
