### ISSUE TITLE
Unable to produce confidence intervals with ggpredict using model.avg Beta regression

### ISSUE THREAD

**Issue by christopherDennison** [strengejacke/ggeffects#614]
Good evening,

I hope this message finds you well. I am wanting to plot the marginal effect of a model averaged coefficient (from a glmmTMB, zero-inflated Beta Regression) using the `ggpredict()` function, but have been receiving the error: `Error: Confidence intervals could not be computed.`

Here is a sample of my code:

I first create a global model:

`BirdNET_ShanF_Full <- glmmTMB(Shan_Fscore ~ vehicular_cs + avgAMP_cs + L10AMP_cs + Bio_anth_cs + dif_L10L90_cs + Mamp_cs + BKdBA_low_cs + BKdB_low_cs + SoundScape_cs + AnthPh_cs + AAanth_cs + AAcanth_cs + AAduranth_cs + mean_Shan_cs + (1|Site) + (1|year) + (1|neigh), DF_soundscape, family = beta_family(), ziformula = ~1, na.action = "na.fail")`

Then use model.avg from a subset (Delta < 2) of dredged models:

`Beta_modAVG <- model.avg(object = D2_mods, fit = T)`

And when attempting to plot the predicted marginal effect of the "mean_Shan_cs" variable:

`p <- ggpredict(Beta_modAVG, c("mean_Shan_cs [all]"))`

I get the error: `Error: Confidence intervals could not be computed.`

However, I do get the following plot:

![image](https://github.com/user-attachments/assets/644ea3d0-e9d3-4242-b622-7b374d1067a1)

I am wondering if there is a process that applies to zero-inflated beta regressions that would solve this issue?

This humble graduate student thanks you in advance for your time and insights.

**Comment by strengejacke** [comment]
Thanks for reporting this issue. I realized that I haven't looked into the `predict.averaging()` method for a long time, it now computes standard errors, thereby making it easier to calculate confidence interval. The associated PR should fix this:

``` r
library(glmmTMB)
library(MuMIn)
data(FoodExpenditure, package = "betareg")
m <- glmmTMB::glmmTMB(
  I(food / income) ~ income + (1 | persons),
  ziformula = ~1,
  data = FoodExpenditure,
  na.action = "na.fail",
  family = glmmTMB::beta_family()
)
set.seed(123)
dr <- dredge(m)
#> Fixed terms are "cond((Int))", "zi((Int))" and "disp((Int))"
avg <- model.avg(object = dr, fit = TRUE)
out <- ggeffects::predict_response(avg, "income")
#> You are calculating adjusted predictions on the population-level (i.e.
#>   `type = "fixed"`) for a *generalized* linear mixed model.
#>   This may produce biased estimates due to Jensen's inequality. Consider
#>   setting `bias_correction = TRUE` to correct for this bias.
#>   See also the documentation of the `bias_correction` argument.

plot(out)
```

![](https://i.imgur.com/2BCqesm.png)

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by christopherDennison** [comment]
Hello there, Daniel.

I really appreciate your time. Strangely, my code is still spitting out the Error: Confidence intervals could not be computed.

Perhaps there is something on my end that is causing the issue.
