### ISSUE TITLE
MAIHDA example figure

### ISSUE THREAD

**Issue by AndrewLawrence** [strengejacke/ggeffects#619]
Hi there, thanks for the really helpful package.

I ran the MAIHDA example ("practical_intersectionality.Rmd"), but found that the figure showing the predictions appeared different to the figure in the online docs - error bars were too wide.

Looking at the changelog, I saw a relevant argument (~line:224) was recently removed (in #583):  `interval = "confidence"` 

Adding this argument back into the code gave a figure which looked just like the online example.

Looks like a quick fix. I can send a PR if that would be helpful.

Cheers,

Andrew

ggeffects: 1.7.2 (CRAN), R: 4.4.2

Incorrect figure appearance:
![000013](https://github.com/user-attachments/assets/e28b2ef4-53f0-4aac-bb17-d8993dc27746)

**Comment by strengejacke** [comment]
I think you just need to update the ggeffects package. Does this fix your issue?

**Comment by AndrewLawrence** [comment]
Apologies! You're quite right 2.0.0 is on CRAN and it did fix the issue.
I had thought I was on the latest version of ggeffects, but clearly not!
