### ISSUE TITLE
Standard Error calculation

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#62]
The files explaining this package and the functions within it is really helpful and really useful! Thank you for putting all of that together! But I can't seem to find an explanation of how the standard errors and confidence intervals are created. Are they created based on the model scale of the variable (ex: for Poisson on the log scale) or is it based on the original response scale.

**Comment by strengejacke** [comment]
It's a bit hidden, indeed. Under `?ggpredict`, secion _Value_, the docs say:

> The predicted values are always on the response scale! 

This is also true for the CI, however, not for the SE. When you call `ggpredict(...)`, the output says:

> Standard errors are on link-scale (untransformed).

The calculation of the SE depends on the model. For some models, `predict()` has a `se.fit`-argument, where SE come from. For other models, SE are calculated as described here:

https://strengejacke.github.io/ggeffects/articles/marginaleffects.html#short-technical-note

**Comment by rpmady** [comment]
Sorry I missed all of that info. A lingering question I have, though, is if confidence intervals are created from standard errors, are the standard errors "back-transformed" (which I think means e^stderror) and then the confidence intervals are calculated?

**Comment by strengejacke** [comment]
No, CI are based on the SE, and then back-transformed to the response scale. See an example here:

https://strengejacke.github.io/ggeffects/articles/stata.html

**Comment by rpmady** [comment]
Okay, that example helps thank you. And thank you for clarifying here as well.

**Comment by bniebuhr** [comment]
Hi,

I have a related question regarding a warning from `ggpredict`, so I chose to reopen this issue.
I have just fit a simple `lmer` model in the format:

```r
m1 <- lmer(log(y) ~ sex*season + (1|year), data = my_data)
```

Then I have plotted the prediction using `ggpredict`:

```r
ggpredict(m1, terms = c("season", "sex"), type = "random", back.transform = TRUE) %>% plot()
```

The result seems very nice, but I got this warning: 
```r
Model has log-transformed response. Back-transforming predictions to original response scale. Standard errors are still on the log-scale.
```

I understand this is a warning from `ggpredict`, but, according to what was mentioned in the answers above, the CIs presented in the plot are already back transformed to the original scale, am I right?

**Comment by strengejacke** [comment]
Standard errors aren't printed any longer anyway, so I could remove that part of the warning. According to your question: yes, predicted values and their CIs are on the correct scale (back transformed to the original scale).

**Comment by Suggestions-Only** [comment]
For a logistic regression model (more specifically, a random intercepts logistic regression model), how would you get a back-transformed SE?  If that gets too complicated, is there another way to get a confidence interval for a contrast between two groups' predicted probabilities?

**Comment by strengejacke** [comment]
If you're interested in contrasts, I suggest trying _modelbased_ (what you already did), [_marginaleffects_](https://vincentarelbundock.github.io/marginaleffects/) and _emmeans_, and probably compare those results.
