### ISSUE TITLE
Question more than an issue

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#63]
I've created a great plot with the plot() function from ggeffects, but I wanted to know if there is a way to connect the predictions of one category to another by a line to illustrate the two-way interaction? 
![rplot](https://user-images.githubusercontent.com/42630011/53851093-7f48eb00-3f8b-11e9-9e4c-19baa72a1dbd.jpeg)

**Comment by strengejacke** [comment]
You can add ggplot-geoms:

```r
plot(dat) + ggplot2::geom_line()
```

**Comment by rpmady** [comment]
Sorry for the late response, but it worked! Thank you for that. 

I'm still trying to figure out why the errors bars look like the way they do; don't look even on both sides. 
![image](https://user-images.githubusercontent.com/42630011/55236747-08f47d00-5207-11e9-9391-0d75f5a18d3e.png)

**Comment by strengejacke** [comment]
If you update ggeffects, you can use the `connect.lines`-argument in `plot()`. I've implementet this lately (see https://strengejacke.github.io/ggeffects/articles/plotcustomize.html#changing-the-x-axis-appearance).

The error bars are asymmetrical because you have a log-link in your model (I guess poisson or negative binomial). You should log-transform your y-scale, which can be done with `log.y = TRUE` (see https://strengejacke.github.io/ggeffects/articles/plotmethod.html#log-transform-y-axis-for-binomial-models).

**Comment by rpmady** [comment]
Thanks for that! When I try to do the log.y = TRUE, I get an error: 

```
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?
Warning messages:
1: Removed 3 rows containing missing values (geom_point). 
2: Removed 3 rows containing missing values (geom_path). 
3: Removed 4 rows containing missing values (geom_errorbar).
```
This was my prediction code: 
```
pred <- ggpredict(mod2, terms = c("location","trtmt"), type = "fe")

```

**Comment by strengejacke** [comment]
This may happen when values are close to zero. In such cases, pass `breaks` and `limits` via `plot()` to the scale-command, see https://strengejacke.github.io/ggeffects/articles/plotmethod.html#control-y-axis-appearance

**Comment by rpmady** [comment]
I think I may have gotten it to work. if I y-transform my y-scale,  does that mean that what is being displayed it not on the response scale anymore?

**Comment by strengejacke** [comment]
No, you don't change the data nor results. You just change the scale of the _plot_ axis, by log-transforming it.

**Comment by rpmady** [comment]
Okay, gotcha. It's weird that when I use ggpredict for a negative binomial model, the confidence intervals are equal. And then when I use it for a poisson model later the intervals are not equal.

**Comment by rpmady** [comment]
Also, do you have guidance on selecting values for the breaks and limits arguments? I haven't been able to specify any that work

**Comment by rpmady** [comment]
Hi @strengejacke, just wanted to check in I haven't been able to find why the prediction intervals are coming out as uneven for the negative binomial model but even for the poisson model.
