### ISSUE TITLE
Adjusting x values in ggpredict

### ISSUE THREAD

**Issue by adcorso** [strengejacke/ggeffects#64]
I am using `ggpredict` to plot the marginal effects of temperature (a continuous variable) from a glmm zero-inflated model:

`pr1= ggpredict(mod, "temp", type = "re.zi")`

The function is working properly, but only returns predicted values for 7 random temperatures. Does anyone know how to increase the quantity of x values, to 25 for example?

Thanks, 
Andrew

**Comment by strengejacke** [comment]
See this vignette:
https://strengejacke.github.io/ggeffects/articles/effectsatvalues.html

In your case, point 5) applies:

> If the first variable specified in terms is a numeric vector, for which no specific values are given, a “pretty range” is calculated (see pretty_range()), to avoid memory allocation problems for vectors with many unique values. If a numeric vector is specified as second or third variable in term (i.e. if this vector represents a grouping structure), representative values (see rprs_values()) are chosen.

You can either specify certain values, or use `"temp [all]"` to plot all values.

**Comment by adcorso** [comment]
Exactly what I was trying to accomplish, thank you. Sorry I was not aware of that vignette.
