### ISSUE TITLE
Warning of inconsistency between Matrix versions (ggeffects build vs. current)

### ISSUE THREAD

**Issue by jjcii** [strengejacke/ggeffects#65]
I am running R 3.5.3, currently trying to install `ggeffects` package as part of a `sjPlot` install. When loading the `ggeffects` library, I receive the following warning:

`Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.2.15
Current Matrix version is 1.2.16
Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package`

Trying the suggested `TMB` package installation results in the following error message:

`clang: error: unsupported option '-fopenmp'
make: *** [external_metis.o] Error 1
ERROR: compilation failed for package ‘TMB’`

Any suggestions on what I can do to successfully re-install TMB (and if so, which version) or to otherwise resolve the inconsistency? Is there a larger issue I need to address?

**Comment by jjcii** [comment]
FYI, to other with similar messages: Turned out the be an issue with the clang installation rather than anything package-specific.

**Comment by strengejacke** [comment]
ok, thanks!
