### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by strengejacke** [strengejacke/ggeffects#67]
@DominiqueMakowski What do I need to setup codecov? I have an account at https://codecov.io/ and I have added some lines to the travis.yml: https://github.com/strengejacke/ggeffects/blob/master/.travis.yml

```r
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
```

Now I got a token when trying to activate ggeffects. but what should I do with this token? Do I need to install the covr-package?

**Comment by DominiqueMakowski** [comment]
Nothing to do with the token, it's mainly for private repository. 

Basically, it just waits for travis to run the codecov function. You just have to complete one build and codecov should work. 

You can try out by making a PR and see if codecov comments it.

**Comment by strengejacke** [comment]
Ok, just saw it. Works!
