### ISSUE TITLE
ggpredict and ggaverage with 4 terms

### ISSUE THREAD

**Issue by RS-eco** [strengejacke/ggeffects#69]
Hey there,

I am using the ggeffects package and would like to create a plot of a linear model with 4 terms. Using facet_grid it is possible to specify 2 different facets, which is what I would like to do, however your package currently won't allow to implement 4 terms in ggpredict or ggaverage. Is there any chance to implement this in your package. I have to come up with a solution for this, so if you want I can also try to change your functions accordingly by myself.

Cheers,

Matt

**Comment by strengejacke** [comment]
This requires some substantial re-writing of code, I guess. I'll look into this, but probably it takes some time to find out to get this working.

**Comment by strengejacke** [comment]
should work now for `ggpredict()` and `ggemmeans()`.

**Comment by strengejacke** [comment]
See also updated vignette here:
https://strengejacke.github.io/ggeffects/articles/ggeffects.html
