### ISSUE TITLE
Unable to modify plot() function

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#74]
I am trying to change the plot() function so that I have dashed 95% confidence intervals. but the ci.style="dash" doesn't change the appearance and the alpha=0.05 doesn't either.

**Comment by strengejacke** [comment]
Do you have a reproducible example? In this vignette, different styles for error bars are working:
https://strengejacke.github.io/ggeffects/articles/plotmethod.html

**Comment by strengejacke** [comment]
_bump_

**Comment by rpmady** [comment]
Sorry for the delay, thank you for the **bump**. The examples in that vignette show that the plots can be customized (for dashes and such) when it is continuous. My plots are for factors.
