### ISSUE TITLE
rms::ols() support?

### ISSUE THREAD

**Issue by Deleetdk** [strengejacke/ggeffects#75]
Great package! 👍

I see that **rms** package's `lrm()` is supported, but seems that the more basic OLS `ols()` is not. I think supporting this one is important because it enables one to use the very nice spline functions (e.g. `rcs()`) that package offers, and which don't work with base `lm()`, and because it has a lot nicer output than `lm()`.

Are there any plans for support?

**Comment by strengejacke** [comment]
should work now. You probably have to update package _insight_ from GitHub before, especially if you use `rcs()` in your formula.

**Comment by Deleetdk** [comment]
Great, thanks. Here's what I made: http://rpubs.com/EmilOWK/ggeffects_examples

**Comment by strengejacke** [comment]
Looks nice! Would you consider this as "public"? I could probably tweet about it.

**Comment by Deleetdk** [comment]
Sure, go away. I will be tweeting it later today probably.
