### ISSUE TITLE
Error with ggpredict 

### ISSUE THREAD

**Issue by rpmady** [strengejacke/ggeffects#78]
I'm also in a similar situation where I have a mixed model with nested random effects. My error is slightly different, but I figured it might be related?
```
mod3 <- glmmTMB(sum.50 ~ location*trtmt + julian2 + min_aft_sunrise2 + mintemp2 + (1|site:day_mod), 
data = bcch_sub, 
ziformula=~1, 
family=nbinom1) 
When I try to run ggpredict(mod3, terms = c("location","trtmt"), type="fe.zi") I get this error:
Error in eval(predvars, data, env) : object 'day_mod' not found
```

I did as you suggested @strengejacke, but updating the package "insight" hasn't gotten rid of the error.

**Comment by strengejacke** [comment]
Do you have a reproducible example, maybe with one of the built-in datasets?

**Comment by rpmady** [comment]
I'm not sure what bug happened, but today it worked! I'll close this issue since it is resolved. 
Thanks for your help @strengejacke!

**Comment by strengejacke** [comment]
maybe the install or reload of the updated insight-package was buggy? glad it is solved now.
