### ISSUE TITLE
ggeffects does not calculate Average marginal effects according to the standard definition

### ISSUE THREAD

**Issue by gbiele** [strengejacke/ggeffects#79]
First, thanks for working on this package!

Here are my questions:
1) When I read the term "average marginal effect", I would expect the change in the outcome variable for a one unit change of the predictor variable (e.g. [here](https://stats.stackexchange.com/tags/marginal-effect/info) and [here](https://cran.rstudio.com/web/packages/margins/margins.pdf)). However, ggaverage produces expected effects for different levels of the predictor variables. Of course, I could calculate what I need from that, but now I am wondering if I am misunderstanding the term average marginal effect, or if the ggeffects package uses the term different than others.

2) It looks as if the values ggaverage returns the expectation for each level of a predictor only over those cases, where the the predictor had that level in the observed data, i.e. it does counter-factuals are not taken into account. This is different than I had expected, because I thought counterfactuals should be included (see point 1 [here](https://stats.stackexchange.com/tags/marginal-effect/info)). 

Now I am wondering if I am overlooking something or, if ggeffects uses the term average marginal effect in a non-traditional manner?

**Comment by strengejacke** [comment]
Short answer: yes, `ggaverage()` is misleading and uses the term `average marginal effects` in a different way.

I thought of removing that function, or maybe at least revise the docs accordingly. The description [given here](https://strengejacke.github.io/ggeffects/articles/ggeffects.html#average-marginal-effects) maybe explains best what `ggaverage()` exactly does, but these are not _average marginal effects_ in the typical definition (which refers to _marginal coefficients_).

**Comment by strengejacke** [comment]
I'm happy about any suggestion for a clearer wording.

**Comment by strengejacke** [comment]
I have revised the wording throughout the docs and vignettes, speaking of "averaged predicted values" (what they actuall are, somehow). Do you think this is sufficient?

**Comment by gbiele** [comment]
Hei Daniel,

I think this is sufficient, because it is not prone to be misunderstood by
those who read carefully.
One thing you could do is to point somewhere in the documentation to the
"typical" definition of marginal effects and maybe point out to that
"averaged predicted values" are something different than average marginal
effects as e.g. provided by the margins packages.
(I also remember you had a good description on the Stan mailing list about
different way to calculate average predictions, depending on to which
values the other covariates are set.).

Also: I appreciate that you are working on this! I like the ggeffects
package, and just stumbled about how marginal effects are calculated there
when preparing a lecture that advocates
<http://htmlpreview.github.io/?https://github.com/gbiele/MarginalEffects/blob/master/MarginalEffects.html>
and demonstrates use of marginal effects. ;-).


Cheers - Guido

**Comment by strengejacke** [comment]
Nice lecture!

btw, I think one major difference between **margins** and **ggeffects** is that **margins** calculates AME for each parameter, so it returns something that is also called _marginal coefficient_. **margins** can also return marginal effects at the mean (MEM), and I think this is where it is comparable to **ggeffects**, see examples below. Also note that **margins** is probably calculating confidence intervals wrong for models with other families than Gaussian (see this vignette: https://strengejacke.github.io/ggeffects/articles/technical_stata.html and this issue: https://github.com/leeper/margins/issues/92, I think the fix is not in the CRAN version).

``` r
library(ggeffects)
library(margins)
library(boot)
N = 1000
my_data = data.frame(
  MaternalEdu = rnorm(N, mean = 10, sd = 1),
  GenderGirl = (runif(N) > runif(N))*1,
  Birthmonth = sample(1:12,N, replace = T),
  PaternalAgez = rnorm(N),
  parity = rpois(N,.75))

logit_ADHD = with(
  my_data,
  - 6 
  - 1.5  * GenderGirl
  +  .75 * Birthmonth 
  -  .25 * MaternalEdu 
  + .95    * PaternalAgez
  -  .2  * PaternalAgez^2
  + 1    * parity
  + 0.2  * parity^2)

my_data$GenderGirl = factor(my_data$GenderGirl)
my_data$parityo = ordered(my_data$parity)
my_data$ADHD = inv.logit(logit_ADHD) > runif(N)
my_data$ADHD <- as.factor(my_data$ADHD)

logreg_fit = glm(ADHD ~ GenderGirl + Birthmonth 
                 + PaternalAgez + I(PaternalAgez^2) 
                 + MaternalEdu + parity,
                 family = binomial,
                 data = my_data)

cplot(logreg_fit, "PaternalAgez")

ggpredict(logreg_fit,"PaternalAgez") %>% plot()
```

![](https://i.imgur.com/L1xb6vl.png)![](https://i.imgur.com/kYUFd2W.png)

``` r




logreg_fit_linquad = 
  glm(ADHD ~ GenderGirl + Birthmonth
      + PaternalAgez + I(PaternalAgez^2) 
      + MaternalEdu + parity + I(parity^2),
      family = binomial,
      data = my_data)

cplot(logreg_fit_linquad, "parity")
```

![](https://i.imgur.com/ViBBHR3.png)

``` r

ggpredict(logreg_fit_linquad, "parity") %>% plot()
```

![](https://i.imgur.com/szRhUU3.png)

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gbiele** [comment]
thanks for the pointers!
