### ISSUE TITLE
ggpredict fails for clmm model when grouping variable included

### ISSUE THREAD

**Issue by sam-crawley** [strengejacke/ggeffects#86]
Minimal example:

```R
library(lme4)
library(ordinal)
library(ggeffects)

data(sleepstudy)
sleepstudy$Days <- factor(sleepstudy$Days)
m <- clmm(Days ~ Reaction + (1 + Reaction | Subject), data = sleepstudy)

p1 <- ggpredict(m, c('Reaction')) # Works
p2 <- ggpredict(m, c('Reaction', 'Subject'), type = "re") # Fails
```

Error message:

> Error in emmeans::emmeans(object = model, spec = c(insight::find_response(model,  : 
  No variable named Subject in the reference grid

It looks like the grouping variable is getting passed to the emmeans call, when it shouldn't be?

**Comment by strengejacke** [comment]
The **ordinal** package has no `predict()`-method for _clmm_ models, so I instead call `emmeans()` inside `ggpredict()` for clmm-objects. However, it seems that emmeans can't compute marginal effects for different group levels (of random effects).

I'll get in touch with the emmeans-maintainer and ask if there is a solution... Else, as a workaround, you may use the **brms** package.

**Comment by strengejacke** [comment]
I [opened an issue](https://github.com/rvlenth/emmeans/issues/118), let's see if it is possible to address this problem.

**Comment by strengejacke** [comment]
@sam-crawley Here is what Russell currently suggests for such cases:
https://github.com/rvlenth/emmeans/issues/118#issuecomment-504460448

I think at this point there is no more I can do regarding the ggeffects-package, so probably you need to consider this workaround as "fix" for this issue.

**Comment by sam-crawley** [comment]
@strengejacke Thanks for that, it makes sense.
Perhaps ggpredict should issue a warning, or an improved error when used with a clmm model? Happy to submit a pull request if you'd like.

**Comment by strengejacke** [comment]
Yes, feel free to submit an PR!
