### ISSUE TITLE
bug in ggpredict() ?

### ISSUE THREAD

**Issue by f-rousset** [strengejacke/ggeffects#89]
Hi,

I maintain a package (`spaMM`) to fit mixed-effect models and a user's question led me to wonder whether the results from my package could be handled by plot_model() (or rather, at which point this would fail and what could be done about it). While diagnosing the (expected) failure I encounter two lines of code that I find highly suspect in `ggpredict`:
`is.gamm <- inherits(model, c("list", "gamm")) && all(names(model %in% 
    c("lme", "gam")))`
`is.gamm4 <- inherits(model, "list") && all(names(model %in% 
    c("mer", "gam")))`

Are the parentheses right? Shouldn't that be (twice)  `all(names(model) %in% 
    c(`...`))` ? 
As it stands, the code evaluates the tests as `TRUE` if `model` is a list, such as `model <- list(a=1,b=2)`:  `names(model %in% 
    c(`...`))` is `NULL` and `all(NULL)` is `TRUE`.

F.

**Comment by strengejacke** [comment]
Thanks, indeed the parantheses look wrong. I'm currently traveling and get back to this once I'm back.
