### ISSUE TITLE
Support for factors in plot.ggeffects()

### ISSUE THREAD

**Issue by tzoltak** [strengejacke/ggeffects#9]
At the moment plot.ggeffects() handle variables that are labelled but fails with factors. Could it be possible to make it handle also factors, as this is rather widely used data type in R.

```{r}
data(efc)
fitLab <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
(efLab = ggeffect(fitLab, "c161sex"))
plot(efLab)

efc$c161sex = factor(efc$c161sex, labels = names(attributes(efc$c161sex)$labels))
fitFact <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
(efFact = ggeffect(fitFact, "c161sex"))
plot(efFact)
```

**Comment by strengejacke** [comment]
Please use `ggpredict()`:

``` r
library(ggeffects)
data(efc)
efc$c161sex = to_label(efc$c161sex)
#> Error in to_label(efc$c161sex): konnte Funktion "to_label" nicht finden
fitFact <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
(efFact <- ggpredict(fitFact, "c161sex"))
#> # A tibble: 2 x 5
#>       x predicted conf.low conf.high  group
#>   <dbl>     <dbl>    <dbl>     <dbl> <fctr>
#> 1     1  63.96235 60.57479  67.34991      1
#> 2     2  65.00378 63.11013  66.89743      1
plot(efFact)
```

![](https://i.imgur.com/nL0fW33.png)



``` r
library(ggeffects)
data(efc)
efc$c161sex = factor(efc$c161sex, labels = names(attributes(efc$c161sex)$labels))
fitFact <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
(efFact <- ggpredict(fitFact, "c161sex"))
#> # A tibble: 2 x 5
#>       x predicted conf.low conf.high  group
#>   <dbl>     <dbl>    <dbl>     <dbl> <fctr>
#> 1     1  63.96235 60.57479  67.34991      1
#> 2     2  65.00378 63.11013  66.89743      1
plot(efFact)
```

![](https://i.imgur.com/RYFTslB.png)

**Comment by tzoltak** [comment]
However in case of glm-s ggeffect() and ggpredict() doesn't give the same results because values of all the other predictors influences the prediction (and there are people who prefere the assumption about values of other predictors that Effect() does by default while estimating effects over the assumption that ggpredict() does). 
(In case of lm-s ggeffect() and ggpredict() gives results that are simply vertically shifted one to another, but this can be considered a rather minor problem).

But perhaps I should express my feature request differently: could plot method for different kinds of ggeffects objects provide a possibility of drawing confidence intervals also as "bars" instead of "bands" (as plot method for Effect objects from package effects does). I think it would be usefull and elegant in case of predictors that aren't continuous.

```{r}
library(ggeffects)
data(efc)
# a factor on a right side of formula needed
efc$c172code = factor(efc$c172code, labels = names(attributes(efc$c172code)$labels))
# leaving aside if predicting sex makes a sense
fit1 = glm(I(c161sex -1) ~ c12hour + neg_c_7 + c172code, family = binomial, data = efc)
# not quite the same (estimating an effect for continuous predictor so both ggeffect() and ggpredict() works)
plot(ggeffect(fit1, "c12hour"))
plot(ggpredict(fit1, "c12hour"))
```

**Comment by strengejacke** [comment]
Ok, `ggeffect()` should work with factors now, as well (will commit tonight). I'm not quite sure how Effect() exactly deals with factors. `ggeffect(fit1, "c172code")` yields the same result as `ggpredict(fit1, "c172code")`, but when using "c12hour" as term, results differ.

**Comment by tzoltak** [comment]
Thanks!

Regarding why a difference sometimes occurs and sometimes not: it depends whether there is a factor in a set of predictors excluding this one, for which we estimate size of the effect (and possibly those used for conditioning). If there isn't, `ggeffect()` and `ggpredict()` will give the same results. If there is, there will be a difference for the reason described in the "Note" section of the documentation of `ggeffect()` function.

Technically `Effects()` deals with factors this way: it uses `expand.modelframe()` to obtain a matrix in which factors are represented as _dummy_ variables and applies `mean()` (or possibly other function given by the `typical` argument) to each column of this matrix (except this describing predictors under consideration). Of course this means that estimated prediction is for someone being for example "60% female and 40% male" and not everybody likes it. However if someone doesn't like it, I think that he/she would rather use average marginal effects (`ggaverage()`) than assume that factor predictors are equal to their first level.

**Comment by strengejacke** [comment]
Ok, so `Effects()` does exactly "average" over factors... Here's a short implementation:

```
model.matrix(fitFact) %>% 
  tibble::as_tibble() %>% 
  purrr::map_at(3:5, mean) %>% 
  tibble::as_tibble() %>% 
  dplyr::arrange(c12hour) %>% 
  dplyr::distinct() %>% 
  purrr::map2_df(coef(fitFact), ~ .x * .y) %>% 
  sjmisc::row_sums()

ggpredict(fitFact, "c12hour")
```

In most situations, I prefer using the base level, actually.
