### ISSUE TITLE
brms models and weight variables (again)

### ISSUE THREAD

**Issue by sam-crawley** [strengejacke/ggeffects#90]
Hi,

Something of a follow-up to #88. It seems, based on ggeffects HEAD and latest version of dependencies from CRAN that ggpredict for any brms model with weights (regardless of family) is now returning:

` Error: Weights must be numeric. `

This seems to be due to the weight variable getting added into fitfram with NAs (last if block in get_expanded_data()), which rstantools::posterior_linpred() / rstantools::posterior_predict() doesn't like.

I'm unsure what the correct fix should be, perhaps that if block should be skipped for brms models?

**Comment by strengejacke** [comment]
Should work now... brms has a very special handling for regression weights... But the resulting plot looks pretty much identical to what `brms::margina_effect()` produces:

``` r
library(insight)
library(ggeffects)
library(brms)

m <- download_model("brms_3")
ggpredict(m, 'y [all]') %>% plot()
```

![](https://i.imgur.com/jWfBrgF.png)

``` r
brms::marginal_effects(m, categorical = TRUE)
```

![](https://i.imgur.com/TqOa9TB.png)

<sup>Created on 2019-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sam-crawley** [comment]
Thanks for the quick response, it looks good to me.
