### ISSUE TITLE
Marginal effect at a particular response.level? (for proportional odds models)

### ISSUE THREAD

**Issue by sforsilence** [strengejacke/ggeffects#91]
ggeffects produces an extra column for the "response.level". However, I am wondering if any of these functions ggeffects or ggpredict could be used for a particular response level. My response variable has 30 levels and I have run a proportional odds model using clm function (class clm from the ordinal package).

**Comment by strengejacke** [comment]
Currently, you have only the option to filter for specific response-levels, and then plot your data.

``` r
library("ggeffects")
library("ordinal")
data(wine, package = "ordinal")
m1 <- clm(rating ~ temp * contact, data = wine)
p <- ggpredict(m1, "temp")
plot(p)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/J4Dz7m0.png)

``` r

p <- p[p$response.level == 1, ]
plot(p)
```

![](https://i.imgur.com/fhR3bEQ.png)

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
I'll close this for now, feel free to re-open if this does not meet your needs.
