### ISSUE TITLE
Are there limits on the levels of nesting in ggpredict?

### ISSUE THREAD

**Issue by rtwillia** [strengejacke/ggeffects#92]
Hi there, I'm running a mixed model with the following random effects structure: 

(1 | dist/sch/sch_cohort) + (time1 + post -1 | dist)

But when I try to extract predictions on the post variable, with 

ggpredict(fit_alg3_samp, terms = c("post [0]", "dist"), type = "re", ci.lvl = NA) ,

I get the following error:

"Error in eval(predvars, data, env) : object 'sch_cohort' not found"

If I change the structure of the random effects to have a max of one variable nested within another I can get it to work: (1 | sch/sch_cohort) + (1 + time1 + post | dist). But I don't want to do that. It seems that there's limit on how many variables one can nest within a mixed model. Is that the true? If not, what might the issue be or is there a workaround?

Thanks!

**Comment by strengejacke** [comment]
Do you have some fake data or a subset of your data and a reproducible example?

**Comment by rtwillia** [comment]
Sure. Here's some toy data that should demonstrate the issue:

set.seed(1984)
dat <- data.frame(y = rnorm(10000 * 5, sd = 1 - .20), 
                  time = rep(1:10, 1000 * 5), 
                  g1 = sort(rep(1:1000, 10 * 5)), 
                  g2 = sort(rep(1:100, 100 * 5)))
dat$g0 <- paste(dat$time, dat$g)
dat$time1 <- dat$time - 8
dat$post <- 0
dat$post[dat$time >= 8] <- 1
fit <- lmer(y ~ post + time1 + (1 | g2/g1/g0) + (post + time1 - 1 | g2), data = dat)
ggpredict(fit, terms = c("post [0, 1]", "g2 [1:100]"), type = "re", ci.lvl = NA)

**Comment by strengejacke** [comment]
Thanks, _should_ be fixed now after updating [insight](https://github.com/easystats/insight) **from GitHub**:

```r
install.packages("devtools")
devtools::install_github("easystats/insight")
```
