### ISSUE TITLE
Error with ggpredict() for distributional regression model output via mgcv

### ISSUE THREAD

**Issue by MilaniC** [strengejacke/ggeffects#93]
Firstly, excellent package. 

But having an issue for predict from a hurdle model estimated via mgcv::gam().

And throws the error message in message below:

##### tl::dr
Sadly cannot fit my model via Stan/brms as the data file is huge and crashes the system heap - hence trying to get mgcv to work (which it does) and hopefully use the excellent ggeffects package too.

#### the bare-bones ...
require(mgcv)

#### example GAMM with hurdle-Poisson likelihood ...
gamHP <- gam(list(y ~ Zones + s(year) + s(x2) + s(x3,bs="re"),
                    ~ s(x4) + s(x5)),
                    data=dat, 
                    method="REML", ## only method available for distributional type regression model in mgcv
                    family=ziplss())  ## hurdle Poisson likelihood model via REML 

#### then ...
df<-ggeffects::ggpredict(gamHP,c("year","Zones")) %>% 
     as_tibble() %>% 
     mutate(year=x,
            predicted=predicted,
            lower=conf.low,
            upper=conf.high,
            zones=group) %>% 
            dplyr::select(-x,-std.error,-conf.low,-conf.high,-group)

#### generates this error message (irrespective of what type=c(fe, re etc) ...
*Error in f[["conditional"]][[3]] : subscript out of bounds*

#### don't use a distributional regression form but use say nb() or ziP() likelihood and all OK

Is this a bug or am I doing something hideously wrong with ggpredict()?

**Comment by MilaniC** [comment]
Error occurs irrespective of using the CRAN or latest dev version of ggeffects

**Comment by MilaniC** [comment]
Aplogies. Pressed wrong "button" - it is not closed.

**Comment by strengejacke** [comment]
This looks like it might be an issue with the _insight_ package. Do you have a minimal reproducible example, e.g. fake data or a small fraction of your data set?

**Comment by MilaniC** [comment]
Thanks for the quick response. I will prepare an appropriate anonymised data set to test.

Meanwhile, I am thinking it might be to do with the multivariate Gaussian Process spatial effect that is in my model:

	+ s(longitude,latitude,bs="gp",m=3,k=100)
	## overall spatial effect with Matern covariance kernel ...

BTW, the error message occurs using either CRAN or the latest dev version of *ggeffects*

**Comment by strengejacke** [comment]
Yes, I think this needs to be fixed in the [insight-package](https://github.com/easystats/insight), I don't believe this issue is directly related to ggeffects.

This error: `f[["conditional"]][[3]]` looks like code from _insight_.

**Comment by MilaniC** [comment]
Yes, that seems most likely - maybe in the find_terms(). 

OK, I will close this issue here and post over on *insight*. 

Many thanks.

**Comment by strengejacke** [comment]
I think I solved the issue. Can you try to install the current GitHGub versin from insight, and then check again? There still might be problems with the predict-function, though.

**Comment by strengejacke** [comment]
short follow up: I also fixed ggeffects, so you can use `ggpredict()` with gam-models with `ziplss` family. Note that predictions for the count-model work fine, but conditioned on zero-inflation part of the model (when `type = "fe.zi"`) is somewhat experiemental. And currently, I can't get "smooth" confidence intervals for `type = "fe.zi"`.
