### ISSUE TITLE
Does {ggpredict} average over categorical factors for the marginal effect of smooths? In a {gamm4}

### ISSUE THREAD

**Issue by dshelldhillon** [strengejacke/ggeffects#97]
I'm trying to obtain marginal effects of a smooth in a {gamm4} model.  I notice a discrepancy between what ggeffects gives me and what I get manually.  

For a smooth `x0`, I calcualte the predictions over a grid of `x0`, at the average of other two smooths, and at each level of a categorical variable.  Once I have the predictions, I average over the grouping factor to obtain the marginal effects.  

Is that not how marginal effects are calculated? Or is ggeffects calculating it at the reference level of the smooth? 

    ## Logistic Regression with smooth and categorical variables   

    ### Simulate some data   

    # Scale the variables to mean 0 and variance 1 

    # Create an 'id' variable, that is the repeat measurments for each subject

    library(tidyverse)
    library(gamm4)
    #> Loading required package: Matrix
    #> 
    #> Attaching package: 'Matrix'
    #> The following object is masked from 'package:tidyr':
    #> 
    #>     expand
    #> Loading required package: lme4
    #> Loading required package: mgcv
    #> Loading required package: nlme
    #> 
    #> Attaching package: 'nlme'
    #> The following object is masked from 'package:lme4':
    #> 
    #>     lmList
    #> The following object is masked from 'package:dplyr':
    #> 
    #>     collapse
    #> This is mgcv 1.8-28. For overview type 'help("mgcv-package")'.
    #> This is gamm4 0.2-5
    library(ggeffects)
    set.seed(1252)

    df <- gamSim(eg = 4, n = 400)
    #> Factor `by' variable example
    df <- df %>%
      mutate(id = rep(c("1","2","3","4","5"), each = 80 )) %>%
      mutate(x0 = scale(x0),
             x1 = scale(x1),
             x2 = scale(x2),
             y = rbinom(400,1,0.8))

    ### Model  

    df_gam <- gamm4::gamm4(y ~ s(x0) + s(x1) + s(x2)+ fac, random = ~ (1|id), data = df, family = binomial(link = "logit"))

    ### ggeffects predict method  

    ggpredict(df_gam, "x0") %>% plot()

![](https://i.imgur.com/dxR43As.png)

    ### manually  

    ## Create a grid of `x0` values at the average value of x1 and x2 at each level of the categorical variable.  

    ## Make predictions on this and average over the categorical variable `fac` to get the mean prediction and the associated interval   

    grid <- expand.grid(x0 = seq(-2,2 ,by = 0.01), x1 = 0, x2 = 0, fac = c("1","2","3"))

    x0_preds <- predict.gam(df_gam$gam, newdata = grid, type = "response", se.fit = TRUE)
    pred_df <- cbind(grid, as.data.frame(x0_preds))

    pred_df %>%
      group_by(x0) %>%
      mutate(fit = mean(fit)) %>%
      mutate(lower = fit - 2*se.fit, upper = fit + 2*se.fit) %>%
      summarize(fit = mean(fit), lower = mean(lower), upper = mean(upper)) %>% ## by grouping x0, average over the levels of fac
      ggplot(.,aes(x0, fit)) + geom_line() + geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.5) 

![](https://i.imgur.com/5pAPrvM.png)

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dshelldhillon** [comment]
The reprex made things clear. Earlier I was including the factor in the by statement in the s(x0, by = fac). I think that was causing problems.

**Comment by strengejacke** [comment]
`ggpredict()` uses the reference level, but `ggemmeans()` and `ggeffect()` average over factors. See also [this vignette](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html).

**Comment by dshelldhillon** [comment]
Thank you for the prompt response! It seems emmeans doesn't support gam and I get an error with `ggeffects` too.  

``` r
library(tidyverse)
library(gamm4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following object is masked from 'package:tidyr':
#> 
#>     expand
#> Loading required package: lme4
#> Loading required package: mgcv
#> Loading required package: nlme
#> 
#> Attaching package: 'nlme'
#> The following object is masked from 'package:lme4':
#> 
#>     lmList
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse
#> This is mgcv 1.8-28. For overview type 'help("mgcv-package")'.
#> This is gamm4 0.2-5
library(ggeffects)
library(emmeans)
#> 
#> Attaching package: 'emmeans'
#> The following object is masked from 'package:ggeffects':
#> 
#>     emm
library(effects)
#> Loading required package: carData
#> lattice theme set by effectsTheme()
#> See ?effectsTheme for details.
set.seed(1252)

df <- gamSim(eg = 4, n = 400)
#> Factor `by' variable example
df <- df %>%
  mutate(id = rep(c("1","2","3","4","5"), each = 80 )) %>%
  mutate(x0 = scale(x0),
         x1 = scale(x1),
         x2 = scale(x2),
         y = rbinom(400,1,0.8),
         fac2 = as_factor(map_chr(1:400, ~sample(1:3, 1, replace = TRUE))))


### Model  

df_gam <- gamm4::gamm4(y ~ s(x0) + s(x1) + s(x2)+ fac + fac2, random = ~ (1|id), data = df, family = binomial(link = "logit"))

ggeffect(df_gam, "x0") %>% plot()
#> `x0` was not found in model terms. Maybe misspelled?
#> Warning: Some model terms could not be found in model data. You probably
#> need to load the data into the environment.
#> Can't compute marginal effects, 'effects::Effect()' returned an error.
#> 
#> Reason: object 'y.0' not found
#> You may try 'ggpredict()' or 'ggemmeans()'.
#> 
#> Can't compute marginal effects, 'effects::Effect()' returned an error.
#> 
#> Reason: object 'prior.weights' not found
#> You may try 'ggpredict()' or 'ggemmeans()'.
#> Error in xy.coords(x, y, xlabel, ylabel, log): 'x' is a list, but does not have components 'x' and 'y'
```

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dshelldhillon** [comment]
Hi Daniel - were you able to reproduce this error above with ggeffects?

**Comment by strengejacke** [comment]
Yes, not sure, but probably gamm4 is neither supported by emmeans nor effects. You could only use `ggpredict()`. Maybe you can contact the maintainers of those packages and ask for support/implementation?
