### ISSUE TITLE
Possible to condition x range on the levels of a factor?

### ISSUE THREAD

**Issue by xmesminf** [strengejacke/ggeffects#98]
Dear all,

I am using ggeffects to visualize the effect of covariates on response variables and that works well. However, I recently tried to compute the effect of a covariate depending on the levels of a factor. Here are the codes I use:
```
# Model

m = glmer(Response ~ Factor * Covariate +
            (1 | Random), 
          data = dataset, 
          family = poisson(link = "log"))

Prediction = ggemmeans(model = m, terms = c("Covariate", "Factor"), 
                       type = "fe")
Prediction$predicted = log(Prediction$predicted + 1)
# I log-transform predictions so that the results are more easily readable in the figure.

# Graph

dataset$Response = log(dataset$Response + 1)
# I log-transform the Response variable for the same reason

Effect = ggplot() +
  geom_point(data = dataset,
             aes(x = Covariate, y = Response, colour = Factor, size = Same_Cov)) +
  labs(x = "Covariate", 
       y = "Response", 
       size = "Number of data with the same x value") +
  geom_line(data = Prediction, 
            aes(x = x, y = predicted, group = group, colour = group), 
            size = 1)
```

In my case, the problem is that the Covariate takes very different values depending on the level of the factor.

![Graph](https://user-images.githubusercontent.com/55758775/65665681-69406c00-e03c-11e9-9cc6-4bc8545714e8.png)

Consequently, I would like to have predictions only for "realistic" x-boundaries, that is, for level A, from ~ 18 to 23; for level B, from ~ 10 to 15 and for level C, from ~ 5 to 11 (see graph above). Ideally, I would like ggemmeans to compute the exact boundaries of x given the level of the factor used, and to perform the predictions with x taking values in these "appropriate" boundaries and not inside the whole range of x in my dataset.
Is there any way to do this with the arguments available in ggemmeans function?

Thank you very much.

**Comment by strengejacke** [comment]
No, you can't do this in the function call directly. What you could do is filter the data frame returned by `ggemmeans()`, so it only contains the empirical value ranges. Use `as.data.frame(Prediction)` to see the actual data frame.

**Comment by xmesminf** [comment]
Thank you very much for your quick answer. Then I will do as you suggest: filter x-values a posteriori before plotting the results.

**Comment by xmesminf** [comment]
For those who would be interested in this topic, specifying the number of x values used for prediction is crucial, because after filtering the data frame, there may be only one or two predictions inside the x-range retained. In my case I added "n=100" to have a satisfying overlapping of prediction curves and raw data on the x-axis:
`Prediction = ggemmeans(model = m, terms = c("Covariate [n=100]", "Factor"), type = "fe")`
