### ISSUE TITLE
Installation_problem

### ISSUE THREAD

**Issue by rikop85** [strengejacke/ggeffects#99]
**Question and context**

I am trying to instal the last version of the package with devtools (devtools::install_github("strengejacke/ggeffects"),  but I get these errors: 

checking for file 'C:\Users\albin\AppData\Local\Temp\Rtmps5Trxw\remotes63c6dfe7e35\strengejacke-ggeffects-d0ab127/DESCRIPTION' (3.5s)
-  preparing 'ggeffects': (9.4s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'ggeffects' ...
   ** R
   ** data
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error : object 'get_varcov' is not exported by 'namespace:insight'
   ERROR: lazy loading failed for package 'ggeffects'
-  removing 'C:/Users/albin/AppData/Local/Temp/Rtmp0QWhWX/Rinst2d48586277e9/ggeffects'
   In R CMD INSTALL
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'ggeffects' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** data
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error : object 'get_varcov' is not exported by 'namespace:insight'
E> ERROR: lazy loading failed for package 'ggeffects'
E> * removing 'C:/Users/albin/AppData/Local/Temp/Rtmp0QWhWX/Rinst2d48586277e9/ggeffects'
E> In R CMD INSTALL
E>       -----------------------------------
E> ERROR: package installation failed

Any suggestion?

**Comment by strengejacke** [comment]
You need to install the latest GitHub version from [*insight*](https://github.com/easystats/insight) first. However, the current dev-version of ggeffects contains not yet any new features for users, so you're ok updating the latest ggeffect 0.12.0 from CRAN as well (which is quite new anyway).
